part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 15. 투팩벌처 미러 (벌처 컨트롤 대결)
// ----------------------------------------------------------
const _tvt2facPushMirror = ScenarioScript(
  id: 'tvt_2fac_push_mirror',
  matchup: 'TvT',
  homeBuildIds: ['tvt_2fac_push'],
  awayBuildIds: ['tvt_2fac_push'],
  description: '투팩 벌처 컨트롤 대결',
  phases: [
    // ── Phase 0: 오프닝 (가스 먼저 → 배럭 → 가스 채취 → 팩토리 → 2번째 팩토리 → 머신샵) ──
    // build_timings.md: 리파이너리(1:18) → 배럭(1:38) → 팩토리(2:31) → 2팩(3:05) → 머신샵(3:22)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      recoveryArmyPerLine: 0,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 가스를 먼저 올립니다. 가스가 많이 드는 빌드인가봅니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -100, // 리파이너리(100)
          altText: '{home} 선수 가스부터 건설합니다. 한번 지켜보죠.',
        ),
        ScriptEvent(
          text: '{away} 선수도 가스를 먼저 올립니다. 일반적으로 가지는 않겠다 이거죠.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -100,
          altText: '{away} 선수도 가스부터. 가스가 많이 필요한 빌드를 준비하고 있는 것 같습니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 배럭 건설합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -150, // 배럭(150)
          altText: '{home} 선수 배럭을 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 배럭 건설합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -150,
          altText: '{away} 선수도 배럭을 올립니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 가스가 모이고 팩토리 건설합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -300, // 팩토리(300)
          altText: '{home} 선수 가스 100이 모여 팩토리를 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 팩토리 건설.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -300,
          altText: '{away} 선수도 팩토리를 올립니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 두 번째 팩토리 건설합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -300, // 팩토리(300)
          altText: '{home} 선수 두 번째 팩토리를 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 두 번째 팩토리를 올립니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -300,
          altText: '{away} 선수도 두 번째 팩토리 건설.',
        ),
        ScriptEvent(
          text: '{home} 선수 마린 한두 기 뽑고 배럭을 띄웁니다. 첫 팩토리에 머신샵을 붙입니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 1, // 마린 1기 (1sup)
          homeResource: -150, // 마린(50) + 머신샵(100)
          altText: '{home} 선수 마린 생산 후 배럭 플로팅. 머신샵 부착합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 마린 생산 후 배럭을 띄웁니다. 머신샵을 붙이죠.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 1,
          awayResource: -150,
          altText: '{away} 선수도 마린 뽑고 배럭 플로팅. 머신샵 부착.',
        ),
        ScriptEvent(
          text: '두 선수 모두 공격적인 빌드를 선택했습니다! 병력 구성이나 컨트롤로 승패가 갈릴 수 있습니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.2,
          altText: '양쪽 다 공격적인 선택입니다! 팩토리 두 개로 빠르게 밀겠다는 거죠.',
        ),
      ],
    ),
    // ── Phase 1: 빌드 변형 분기 ──
    // 변형1: 탱크+벌처 러쉬 (머신샵→탱크→시즈모드→탱크2기 추가→속업+마인 후 벌처 충원)
    // 변형2: 마인+속업 벌처 러쉬 (머신샵→마인업→벌처 양산→속업→벌처 물량 압박)
    // 변형3: 혼합 메카닉 (머신샵+아머리→탱크+시즈모드→벌처+골리앗 혼합 압박)
    ScriptPhase(
      name: 'build_variant',
      recoveryArmyPerLine: 1,
      branches: [
        // ── 변형1: 3탱크+벌처 러쉬 (홈) ──
        ScriptBranch(
          id: 'home_tank_rush',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{home} 선수 머신샵에서 탱크 생산을 시작합니다. 시즈모드 연구도 들어갑니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -550, // 탱크(250) + 시즈모드(300)
              altText: '{home} 선수 탱크부터 뽑습니다. 시즈모드 연구 시작.',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크 2기를 더 생산합니다. 두 번째 팩토리에서도 벌처가 나옵니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 6, // 탱크 2기(4sup) + 벌처 1기(2sup)
              homeResource: -575, // 탱크 2기(500) + 벌처(75)
              altText: '{home} 선수 탱크 3기 편성 완료. 벌처도 충원합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 시즈모드 완료! 탱크 3기와 벌처로 전진합니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -75, // 벌처 1기 추가
              altText: '{home} 선수 시즈 탱크 3기 러쉬! 벌처가 호위합니다!',
            ),
            ScriptEvent(
              text: '탱크 3기에 시즈모드! 벌처가 시야를 밝히며 호위합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '무거운 병력이 나왔습니다! 탱크 화력으로 밀겠다는 겁니다!',
            ),
          ],
        ),
        // ── 변형1: 3탱크+벌처 러쉬 (어웨이) ──
        ScriptBranch(
          id: 'away_tank_rush',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{away} 선수 머신샵에서 탱크 생산을 시작합니다. 시즈모드 연구도 들어갑니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -550,
              altText: '{away} 선수 탱크부터 뽑습니다. 시즈모드 연구 시작.',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크 2기를 더 생산합니다. 두 번째 팩토리에서 벌처도 나옵니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 6,
              awayResource: -575,
              altText: '{away} 선수 탱크 3기 편성 완료. 벌처도 충원합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 시즈모드 완료! 탱크 3기와 벌처로 전진합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -75,
              altText: '{away} 선수 시즈 탱크 3기 러쉬! 벌처가 호위합니다!',
            ),
            ScriptEvent(
              text: '탱크 3기에 시즈모드! 정면 화력으로 밀겠다는 겁니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '무거운 병력이 나왔습니다! 시즈 화력이 강력합니다!',
            ),
          ],
        ),
        // ── 변형2: 마인+속업 벌처 물량 러쉬 (홈) ──
        ScriptBranch(
          id: 'home_mine_vulture',
          baseProbability: 1.2,
          events: [
            ScriptEvent(
              text: '{home} 선수 머신샵에서 마인 업그레이드를 시작합니다. 벌처도 계속 생산.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -175, // 마인업(100) + 벌처(75)
              altText: '{home} 선수 마인 업글. 벌처와 마인으로 견제하겠다는 겁니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 두 번째 팩토리에서도 벌처를 뽑습니다. 속업 연구도 시작합니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 4, homeResource: -350, // 벌처 2기(150) + 속업(200)
              altText: '{home} 선수 속업 연구. 팩토리 두 개에서 벌처가 쏟아집니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 속업 완료! 마인을 깔면서 벌처로 상대를 압박합니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 4, homeResource: -150, // 벌처 2기 추가
              altText: '{home} 선수 속업 벌처가 쏟아집니다! 마인을 깔며 전진!',
            ),
            ScriptEvent(
              text: '마인과 속업 벌처! 기동력으로 상대를 괴롭히겠다는 겁니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '벌처 물량에 마인까지! 상대 SCV가 위험합니다!',
            ),
          ],
        ),
        // ── 변형2: 마인+속업 벌처 물량 러쉬 (어웨이) ──
        ScriptBranch(
          id: 'away_mine_vulture',
          baseProbability: 1.2,
          events: [
            ScriptEvent(
              text: '{away} 선수 머신샵에서 마인 업그레이드를 시작합니다. 벌처도 계속 생산.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -175,
              altText: '{away} 선수 마인 업글. 벌처와 마인으로 견제하겠다는 겁니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 두 번째 팩토리에서도 벌처를 뽑습니다. 속업 연구도 시작합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4, awayResource: -350,
              altText: '{away} 선수 속업 연구. 팩토리 두 개에서 벌처가 쏟아집니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 속업 완료! 마인을 깔면서 벌처로 상대를 압박합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4, awayResource: -150,
              altText: '{away} 선수 속업 벌처가 쏟아집니다! 마인을 깔며 전진!',
            ),
            ScriptEvent(
              text: '마인과 속업 벌처! 기동력으로 상대를 괴롭히겠다는 겁니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '벌처 물량에 마인까지! 상대 SCV가 위험합니다!',
            ),
          ],
        ),
        // ── 변형3: 혼합 메카닉 (홈) ──
        ScriptBranch(
          id: 'home_mixed_mech',
          baseProbability: 0.8,
          events: [
            ScriptEvent(
              text: '{home} 선수 머신샵에서 탱크 생산, 아머리도 건설합니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -550, // 탱크(250) + 시즈모드(300) (아머리는 뒤에)
              altText: '{home} 선수 탱크와 아머리를 동시에. 다양한 병력 조합을 노립니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 아머리가 완성됩니다. 골리앗도 생산 시작합니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 4, homeResource: -450, // 아머리(150) + 골리앗(150) + 벌처(75x2)
              altText: '{home} 선수 골리앗이 나옵니다. 탱크 벌처 골리앗 혼합 편성입니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크, 골리앗, 벌처 혼합 편성으로 전진합니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -150, // 골리앗(150)
              altText: '{home} 선수 다양한 병력 구성! 상대가 대응하기 까다롭습니다!',
            ),
            ScriptEvent(
              text: '탱크, 골리앗, 벌처 혼합입니다! 어떤 상황에도 대응할 수 있는 구성이죠.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '다양한 병력 구성! 정면에서도 견제에서도 강한 편성입니다.',
            ),
          ],
        ),
        // ── 변형3: 혼합 메카닉 (어웨이) ──
        ScriptBranch(
          id: 'away_mixed_mech',
          baseProbability: 0.8,
          events: [
            ScriptEvent(
              text: '{away} 선수 머신샵에서 탱크 생산, 아머리도 건설합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -550,
              altText: '{away} 선수 탱크와 아머리를 동시에. 다양한 조합을 노립니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 아머리가 완성됩니다. 골리앗도 생산 시작합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4, awayResource: -450,
              altText: '{away} 선수 골리앗이 나옵니다. 탱크 벌처 골리앗 혼합 편성입니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크, 골리앗, 벌처 혼합 편성으로 전진합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -150,
              altText: '{away} 선수 다양한 병력 구성! 상대가 대응하기 까다롭습니다!',
            ),
            ScriptEvent(
              text: '탱크, 골리앗, 벌처 혼합입니다! 다양한 구성으로 압박합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '혼합 편성! 정면에서도 견제에서도 강한 구성이죠.',
            ),
          ],
        ),
      ],
    ),
    // ── Phase 2: 벌처 교전 결과 - 분기 ──
    ScriptPhase(
      name: 'vulture_clash',
      recoveryArmyPerLine: 1,
      branches: [
        // 홈 벌처 우세
        ScriptBranch(
          id: 'home_vulture_win',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{home} 선수 벌처 컨트롤이 한 수 위입니다! 상대 벌처를 잡아냅니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -4, homeArmy: -2, // 벌처 2기 vs 1기 교환
              altText: '{home} 선수 벌처 컨트롤 차이! 상대 벌처 격파!',
            ),
            ScriptEvent(
              text: '{home} 선수 마인 매설로 맵 전체를 장악합니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 마인 매설. 맵 컨트롤을 가져갑니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 벌처로 상대 앞마당 SCV에 피해를 입힙니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -250, // SCV 견제 피해
              altText: '{home} 선수 SCV 견제 성공! 일꾼을 솎아냅니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 벌처 손실이 큽니다. 빨리 수습해야 합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
            ),
            ScriptEvent(
              text: '벌처 싸움에서 밀리면 맵 컨트롤과 일꾼을 동시에 잃습니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '벌처전 열세는 곧바로 자원 열세로 이어집니다.',
            ),
            // 근거리 맵: 벌처 견제 도착 빨라서 추가 피해
            ScriptEvent(
              text: '{home} 선수 근거리 맵이라 벌처가 바로 앞마당에 도착! 추가 SCV 피해!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -150,
              requiresMapTag: 'rushShort',
            ),
          ],
        ),
        // 어웨이 벌처 우세
        ScriptBranch(
          id: 'away_vulture_win',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{away} 선수 속업 타이밍이 더 빠릅니다! 상대 벌처를 따라잡아 격파!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4, awayArmy: -2,
              altText: '{away} 선수 속업 차이! 상대 벌처를 잡아냅니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 상대 앞마당으로 침투! SCV를 잡아냅니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -250,
              altText: '{away} 선수 앞마당 침투! SCV 대량 학살!',
            ),
            ScriptEvent(
              text: '{home} 선수 벌처를 잃고 앞마당 SCV까지 피해! 상당히 밀립니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
            ),
            ScriptEvent(
              text: '{away} 선수 마인 매설로 맵 장악. 상대 이동을 봉쇄합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 마인으로 맵 봉쇄! 상대가 갇혔습니다.',
            ),
            ScriptEvent(
              text: '벌처 컨트롤 차이가 게임을 결정짓고 있습니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '벌처전에서 밀리면 확장도 못 가고 갇히게 됩니다.',
            ),
            // 근거리 맵: 벌처 견제 도착 빨라서 추가 피해
            ScriptEvent(
              text: '{away} 선수 근거리 맵이라 벌처가 바로 도착! SCV 피해가 더 큽니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -150,
              requiresMapTag: 'rushShort',
            ),
          ],
        ),
        // 홈 벌처 압살 → 조기 종료
        ScriptBranch(
          id: 'home_vulture_crush',
          baseProbability: 0.5,
          conditionStat: 'harass',
          events: [
            ScriptEvent(
              text: '{home} 선수 벌처가 상대 벌처를 전멸시킵니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -6, homeArmy: -2,
              altText: '{home} 선수 벌처 컨트롤 압도! 상대 벌처가 전멸!',
            ),
            ScriptEvent(
              text: '{home} 선수 벌처가 상대 앞마당으로 돌진합니다! SCV를 대량 학살!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -400,
              altText: '{home} 선수 벌처 난입! SCV가 줄줄이 터집니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 본진까지 침투! SCV가 녹아내립니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -300,
              altText: '{home} 선수 본진 SCV까지 타격! 자원 채취가 마비됩니다!',
            ),
            ScriptEvent(
              text: '벌처에 SCV를 너무 많이 잃었습니다! 회복이 불가능합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{home} 선수 벌처 견제가 치명적입니다! 상대가 버틸 수 없습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 벌처 난동이 계속됩니다! SCV가 일할 수 없습니다!',
            ),
          ],
        ),
        // 어웨이 벌처 압살 → 조기 종료
        ScriptBranch(
          id: 'away_vulture_crush',
          baseProbability: 0.5,
          conditionStat: 'harass',
          events: [
            ScriptEvent(
              text: '{away} 선수 벌처가 상대 벌처를 전멸시킵니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -6, awayArmy: -2,
              altText: '{away} 선수 벌처 컨트롤 압도! 상대 벌처가 전멸!',
            ),
            ScriptEvent(
              text: '{away} 선수 벌처가 상대 앞마당 SCV를 대량으로 잡아냅니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -400,
              altText: '{away} 선수 벌처 난입! SCV가 줄줄이 터집니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 본진까지 침투! SCV가 녹아내립니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -300,
              altText: '{away} 선수 본진 SCV까지 타격! 자원 채취가 마비됩니다!',
            ),
            ScriptEvent(
              text: '벌처에 SCV를 너무 많이 잃었습니다! 회복이 불가능합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{away} 선수 벌처 견제가 치명적입니다! 상대가 버틸 수 없습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 벌처 난동이 계속됩니다! SCV가 일할 수 없습니다!',
            ),
          ],
        ),
        // 교착
        ScriptBranch(
          id: 'vulture_stalemate',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '양측 벌처가 비등합니다. 서로 마인만 깔고 물러납니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '벌처전 교착. 양측 마인을 깔며 견제합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 벌처로 상대 앞마당을 찔러봅니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -100,
              skipChance: 0.4,
              altText: '{home} 선수 벌처 견제. SCV 몇 기를 잡습니다.',
            ),
            ScriptEvent(
              text: '{away} 선수도 벌처로 반대편을 찌릅니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -100,
              skipChance: 0.4,
              altText: '{away} 선수도 벌처 견제. 서로 SCV를 교환합니다.',
            ),
            ScriptEvent(
              text: '교착 상태입니다. 탱크 전환 타이밍이 관건입니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.5,
              altText: '벌처전이 비등하면 탱크를 먼저 내는 쪽이 유리합니다.',
            ),
          ],
        ),
      ],
    ),
    // ── Phase 3: 병력 보충 + 추가 생산 ──
    ScriptPhase(
      name: 'reinforcement',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 탱크와 벌처를 추가 생산합니다. 병력을 보충합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 4, homeResource: -325, // 탱크(250) + 벌처(75)
          altText: '{home} 선수 병력 충원. 팩토리 두 개가 쉬지 않고 돌아갑니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 병력을 보충합니다. 팩토리 두 개에서 유닛이 쏟아집니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 4, awayResource: -325,
          altText: '{away} 선수도 탱크와 벌처를 추가합니다.',
        ),
        ScriptEvent(
          text: '팩토리 두 개의 생산력! 병력이 빠르게 불어납니다. 확장 타이밍이 관건입니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.4,
          altText: '병력이 쌓이고 있습니다. 확장을 언제 가느냐가 승부입니다.',
        ),
      ],
    ),
    // ── Phase 4: 확장 타이밍 분기 ──
    // 미러전이라도 확장 타이밍에 차이가 생길 수 있음
    ScriptPhase(
      name: 'expansion_timing',
      recoveryArmyPerLine: 2,
      branches: [
        // ── 동시 확장: 양측 비슷한 타이밍에 앞마당 ──
        ScriptBranch(
          id: 'both_expand',
          baseProbability: 1.5,
          events: [
            ScriptEvent(
              text: '{home} 선수 앞마당 커맨드센터를 올립니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -400,
              altText: '{home} 선수 앞마당 확장. 벌처전이 정리되니 확장을 갑니다.',
            ),
            ScriptEvent(
              text: '{away} 선수도 앞마당을 확장합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -400,
              altText: '{away} 선수도 앞마당 커맨드. 자원 싸움입니다.',
            ),
            ScriptEvent(
              text: '양측 비슷한 타이밍에 확장을 갔습니다. 탱크 수 싸움으로 넘어갑니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.4,
              altText: '동시 확장. 자원이 비등하니 컨트롤이 승부를 가릅니다.',
            ),
            // 벌처 견제
            ScriptEvent(
              text: '{home} 선수 벌처를 보내 상대 확장을 견제합니다. SCV를 괴롭힙니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -150,
              skipChance: 0.4,
              altText: '{home} 선수 벌처 견제. 상대 앞마당 SCV를 잡습니다.',
            ),
            ScriptEvent(
              text: '{away} 선수도 벌처 견제. 상대 확장 SCV를 노립니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -150,
              skipChance: 0.4,
              altText: '{away} 선수 벌처로 상대 앞마당을 찌릅니다.',
            ),
          ],
        ),
        // ── 홈 빠른 확장: 일찍 확장하지만 어웨이가 병력 우위로 공격 ──
        ScriptBranch(
          id: 'home_fast_expand',
          baseProbability: 0.7,
          events: [
            ScriptEvent(
              text: '{home} 선수 탱크보다 확장을 먼저 올립니다! 위험하지만 자원을 확보하려 합니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -400,
              altText: '{home} 선수 빠른 앞마당! 병력이 얇아지지만 자원을 확보합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 확장 대신 탱크를 추가 생산합니다! 병력 차이를 만듭니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4, awayResource: -250,
              altText: '{away} 선수 확장을 미루고 탱크와 벌처를 더 뽑습니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 상대 확장 타이밍을 노립니다! 탱크와 벌처로 전진!',
              owner: LogOwner.away,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: -4, homeResource: -200,
              altText: '{away} 선수 병력 우위로 밀어붙입니다! 확장에 투자한 자원이 아깝습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 확장을 갔지만 병력이 부족합니다! 수비가 어렵습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              altText: '{home} 선수 확장 비용만큼 병력이 모자랍니다!',
            ),
            ScriptEvent(
              text: '빠른 확장의 대가! 병력이 얇은 틈을 찔립니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '확장을 서두른 대가가 크네요. 병력 차이가 벌어집니다.',
            ),
          ],
        ),
        // ── 어웨이 빠른 확장: 일찍 확장하지만 홈이 병력 우위로 공격 ──
        ScriptBranch(
          id: 'away_fast_expand',
          baseProbability: 0.7,
          events: [
            ScriptEvent(
              text: '{away} 선수 탱크보다 확장을 먼저 선택합니다! 자원 확보를 서두릅니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -400,
              altText: '{away} 선수 빠른 앞마당! 위험하지만 장기전을 노립니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 확장 대신 탱크를 추가합니다! 병력 우위를 만듭니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 4, homeResource: -250,
              altText: '{home} 선수 확장을 미루고 병력을 더 뽑습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 상대가 확장에 자원을 쓴 틈! 탱크와 벌처로 전진!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -4, awayResource: -200,
              altText: '{home} 선수 병력 우위로 밀어붙입니다! 확장 직후 약한 틈!',
            ),
            ScriptEvent(
              text: '{away} 선수 확장은 올렸지만 병력이 부족합니다! 수비가 위험합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              altText: '{away} 선수 확장 비용만큼 병력이 모자랍니다!',
            ),
            ScriptEvent(
              text: '빠른 확장의 대가! 병력이 얇은 틈을 찔립니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '확장을 서두른 대가가 크네요. 병력 차이가 벌어집니다.',
            ),
          ],
        ),
        // ── 홈 확장 스킵 공격: 확장 안 하고 병력으로 상대 확장 파괴 → 조기 종료 ──
        ScriptBranch(
          id: 'home_skip_expand_attack',
          baseProbability: 0.4,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{home} 선수 확장을 안 갑니다! 탱크와 벌처를 계속 뽑습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 6, homeResource: -500,
              altText: '{home} 선수 확장 포기! 올인 병력 생산!',
            ),
            ScriptEvent(
              text: '{away} 선수 앞마당을 확장합니다. 상대가 확장을 안 간 걸 모릅니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -400,
              altText: '{away} 선수 앞마당 확장. 아직 상대 빌드를 모르고 있습니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크와 벌처 물량으로 상대 앞마당을 급습합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -6, awayResource: -300,
              altText: '{home} 선수 확장 포기한 만큼의 병력! 앞마당을 밀어버립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 병력이 압도적으로 부족합니다! 확장에 자원을 쏟아서 막을 수 없습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              altText: '{away} 선수 확장 비용이 발목을 잡습니다! 탱크가 너무 적습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 확장 포기 올인! 상대 앞마당이 무너집니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 병력 차이가 압도적입니다! 상대가 버틸 수 없습니다!',
            ),
          ],
        ),
        // ── 어웨이 확장 스킵 공격: 확장 안 하고 올인 ──
        ScriptBranch(
          id: 'away_skip_expand_attack',
          baseProbability: 0.4,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{away} 선수 확장을 안 갑니다! 탱크와 벌처를 계속 뽑습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 6, awayResource: -500,
              altText: '{away} 선수 확장 포기! 올인 병력 생산!',
            ),
            ScriptEvent(
              text: '{home} 선수 앞마당을 확장합니다. 상대 빌드를 아직 확인 못 했습니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -400,
              altText: '{home} 선수 앞마당 커맨드. 상대가 확장을 안 간 걸 모릅니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크와 벌처 물량으로 상대 앞마당을 급습합니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: -6, homeResource: -300,
              altText: '{away} 선수 확장 포기한 만큼의 병력! 앞마당을 밀어버립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 병력이 압도적으로 부족합니다! 확장에 자원을 써서 탱크가 모자랍니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              altText: '{home} 선수 확장 비용이 발목을 잡습니다! 수비가 불가능합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 확장 포기 올인! 상대 앞마당이 무너집니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 병력 차이가 압도적입니다! 상대가 버틸 수 없습니다!',
            ),
          ],
        ),
      ],
    ),
    // ── Phase 5: 시즈 모드 완료 + 거리재기 ──
    ScriptPhase(
      name: 'siege_mode',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 시즈 모드 연구 완료. 탱크가 자리를 잡습니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '{home} 선수 시즈 모드 완료. 센터에 라인을 긋습니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 시즈 모드 완료. 양측 탱크 라인이 형성됩니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '{away} 선수도 시즈 라인. 센터에서 거리재기가 시작됩니다.',
        ),
        ScriptEvent(
          text: '시즈 모드가 완료됐습니다. 거리재기 시작입니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.3,
          altText: '테테전의 꽃, 시즈 탱크 라인 긋기 싸움입니다.',
        ),
        // 거리재기
        ScriptEvent(
          text: '{home} 선수 벌처로 시야를 밝히고 시즈 포격! 상대 탱크가 맞습니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -2,
          skipChance: 0.4,
          altText: '{home} 선수 벌처 시야 확보 후 시즈 포격! 상대 탱크를 깎습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 탱크를 전진시켜 사거리를 잡습니다. 포격! {home} 탱크가 터집니다!',
          owner: LogOwner.away,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -2,
          skipChance: 0.4,
          altText: '{away} 선수 사거리 끝에서 포격! {home} 탱크를 잡습니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 벌처로 측면을 돌아 상대 탱크 뒤를 찌릅니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -1,
          skipChance: 0.5,
          altText: '{home} 선수 벌처가 상대 라인 뒤쪽으로 침투합니다!',
        ),
        ScriptEvent(
          text: '{away} 선수도 벌처로 상대 라인 뒤를 찌릅니다. SCV를 잡습니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -150,
          skipChance: 0.5,
          altText: '{away} 선수 벌처 침투. 상대 후방 SCV에 피해를 줍니다.',
        ),
        ScriptEvent(
          text: '사거리 싸움이 치열합니다. 탱크 한 대 차이가 승부를 가릅니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.3,
          altText: '먼저 자리 잡는 쪽이 센터의 주인입니다.',
        ),
        // 복잡 지형 맵: 고지대 시즈 배치
        ScriptEvent(
          text: '언덕 위 시즈모드. 테테전에서 가장 무서운 지형지물이죠.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          requiresMapTag: 'terrainHigh',
          skipChance: 0.5,
        ),
        ScriptEvent(
          text: '{home} 선수 고지대를 점령하고 시즈 포격! 아래에서는 사거리가 안 닿습니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -2,
          requiresMapTag: 'terrainHigh',
          skipChance: 0.5,
          altText: '{home} 선수 지형을 활용한 시즈 배치! 상대가 올라올 수 없습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수도 반대편 고지대에 탱크를 올립니다. 지형 싸움.',
          owner: LogOwner.away,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -2,
          requiresMapTag: 'terrainHigh',
          skipChance: 0.5,
          altText: '{away} 선수 고지대 시즈로 응수! 서로 고지를 점령합니다.',
        ),
        // 근거리 맵: 시즈 거리재기가 더 치열
        ScriptEvent(
          text: '{home} 선수 근거리라 탱크가 바로 사거리에 들어옵니다! 시즈 포격!',
          owner: LogOwner.home,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -2,
          requiresMapTag: 'rushShort',
          skipChance: 0.5,
        ),
        ScriptEvent(
          text: '{away} 선수도 근거리 맵 이점을 살려 시즈 포격!',
          owner: LogOwner.away,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -2,
          requiresMapTag: 'rushShort',
          skipChance: 0.5,
        ),
        // 원거리 맵: 멀티 확장 여유
        ScriptEvent(
          text: '원거리 맵이라 멀티 확장이 안전합니다. 양측 자원이 풍부해집니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 200, awayResource: 200,
          requiresMapTag: 'rushLong',
        ),
      ],
    ),
    // ── Phase 5: 탱크 라인 압도 → 조기 종료 가능 ──
    ScriptPhase(
      name: 'siege_dominance',
      recoveryArmyPerLine: 2,
      branches: [
        // 시즈 거리재기에서 큰 차이 없이 계속 진행
        ScriptBranch(
          id: 'siege_continues',
          baseProbability: 1.5,
          events: [
            ScriptEvent(
              text: '양측 탱크 라인이 팽팽합니다. 골리앗 전환으로 넘어갑니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.4,
              altText: '시즈 대치가 이어집니다. 다음 테크가 관건입니다.',
            ),
          ],
        ),
        // 홈 탱크 라인 압도 → 밀어붙여서 끝냄
        ScriptBranch(
          id: 'home_siege_crush',
          baseProbability: 0.5,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{home} 선수 거리재기에서 탱크 수 차이가 벌어졌습니다! 라인을 밀어붙입니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -6, homeArmy: -2,
              altText: '{home} 선수 탱크 라인 우위! 상대 탱크를 밀어냅니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크 라인이 상대 앞마당까지 진입합니다! 시즈 포격!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -4, awayResource: -300,
              altText: '{home} 선수 앞마당까지 시즈! 상대가 무너집니다!',
            ),
            ScriptEvent(
              text: '탱크 라인에서 밀리면 회복이 안 됩니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '조이기 라인이 풀리지 않습니다. 서서히 말라 죽어가네요.',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크 라인이 상대 진영을 압박합니다! 탱크 수 차이가 큽니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 시즈 화력 우위! 상대가 라인을 유지하기 어렵습니다!',
            ),
          ],
        ),
        // 어웨이 탱크 라인 압도 → 밀어붙여서 끝냄
        ScriptBranch(
          id: 'away_siege_crush',
          baseProbability: 0.5,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{away} 선수 거리재기에서 탱크 수가 앞섭니다! 라인을 밀어붙입니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -6, awayArmy: -2,
              altText: '{away} 선수 탱크 라인 우위! 상대 탱크를 밀어냅니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크 라인이 상대 앞마당까지 진입! 시즈 포격!',
              owner: LogOwner.away,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: -4, homeResource: -300,
              altText: '{away} 선수 앞마당까지 시즈! 상대가 무너집니다!',
            ),
            ScriptEvent(
              text: '탱크 라인에서 밀리면 회복이 안 됩니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '압도적인 화력! 이건 컨트롤로 극복이 안 됩니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크 라인이 상대 진영을 압박합니다! 탱크 수 차이가 큽니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 시즈 화력 우위! 상대가 라인을 유지하기 어렵습니다!',
            ),
          ],
        ),
      ],
    ),
    // ── Phase 6: 아머리 + 골리앗 전환 ──
    ScriptPhase(
      name: 'siege_goliath',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 아머리 건설. 골리앗 생산을 시작합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -300, // 아머리(150) + 골리앗(150)
          homeArmy: 2,
          altText: '{home} 선수 아머리를 올리고 골리앗으로 전환합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 아머리. 골리앗 체제로 넘어갑니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayResource: -300,
          awayArmy: 2,
          altText: '{away} 선수도 골리앗 생산. 화력이 두꺼워집니다.',
        ),
        ScriptEvent(
          text: '시즈 탱크에 골리앗이 합류하면서 정면 화력이 올라갑니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.4,
          altText: '인구수가 올라갑니다. 곧 한 방이 터질 수 있습니다.',
        ),
        // 거리재기 - 골리앗 합류 후
        ScriptEvent(
          text: '{home} 선수 탱크 한 칸 전진. 시즈 포격! 상대 골리앗이 맞습니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -2,
          skipChance: 0.4,
          altText: '{home} 선수 거리재기! 사거리 끝에서 상대 골리앗을 깎습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 탱크 재배치 후 포격! {home} 탱크를 잡습니다!',
          owner: LogOwner.away,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -2,
          skipChance: 0.4,
          altText: '{away} 선수 맞포격! 탱크 사거리 싸움에서 한 대를 잡습니다!',
        ),
        // 트리플 확장
        ScriptEvent(
          text: '{home} 선수 세 번째 확장을 올립니다. 자원을 확보하려 합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -400,
          altText: '{home} 선수 트리플 커맨드. 자원 라인을 늘립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 확장 타이밍을 노립니다! 병력이 빠진 틈을 찌릅니다!',
          owner: LogOwner.away,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -2,
          skipChance: 0.5,
          altText: '{away} 선수 확장 직후를 노린 포격! 병력이 얇은 틈!',
        ),
        ScriptEvent(
          text: '{away} 선수도 세 번째 확장을 올립니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -400,
          altText: '{away} 선수도 트리플. 자원을 확보합니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 상대 확장 타이밍에 벌처를 보냅니다! SCV 견제!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -150,
          skipChance: 0.5,
          altText: '{home} 선수 확장 틈을 노린 견제! SCV를 잡습니다!',
        ),
        // 팩토리 추가
        ScriptEvent(
          text: '{home} 선수 추가 팩토리 건설. 병력 보충이 빨라집니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -300,
          skipChance: 0.4,
          altText: '{home} 선수 팩토리 추가. 물량이 더 빨리 늘어납니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 추가 팩토리 건설.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -300,
          skipChance: 0.4,
          altText: '{away} 선수도 팩토리 추가. 생산을 맞춥니다.',
        ),
      ],
    ),
    // ── Phase 7: 풀 메카닉 (스타포트 + 드랍십) ──
    ScriptPhase(
      name: 'full_mech',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 스타포트 건설. 드랍십을 준비합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -250, // 스타포트 250
          altText: '{home} 선수 스타포트를 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 스타포트를 올립니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -250,
          altText: '{away} 선수도 스타포트 건설. 드랍 준비입니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 드랍십 생산. 벌처로 시야를 확보하면서 타이밍을 재고 있습니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 2, homeResource: -200,
          altText: '{home} 선수 드랍십 완성. 출격 시점을 노리고 있습니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 드랍십 생산. 골리앗을 대공 위치에 배치합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2, awayResource: -200,
          altText: '{away} 선수도 드랍십. 양측 풀 메카닉 체제입니다.',
        ),
        ScriptEvent(
          text: '시즈탱크, 골리앗, 드랍십. 풀 메카닉 체제입니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.4,
          altText: '양측 풀 메카닉. 드랍이냐 정면이냐가 관건입니다.',
        ),
        ScriptEvent(
          text: '골리앗 비율을 높여서 드랍십을 원천 봉쇄합니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.6,
          altText: '팩토리가 쉴 새 없이 돌아갑니다. 물량전 예고입니다.',
        ),
        // 공중 개방 맵: 드랍 경로가 다양해서 드랍 위협 증가
        ScriptEvent(
          text: '공중이 열린 맵입니다. 드랍 경로가 다양해서 골리앗 배치가 어렵습니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          requiresMapTag: 'airHigh',
        ),
        // 원거리 맵: 드랍 이동 시간이 길어서 탐지 가능
        ScriptEvent(
          text: '원거리 맵이라 드랍십 이동이 오래 걸립니다. 정찰할 시간이 있습니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          requiresMapTag: 'rushLong',
        ),
      ],
    ),
    // ── Phase 9: 드랍 운영 + 교전 - 분기 ──
    // 드랍은 항상 올인이 아님: 게릴라 견제 / 유리한 쪽 마무리 / 불리한 쪽 역전 / 정면
    ScriptPhase(
      name: 'drop_warfare',
      recoveryArmyPerLine: 2,
      branches: [
        // ── 게릴라 드랍 (홈): 확장 견제 후 회수, 자잘한 피해 ──
        ScriptBranch(
          id: 'home_guerrilla_drop',
          baseProbability: 1.2,
          events: [
            ScriptEvent(
              text: '{home} 선수 드랍십에 탱크 한 대를 싣고 상대 확장기지로 향합니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 드랍십 출격. 상대 확장을 견제합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 확장기지에 탱크를 내리고 SCV를 잡습니다! 바로 회수!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -200,
              altText: '{home} 선수 확장 드랍 성공! SCV 피해를 주고 빠집니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 골리앗을 돌렸지만 이미 드랍십이 빠져나갑니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 수비를 왔지만 드랍십은 이미 회수 완료.',
            ),
            ScriptEvent(
              text: '게릴라 드랍! 큰 피해는 아니지만 상대 시선을 분산시킵니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '드랍 견제로 상대 병력이 분산됩니다. 정면이 얇아지는 틈!',
            ),
            ScriptEvent(
              text: '{home} 선수 드랍으로 시선을 끈 사이 정면 탱크를 한 칸 전진시킵니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              skipChance: 0.4,
              altText: '{home} 선수 드랍 타이밍에 맞춰 거리재기! 상대 탱크를 잡습니다!',
            ),
            // 공중 개방 맵: 드랍 경로가 다양
            ScriptEvent(
              text: '공중이 열린 맵이라 드랍 경로를 바꿔가며 계속 견제합니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              requiresMapTag: 'airHigh',
              skipChance: 0.5,
            ),
          ],
        ),
        // ── 게릴라 드랍 (어웨이): 확장 견제 후 회수 ──
        ScriptBranch(
          id: 'away_guerrilla_drop',
          baseProbability: 1.2,
          events: [
            ScriptEvent(
              text: '{away} 선수 드랍십에 탱크를 싣고 상대 트리플 확장으로 향합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 드랍십 출격. 상대 확장을 노립니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 확장기지에 탱크를 내려 SCV를 잡아냅니다! 빠르게 회수!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -200,
              altText: '{away} 선수 확장 드랍! SCV를 잡고 바로 탈출합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 골리앗이 뒤늦게 도착합니다. 이미 피해는 입었습니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 수비했지만 SCV 몇 기는 이미 잃었습니다.',
            ),
            ScriptEvent(
              text: '자잘한 드랍 견제가 쌓이면 자원 차이로 이어집니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '게릴라 운영! 드랍으로 상대 자원을 조금씩 깎아냅니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 드랍으로 시선을 끈 사이 정면에서 탱크 포격!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              skipChance: 0.4,
              altText: '{away} 선수 드랍 타이밍에 거리재기! 상대 탱크를 깎습니다!',
            ),
            // 공중 개방 맵
            ScriptEvent(
              text: '공중이 열린 맵이라 드랍 경로가 다양합니다. 수비가 어렵습니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              requiresMapTag: 'airHigh',
              skipChance: 0.5,
            ),
          ],
        ),
        // ── 마무리 드랍 (홈 유리): 유리한 쪽이 드랍과 정면 동시로 끝냄 ──
        ScriptBranch(
          id: 'home_finishing_drop',
          baseProbability: 0.7,
          events: [
            ScriptEvent(
              text: '{home} 선수 정면에서 앞서고 있습니다. 드랍십으로 확실하게 끝내려 합니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 병력 우위! 드랍과 정면 동시 공격을 준비합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 드랍십 두 대 출격! 상대 본진과 확장에 동시 투하!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: -300, awayArmy: -2,
              altText: '{home} 선수 멀티 드랍! 본진과 확장을 동시에 노립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 정면 탱크 라인도 전진! 수비할 곳이 세 군데입니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -4,
              altText: '{home} 선수 드랍과 정면 동시! 상대가 수비를 나눠야 합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 병력을 나눠야 합니다! 어디를 먼저 막을지 결정해야 합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              altText: '{away} 선수 수비 분산! 모든 곳을 막을 수 없습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 멀티 포인트 공격으로 상대를 완전히 무너뜨립니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 드랍과 정면 동시 공격! 수비가 붕괴됩니다!',
            ),
          ],
        ),
        // ── 마무리 드랍 (어웨이 유리): 유리한 쪽이 드랍과 정면 동시로 끝냄 ──
        ScriptBranch(
          id: 'away_finishing_drop',
          baseProbability: 0.7,
          events: [
            ScriptEvent(
              text: '{away} 선수 정면에서 앞서고 있습니다. 드랍으로 마무리하려 합니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 병력 우위! 드랍과 정면을 동시에 준비합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 드랍십 두 대 출격! 본진과 확장을 동시에 타격!',
              owner: LogOwner.away,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -300, homeArmy: -2,
              altText: '{away} 선수 멀티 드랍! 상대 후방을 초토화합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 정면에서도 탱크 라인을 밀어붙입니다! 세 방향 공격!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4,
              altText: '{away} 선수 드랍과 정면 동시! 상대가 갈립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 수비를 나눠야 하지만 병력이 부족합니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              altText: '{home} 선수 모든 곳을 막기 어렵습니다! 수비가 무너집니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 멀티 포인트 공격! 상대가 완전히 무너집니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 드랍과 정면 동시 공격으로 경기를 끝냅니다!',
            ),
          ],
        ),
        // ── 정면 교전: 드랍 없이 라인 싸움 ──
        ScriptBranch(
          id: 'frontal_clash',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '양측 드랍을 경계하며 골리앗을 대공 위치에 배치합니다. 정면 승부입니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '드랍 없이 정면 승부. 탱크 라인 싸움입니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크 한 칸 전진! 시즈 포격! {away} 탱크가 맞습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              skipChance: 0.4,
              altText: '{home} 선수 거리재기! 상대 탱크를 한 대 깎습니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크 재배치 후 맞포격! {home} 골리앗이 터집니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              skipChance: 0.4,
              altText: '{away} 선수 맞포격! {home} 병력을 깎습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크, 골리앗 라인을 전진시킵니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 4, homeResource: -400,
              altText: '{home} 선수 라인을 밀어붙입니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 골리앗 화력으로 맞섭니다! 정면 교전!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4, awayResource: -400,
              altText: '{away} 선수 정면에서 맞받습니다!',
            ),
            ScriptEvent(
              text: '정면 라인전! 시즈 포격 범위가 승부를 가릅니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '탱크 일점사! 상대 탱크 숫자 줄이는 데 집중합니다.',
            ),
          ],
        ),
        // ── 역전 드랍 (홈 불리): 올인 본진 드랍 ──
        ScriptBranch(
          id: 'home_desperate_drop',
          baseProbability: 0.6,
          events: [
            ScriptEvent(
              text: '{home} 선수 정면에서 밀리고 있습니다! 병력 차이가 벌어지고 있습니다!',
              owner: LogOwner.system,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4,
            ),
            ScriptEvent(
              text: '{home} 선수 드랍십 두 대에 탱크를 가득 싣습니다! 본진을 노립니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 대규모 드랍! 상대 본진 뒤를 노립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 상대 본진에 탱크 투하! 시즈 모드 전환! 팩토리가 터집니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: -500, awayArmy: -4,
              altText: '{home} 선수 본진 드랍 성공! 생산 라인을 타격합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 급히 병력을 돌리지만 이미 피해가 큽니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              altText: '{away} 선수 본진 생산 건물이 파괴됩니다! 생산이 끊깁니다!',
            ),
            ScriptEvent(
              text: '대역전극! 불리하던 경기를 드랍쉽 한 방으로 뒤집습니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '드랍쉽 한 대의 기적! 본진 팩토리 라인이 마비됐습니다.',
            ),
          ],
        ),
        // ── 역전 드랍 (어웨이 불리): 올인 본진 드랍 ──
        ScriptBranch(
          id: 'away_desperate_drop',
          baseProbability: 0.6,
          events: [
            ScriptEvent(
              text: '{away} 선수 정면에서 밀리고 있습니다! 탱크 수가 부족합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -4,
            ),
            ScriptEvent(
              text: '{away} 선수 드랍십 두 대에 탱크를 싣고 상대 본진으로 향합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 대규모 드랍! 승부수를 던집니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 상대 본진에 탱크 투하! 시즈 모드! 생산시설이 터집니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -500, homeArmy: -4,
              altText: '{away} 선수 본진 드랍 성공! 상대 팩토리를 부숩니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 병력을 돌리지만 생산시설 피해가 심각합니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              altText: '{home} 선수 본진 생산 건물이 파괴됩니다! 생산이 끊깁니다!',
            ),
            ScriptEvent(
              text: '역전 드랍! 불리했던 쪽이 생산력을 뒤집었습니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '드랍쉽 한 대의 기적! 본진 팩토리 라인이 마비됐습니다.',
            ),
          ],
        ),
        // ── 멀티 앞 수비병력 밀어내기 (홈): 드랍+지상 합공으로 멀티 파괴 ──
        ScriptBranch(
          id: 'home_multi_push',
          baseProbability: 0.8,
          events: [
            ScriptEvent(
              text: '{home} 선수 스캔으로 상대 추가 확장 앞 수비 라인을 확인합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{home} 선수 드랍쉽 편대가 수비 병력 위로! 동시에 지상 탱크도 전진합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 드랍과 지상 동시 공격! 상대 추가 확장을 노립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 수비 병력 뒤에 탱크 투하! 앞뒤로 시즈 포격이 쏟아집니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -6, homeArmy: -2,
              altText: '{home} 선수 양면 합공! 수비 라인이 무너집니다!',
            ),
            ScriptEvent(
              text: '수비 병력이 밀려나면서 추가 확장이 끊겼습니다! {away} 선수 자원 라인에 타격이 크네요.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -300,
              altText: '추가 확장을 지킬 수 없게 됐습니다! {away} 선수 멀티가 끊기면서 불리해집니다.',
            ),
          ],
        ),
        // ── 멀티 앞 수비병력 밀어내기 (어웨이) ──
        ScriptBranch(
          id: 'away_multi_push',
          baseProbability: 0.8,
          events: [
            ScriptEvent(
              text: '{away} 선수 스캔으로 상대 추가 확장 앞 수비 라인을 확인합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{away} 선수 드랍쉽 편대가 수비 병력 위로! 정면에서도 탱크를 밀어붙입니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 드랍과 지상 동시 공격! 상대 추가 확장을 끊으려 합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 수비 병력 뒤에 착지! 앞뒤로 시즈 포격!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -6, awayArmy: -2,
              altText: '{away} 선수 양면 합공! 수비 라인이 무너집니다!',
            ),
            ScriptEvent(
              text: '수비 병력이 녹아내리면서 추가 확장이 끊겼습니다! {home} 선수 멀티가 날아가면서 불리해집니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -300,
              altText: '추가 확장을 지킬 수가 없습니다! {home} 선수 자원 라인이 끊기면서 수비가 어려워지네요.',
            ),
          ],
        ),
        // ── 레이스 대공 (홈): 몰래 레이스를 모아 드랍쉽 격추 ──
        ScriptBranch(
          id: 'home_wraith_intercept',
          baseProbability: 0.5,
          events: [
            ScriptEvent(
              text: '{home} 선수 스타포트에서 레이스를 조용히 생산하고 있었습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 4, homeResource: -300, // 레이스 2기 (150x2, 2sup x2)
              altText: '{home} 선수 레이스를 몰래 뽑고 있었습니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 드랍쉽이 출격합니다! 상대 확장을 노립니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 드랍쉽에 병력을 싣고 출발합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 레이스가 드랍쉽을 포착! 드랍쉽이 격추됩니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -6,
              altText: '{home} 선수 레이스 매복! 드랍쉽이 터지면서 병력이 전부 떨어집니다!',
            ),
            ScriptEvent(
              text: '드랍쉽 격추! 안에 실린 병력까지 전부 잃었습니다! 큰 손실이에요.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '레이스 매복에 드랍쉽이 당했습니다! 병력 손실이 막대합니다.',
            ),
          ],
        ),
        // ── 레이스 대공 (어웨이): 몰래 레이스를 모아 드랍쉽 격추 ──
        ScriptBranch(
          id: 'away_wraith_intercept',
          baseProbability: 0.5,
          events: [
            ScriptEvent(
              text: '{away} 선수 스타포트에서 레이스를 조용히 모으고 있었습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4, awayResource: -300,
              altText: '{away} 선수 레이스를 몰래 뽑아두었습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 드랍쉽이 출격합니다! 상대 확장으로 향합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 드랍쉽에 병력을 싣고 출발합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 레이스가 드랍쉽을 포착! 드랍쉽이 격추됩니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -6,
              altText: '{away} 선수 레이스 매복! 드랍쉽이 터지면서 병력이 전부 떨어집니다!',
            ),
            ScriptEvent(
              text: '드랍쉽 격추! 안에 실린 병력까지 전부 잃었습니다! 큰 손실이에요.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '레이스 매복에 드랍쉽이 당했습니다! 병력 손실이 막대합니다.',
            ),
          ],
        ),
      ],
    ),
    // ── Phase 9: 결전 ──
    ScriptPhase(
      name: 'decisive_battle',
      recoveryArmyPerLine: 2,
      linearEvents: [
        // 결전 직전 거리재기
        ScriptEvent(
          text: '{home} 선수 벌처로 시야를 밝히고 탱크 포격! 상대 골리앗이 맞습니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -2,
          skipChance: 0.5,
          altText: '{home} 선수 결전 직전 거리재기! 시즈 포격으로 상대 병력을 깎습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수도 탱크 위치를 조정합니다. 포격! {home} 탱크가 터집니다!',
          owner: LogOwner.away,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -2,
          skipChance: 0.5,
          altText: '{away} 선수 맞포격! 사거리 끝에서 {home} 탱크를 잡습니다!',
        ),
        // 결전 전 대규모 교전
        ScriptEvent(
          text: '{home} 선수 탱크 라인을 전진시킵니다! 상대 골리앗과 정면 포격전!',
          owner: LogOwner.home,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -8, homeArmy: -6,
          skipChance: 0.3,
          altText: '{home} 선수 라인 전진! 상대 병력과 정면으로 부딪힙니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 시즈 포격으로 응사합니다! 양측 병력이 크게 줄어듭니다!',
          owner: LogOwner.away,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -8, awayArmy: -6,
          skipChance: 0.3,
          altText: '{away} 선수 맞포격! 양측 탱크가 대거 터집니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 전 병력 총동원! 최종 결전!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 6, homeResource: -400,
          altText: '{home} 선수 전 병력 결집! 마지막 승부입니다!',
        ),
        ScriptEvent(
          text: '{away} 선수도 전 병력 투입! 결전입니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 6, awayResource: -400,
          altText: '{away} 선수도 전 병력 배치! 마지막 한판!',
        ),
        ScriptEvent(
          text: '양측 전 병력 충돌! 여기서 밀리면 끝입니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.3,
          altText: '모든 병력 쏟아붓습니다! 마지막 결전이에요.',
        ),
        ScriptEvent(
          text: '{home} 선수 시즈 포격 집중! 상대 탱크가 터집니다!',
          owner: LogOwner.home,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -20, homeArmy: -10,
          altText: '{home} 선수 시즈 화력! 상대 탱크를 집중 타격합니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 골리앗 화력으로 반격합니다!',
          owner: LogOwner.away,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -20, awayArmy: -10,
          altText: '{away} 선수 골리앗으로 끝까지 저항합니다!',
        ),
      ],
    ),
    // ── Phase 10: 결전 판정 ──
    ScriptPhase(
      name: 'decisive_outcome',
      recoveryArmyPerLine: 2,
      branches: [
        ScriptBranch(
          id: 'home_wins_decisive',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{home} 선수 탱크와 벌처로 상대 라인을 돌파합니다! {away} 선수 앞마당에서 본진까지 밀립니다!',
              altText: '{home} 선수 마인 활용이 적절합니다! 상대 탱크를 잡아냅니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        ScriptBranch(
          id: 'away_wins_decisive',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{away} 선수 탱크와 벌처로 수비 라인 돌파! {home} 선수 앞마당에서 본진까지 밀립니다!',
              altText: '{away} 선수 마인 매설로 맵을 장악! 상대 이동을 봉쇄합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
