part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// BBS vs 노배럭더블
// (bbs_vs_1bar_double 구조 복제 → 디테일은 별도 보정)
//
// 분기 4개 (Phase 1 non-decisive, baseProbability 75/25 비율):
//   center_def_wins      : 센터 정찰 + SCV 컨트롤로 BBS 마린 줄임 → 수비 우세 (basePr 0.375)
//   center_atk_wins      : 센터 정찰이지만 BBS 컨트롤 우위 → SCV 괴멸, BBS 압박 (basePr 0.125)
//   base_bunker_success  : 본진 정찰 → 1vs3 교전 + 벙커 성공 → BBS 큰 피해 (basePr 0.375)
//   base_defended        : 본진 정찰이지만 SCV 컨트롤로 막음 → 수비 우세 (basePr 0.125)
// ----------------------------------------------------------
const _tvtBbsVsNobarDouble = ScenarioScript(
  id: 'tvt_bbs_vs_nobar_double',
  matchup: 'TvT',
  homeBuildIds: ['tvt_bbs'],
  awayBuildIds: ['tvt_nobar_double'],
  description: 'BBS vs 노배럭더블',
  phases: [
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      recoveryArmyPerLine: 0,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 SCV 한 기를 센터로 보냅니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '{home} 선수 초반부터 SCV를 센터로 올립니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 센터에 첫 배럭을 올립니다. 빠른 배럭입니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -150,
          altText: '{home} 선수 센터 첫 배럭 건설. 공격적인 빌드입니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 앞마당에 커맨드센터를 먼저 올립니다. 굉장히 과감한 선택입니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -400,
          altText: '{away} 선수 배럭도 없이 커맨드센터부터 올리네요. 성공만 한다면 후반 물량이 기대가 됩니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 센터에 두 번째 배럭. 정확하게 상대 빌드를 노린 것 같은데요.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -150,
          altText: '{home} 선수 센터 배럭 두 개! 초반 공격에 모든 걸 겁니다.',
        ),
        ScriptEvent(
          text: '극명하게 빌드가 갈렸는데요, 뚫리느냐 막느냐 초반 컨트롤 싸움 볼만하겠습니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '보통 생더블이라고 하죠, 배럭없이 확장부터 하는 빌드를 노린 bbs! 과연 얼만큼 피해를 입힐 것인가!',
        ),
        ScriptEvent(
          text: '{home} 선수 마린 추가 생산 하며 상대방 위치를 찾기 위해 배럭 건설한 SCV가 정찰을 나섭니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 3,
          homeResource: -150,
          altText: '{home} 선수 마린을 모으며 상대방 위치를 찾기 위해 정찰을 진행합니다.',
        ),
      ],
    ),

    ScriptPhase(
      name: 'scout_and_engage',
      recoveryArmyPerLine: 0,
      branches: [
        ScriptBranch(
          id: 'center_def_wins',
          description: '센터 정찰 + SCV 컨트롤로 BBS 마린 줄임 → 수비 우세',
          baseProbability: 0.30,
          events: [
            ScriptEvent(
              text: '{away} 선수 정찰 SCV가 센터 쪽으로 향합니다. 배럭이 없기를 빌텐데요!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 센터배럭이 가장 무섭죠! SCV가 센터로 정찰을 갑니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 배럭을 올립니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -150,
              altText: '{away} 선수 배럭 건설. 마린이 나오려면 시간이 필요합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 SCV가 센터에서 배럭 두 기를 발견합니다! 본진 SCV 이끌고 수비해야죠!',
              owner: LogOwner.system,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 1,
              awayResource: -50,
              altText: '{away} 선수 센터 배럭 두 기 확인! 막으면 이긴다는 마인드로 다수의 SCV를 끌고 나옵니다',
            ),
            ScriptEvent(
              text: '벌써 마린 수가 차이가 납니다! {home} 선수는 3기, {away} 선수는 아직 0기!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수가 마린이 3기 모이는 사이 {away} 선수는 배럭 건설 중!',
            ),
            ScriptEvent(
              text: '{away} 선수 SCV로 BBS 마린을 감싸 잡아냅니다! 마린이 모이지 못하게 만들죠.',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -3,
              altText: '{away} 선수 SCV 컨트롤! {home} 선수의 마린이 모이질 못합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 SCV도 잃고 마린도 부족합니다. 이대로 후퇴하면 가망이 없는데요!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayResource: 0,
              homeResource: -150,
              awayArmy: -1,
              altText: '{home} 선수 마린이 다 잡히고 초반 전략이 막힙니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 앞마당 가동, 굉장한 컨트롤과 수비력입니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 6,
              awayResource: -75,
              altText: '{away} 선수 확장 성공, {home} 선수 확장 차이로 인한 병력 압박이 예상되는데요.',
            ),
            ScriptEvent(
              text: '{away} 선수 가스 건설 하며 팩토리 준비합니다. 사실상 BBS가 막힌 순간 승기를 잡았죠.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 6,
              awayResource: -75,
              altText: '{away} 선수 여유롭게 테크를 올리며 {home} 선수를 궁지로 몰아넣습니다.',
            ),
          ],
        ),

        ScriptBranch(
          id: 'center_atk_wins',
          description: '센터 정찰 했지만 BBS 컨트롤 우위 → SCV 괴멸, 마린 압박',
          baseProbability: 0.20,
          events: [
            ScriptEvent(
              text: '{away} 선수 정찰 SCV가 센터 쪽으로 향합니다. 확실하게 정찰하고 가려고 합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 센터배럭만 아니면 된다는 마음! SCV가 센터로 정찰을 갑니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 배럭을 올립니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -150,
              altText: '{away} 선수 배럭 건설. 마린 나올 때까지 버텨야 합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 SCV가 센터에서 배럭 두 기를 발견합니다! 본진 SCV 이끌고 수비해야죠!',
              owner: LogOwner.system,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 1,
              awayResource: -50,
              altText: '{away} 선수 센터 배럭 두 기 확인! 막으면 이긴다는 마인드로 다수의 SCV를 끌고 나옵니다',
            ),
            ScriptEvent(
              text: '벌써 마린 수가 차이가 납니다! {home} 선수는 3기, {away} 선수는 아직 0기!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수의 마린이 3기 모이는 사이 {away} 선수는 배럭 아직 건설 중입니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 SCV를 끌고 센터로 진출. {home} 선수의 마린을 모이기전에 끊어줄 심산이죠.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 SCV 부대를 끌고 나갑니다. 마린이 모이지 않게 해야합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 마린 컨트롤로 수비측 SCV가 마린을 감싸지 못하게 합니다. SCV만으로 수비하기는 쉽지 않죠!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: -300,
              awayArmy: -2,
              altText: '{home} 선수 마린 컨트롤이 대단합니다. 수비측 SCV 피해가 큽니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 마린이 계속 쌓입니다! 수비측 앞마당까지 압박이 들어옵니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 3,
              homeResource: -150,
              altText: '{home} 선수 마린 추가 생산! 수비측 앞마당에 벙커를 지으며 압박합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 본인의 앞마당에 벙커를 지으며 버텨보려 하지만 {home} 선수의 마린이 배럭을 점령했습니다.',
              owner: LogOwner.away,
              homeResource: -100,
              homeArmy: -2,
              awayArmy: -4,
              awayResource: -300,
              altText: '{away} 선수 앞마당 벙커로 수비 시도하지만 쉽지않습니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 추가 마린 투입! 상대방의 앞마당을 파괴합니다.',
              owner: LogOwner.home,
              awayResource: 0,
              homeArmy: 5,
              homeResource: -250,
              awayArmy: -3,
              altText: '{home} 선수 초반 승부수가 통했습니다! 본진까지 진격!',
            ),
          ],
        ),

        ScriptBranch(
          id: 'base_bunker_success',
          description: '본진 정찰 → 벙커 성공 + 마린 진입 → BBS 큰 피해',
          baseProbability: 0.38,
          events: [
            ScriptEvent(
              text: '{away} 선수 이상함을 느끼지 못하고 일반적인 정찰 루트를 선택합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 정찰 SCV로 상대 본진을 찾으려고 합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 앞마당에 심시티의 일환으로 배럭을 올립니다. 아직 마린은 없습니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -150,
              altText: '{away} 선수 배럭 건설. 마린 생산까지 시간이 필요합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 마린 3기로 {away} 선수의 앞마당을 덮칩니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 마린 숫자로 {away} 선수 압박하기 시작합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 앞마당 건설하던 SCV가 잡히고 맙니다. 배럭 없는 상태라 마린도 없습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -50,
              altText: '{away} 선수 SCV 손실. 마린이 아예 없는 상태라 절망적입니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 {away} 선수의 앞마당에 벙커 건설 시도!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -100,
              altText: '{home} 선수 벙커를 지으며 SCV 나오라고 압박합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 SCV 다 끌고 나와서 수비하려 합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} SCV 빨리 나와야죠!',
            ),
            ScriptEvent(
              text: '{home} 선수 벙커 완성, 마린 진입! 화력이 쏟아집니다!',
              owner: LogOwner.home,
              homeArmy: 3,
              homeResource: -150,
              awayResource: -200,
              awayArmy: -2,
              altText: '{home} 선수 벙커 마린 화력! 수비측 앞마당이 장악당합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 추가 마린 투입! 앞마당 커맨드까지 밀어버립니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeArmy: 6,
              homeResource: -300,
              awayResource: -400,
              altText: '{home} 선수 벙커링 성공! {away} 선수 앞마당 커맨드 파괴!',
            ),
          ],
        ),

        ScriptBranch(
          id: 'base_defended',
          description: '본진 정찰이지만 SCV 컨트롤로 벙커/마린 진입 막음 → 수비 우세',
          baseProbability: 0.12,
          events: [
            ScriptEvent(
              text: '{away} 선수 이상함을 느끼지 못하고 일반적인 정찰 루트를 선택합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 정찰 SCV로 상대 본진을 찾으려고 합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 앞마당에 배럭을 올립니다. 심시티를 위함이기도 하죠.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -150,
              altText: '{away} 선수 배럭 건설. 아직까진 상대방의 초반 빌드를 파악하지 못했죠.',
            ),
            ScriptEvent(
              text: '{away} 선수 SCV가 상대 본진을 원서치로 찾아냅니다. 배럭이 없는 걸 발견, SCV 다수를 수비적으로 배치합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -50,
              altText: '{away} 선수 원서치에 성공합니다. 배럭이 없음에 이상함을 느끼고 다수의 SCV를 수비대기 시킵니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 마린 3기와 SCV가 수비 진영 도착 직전입니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 마린과 SCV 상대방을 압박하기 위해 이동합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 마린이 없는 상태라 SCV 다수로만 시간을 법니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -1,
              altText: '{away} 선수 SCV 뭉치기로 막아봅니다! 마린은 아직 안 나옵니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 {away} 선수의 앞마당에 벙커 건설 시도!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -100,
              altText: '{home} 선수 벙커를 지으며 압박 진행합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 SCV 컨트롤! 벙커 짓는 SCV 잡고, 진입하려는 마린도 잡습니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              altText: '{away} 선수 SCV 컨트롤이 미쳤는데요, 벙커 진입을 막습니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 피해를 최소화하며 막아냅니다! 이렇게 막히면 자원차이가 크게 벌어집니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayResource: 0,
              awayArmy: 12,
              homeResource: -100,
              altText: '{away} 선수 수비력이 빛난 순간입니다! {home} 선수는 이후에 자원차이로 쏟아질 병력이 감당안될텐데요!',
            ),
          ],
        ),
      ],
    ),

    ScriptPhase(
      name: 'finisher',
      recoveryArmyPerLine: 0,
      branches: [
        ScriptBranch(
          id: 'finisher_home',
          description: 'BBS 측 마무리',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{home} 선수 초반 전략이 통했습니다! {away} 선수 마우스를 놓습니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 마무리! 경기 종료입니다!',
            ),
          ],
        ),
        ScriptBranch(
          id: 'finisher_away',
          description: '수비 측 마무리',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{away} 선수 수비력이 돋보이는 경기입니다! {home} 선수 키보드에서 손을 뗍니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 마무리! 경기 종료입니다!',
            ),
          ],
        ),
      ],
    ),
  ],
);
