part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// FD 러쉬 미러 (탱크 시즈 거리재기)
// ----------------------------------------------------------
const _tvtFdRushMirror = ScenarioScript(
  id: 'tvt_fd_rush_mirror',
  matchup: 'TvT',
  homeBuildIds: ['tvt_fd_rush'],
  awayBuildIds: ['tvt_fd_rush'],
  description: 'FD 러쉬 탱크 대결',
  phases: [
    // ── Phase 0: 오프닝 (lines 1-8) ── recovery 100/줄
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      recoveryArmyPerLine: 0,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 배럭 건설합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -150, // 배럭 150
          altText: '{home} 선수 배럭을 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 배럭 건설합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -150,
          altText: '{away} 선수도 배럭을 올립니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 배럭에 이어 리파이너리를 올립니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -100, // 리파이너리 100
          altText: '{home} 선수 가스를 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 리파이너리를 올립니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -100,
          altText: '{away} 선수도 가스를 올립니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 배럭이 완성됩니다. 마린 생산을 시작하며 팩토리도 올립니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -300, // 팩토리 300
          homeArmy: 4, // 배럭 완성분 마린 + 팩토리 건설
          altText: '{home} 선수 배럭 완성, 마린을 뽑으면서 팩토리를 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 배럭이 완성됩니다. 마린 생산과 팩토리 건설을 동시에 진행합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayResource: -300,
          awayArmy: 4,
          altText: '{away} 선수도 배럭 완성, 마린과 팩토리 동시 진행.',
        ),
        ScriptEvent(
          text: '{home} 선수 머신샵 부착. 벌처를 건너뛰고 바로 탱크를 노립니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -100, // 머신샵 100
          altText: '{home} 선수 머신샵을 올립니다, 빠른 탱크 체제입니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 머신샵 부착. 벌처 없이 바로 탱크입니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -100,
          altText: '{away} 선수도 머신샵, 탱크를 뽑을 준비입니다.',
        ),
        ScriptEvent(
          text: '마린을 모으면서 팩토리 머신샵까지, 컨트롤 싸움이 중요하겠습니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '벌처를 건너뛰고 바로 탱크, 마린과 함께 압박하겠다는 빌드입니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 탱크 생산과 시즈모드 연구를 동시에 시작합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 2, homeResource: -550, // 시즈탱크 250 + 시즈모드 300
          altText: '{home} 선수 탱크와 시즈모드를 동시에 돌립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 탱크와 시즈모드를 동시에 시작합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2, awayResource: -550,
          altText: '{away} 선수도 탱크 생산과 시즈모드 동시 진행.',
        ),
      ],
    ),
    // ── Phase 1: 마린+탱크 전진 (lines 12-20) ── recovery 150/줄
    ScriptPhase(
      name: 'marine_tank_push',
      recoveryArmyPerLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 시즈모드 완료! 마린 다수와 탱크를 앞세워 전진합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: 2, // 마린 추가 완성분
          altText: '{home} 선수 마린 물량에 탱크까지! 전진 시작!',
        ),
        ScriptEvent(
          text: '{away} 선수도 마린과 탱크로 전진합니다! 센터에서 마주칩니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: 2,
          altText: '{away} 선수도 마린과 탱크가 합류! 센터로 향합니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 뒤에서 앞마당 커맨드센터를 올립니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -400, // CC 400
          altText: '{home} 선수 압박하면서 앞마당 확장을 시작합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 앞마당 커맨드센터를 올립니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -400,
          altText: '{away} 선수도 전진하면서 뒤에서 확장.',
        ),
        ScriptEvent(
          text: '양측 마린과 탱크가 센터에서 마주칩니다! 컨트롤 싸움이 중요하겠습니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '마린 물량에 시즈탱크까지, 초반부터 치열한 교전입니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 고지를 먼저 잡으려 합니다, 시즈 거리가 중요합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '{home} 선수 고지 선점 시도.',
        ),
        ScriptEvent(
          text: '{away} 선수도 고지를 노립니다, 탱크 배치 싸움입니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '{away} 선수 고지 확보 시도, 먼저 잡는 쪽이 유리합니다.',
        ),
      ],
    ),
    // ── Phase 2: 압박 결과 분기 (lines 22-32) ── recovery 150/줄
    ScriptPhase(
      name: 'push_result',
      recoveryArmyPerLine: 1,
      branches: [
        // 분기 A: 비등 교전 → 탱크 생존, 각자 귀환
        ScriptBranch(
          id: 'push_even',
          description: '비등 교전, 마린 소모 후 탱크 살려 귀환',
          baseProbability: 1.5,
          events: [
            ScriptEvent(
              text: '센터에서 양측 병력이 맞붙습니다! 치열한 교환이 일어납니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '양쪽 병력이 센터에서 충돌합니다, 손실이 발생합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 마린이 집중 사격, 상대 마린을 처리하지만 손실도 있습니다.',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2, awayArmy: -2,
              altText: '{home} 선수 마린 교환, 피해가 양쪽에 발생합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수도 마린으로 맞대응, 비슷한 손실입니다.',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2, awayArmy: -2,
              altText: '{away} 선수 마린 집중 사격, 양쪽 피해가 엇비슷합니다.',
            ),
            ScriptEvent(
              text: '탱크는 양쪽 모두 살아남았습니다, 각자 귀환하며 재정비합니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.2,
              altText: '마린 소모전 이후 탱크는 생존, 대치 국면이 이어집니다.',
            ),
          ],
        ),
        // 분기 B: 홈 컨트롤 우위 → 어웨이 탱크 제거
        ScriptBranch(
          id: 'home_push_edge',
          description: '홈 컨트롤 우위, 어웨이 탱크 제거',
          baseProbability: 0.8,
          conditionStat: 'control',
          homeStatMustBeHigher: true,
          events: [
            ScriptEvent(
              text: '{home} 선수 마린 컨트롤이 예리합니다! 상대 마린을 효율적으로 처리합니다.',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2, homeArmy: -1,
              altText: '{home} 선수 마린 컨트롤 우위, 상대보다 효율적입니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 남은 마린으로 탱크 사거리를 잡아냅니다! {away} 선수 탱크가 위험합니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -3, homeArmy: -1,
              altText: '{home} 선수 마린을 이용해 탱크를 잡아냅니다!',
            ),
            ScriptEvent(
              text: '초반 교전에서 탱크 한 대를 잡아냈습니다, {home} 선수가 유리해졌습니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 컨트롤로 상대 탱크를 제거, 교전 우위를 가져갑니다.',
            ),
          ],
        ),
        // 분기 C: 어웨이 컨트롤 우위 → 홈 탱크 제거
        ScriptBranch(
          id: 'away_push_edge',
          description: '어웨이 컨트롤 우위, 홈 탱크 제거',
          baseProbability: 0.8,
          conditionStat: 'control',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수 마린 컨트롤이 한 수 위입니다! 상대 마린을 빠르게 처리합니다.',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2, awayArmy: -1,
              altText: '{away} 선수 컨트롤 우위, 마린 교환에서 앞섭니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 마린으로 탱크를 잡아냅니다! {home} 선수 탱크가 터집니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -3, awayArmy: -1,
              altText: '{away} 선수 탱크를 노려 잡아냅니다!',
            ),
            ScriptEvent(
              text: '탱크 한 대 차이! {away} 선수가 초반 교전을 가져갑니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 컨트롤로 {home} 선수 탱크를 제거, 전세가 기울었습니다.',
            ),
          ],
        ),
        // 분기 D: 홈 압도 → 어웨이 병력 괴멸 + 앞마당 취소
        ScriptBranch(
          id: 'home_push_dominates',
          description: '홈 압도, 어웨이 병력 괴멸 및 앞마당 취소',
          baseProbability: 0.5,
          conditionStat: 'control',
          homeStatMustBeHigher: true,
          events: [
            ScriptEvent(
              text: '{home} 선수 마린 컨트롤이 압도적입니다! 상대 병력이 무너지기 시작합니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -3, homeArmy: -1,
              altText: '{home} 선수 완벽한 마린 컨트롤! 상대가 버티질 못합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크까지 앞세워 밀어붙입니다! {away} 선수 병력이 괴멸합니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -4, homeArmy: -1,
              altText: '{home} 선수 탱크가 합류! {away} 선수 병력을 완전히 쓸어버립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 상대 앞마당까지 진격합니다! 앞마당 커맨드센터가 취소됩니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 초반 압도로 상대 앞마당을 파괴합니다! 경기가 끝났습니다!',
            ),
          ],
        ),
        // 분기 E: 어웨이 압도 → 홈 병력 괴멸 + 앞마당 취소
        ScriptBranch(
          id: 'away_push_dominates',
          description: '어웨이 압도, 홈 병력 괴멸 및 앞마당 취소',
          baseProbability: 0.5,
          conditionStat: 'control',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수 마린 컨트롤이 압도적입니다! {home} 선수 병력이 순식간에 무너집니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -3, awayArmy: -1,
              altText: '{away} 선수 완벽한 컨트롤! {home} 선수 마린이 버티질 못합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크를 앞세워 계속 밀어붙입니다! {home} 선수 병력이 괴멸합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4, awayArmy: -1,
              altText: '{away} 선수 탱크까지 합류! {home} 선수 병력을 완전히 쓸어버립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 {home} 선수 앞마당까지 진격합니다! 앞마당 커맨드센터가 취소됩니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 초반 압도로 {home} 선수 앞마당을 파괴합니다! 경기가 끝났습니다!',
            ),
          ],
        ),
      ],
    ),
    // ── Phase 3: 탱크 푸시 체크 (lines 30-38) ── recovery 150/줄
    ScriptPhase(
      name: 'tank_push_check',
      recoveryArmyPerLine: 1,
      branches: [
        // 분기 A: 탱크 비등 → 게임 계속
        ScriptBranch(
          id: 'tank_even',
          baseProbability: 1.5,
          events: [
            ScriptEvent(
              text: '양측 탱크 물량이 비등합니다, 시즈 라인 교착이 이어집니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '양쪽 탱크 수가 비슷합니다, 쉽게 밀어붙이기 어렵습니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크를 추가 생산합니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -250,
              altText: '{home} 선수 탱크 한 대가 더 합류합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수도 탱크를 추가 생산합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -250,
              altText: '{away} 선수도 탱크 보충.',
            ),
            ScriptEvent(
              text: '물량전으로 가고 있습니다, 확장이 필요한 시점입니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '탱크 수 싸움이 치열합니다, 자원 확보가 관건입니다.',
            ),
          ],
        ),
        // 분기 B: 홈 탱크 푸시 → decisive
        ScriptBranch(
          id: 'home_tank_push',
          baseProbability: 0.5,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{home} 선수 시즈 모드를 풀고 전진합니다! 밀어붙입니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -250,
              altText: '{home} 선수 탱크 전진! 상대 라인을 밀어붙입니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크가 유리한 각도에서 시즈 포격! 상대 탱크를 제압합니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -4, homeArmy: -2,
              altText: '{home} 선수 시즈 집중 포격! 상대 라인이 무너집니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크 푸시로 시즈 라인을 돌파합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 탱크 운용이 한 수 위였습니다!',
            ),
          ],
        ),
        // 분기 C: 어웨이 탱크 푸시 → decisive
        ScriptBranch(
          id: 'away_tank_push',
          baseProbability: 0.5,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{away} 선수 시즈 모드를 풀고 전진합니다! 밀어붙입니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -250,
              altText: '{away} 선수 탱크 전진! 상대 라인으로 밀고 갑니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크가 유리한 각도에서 포격! 상대 탱크를 날립니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4, awayArmy: -2,
              altText: '{away} 선수 시즈 집중 포격! 상대 라인이 붕괴합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크 푸시로 시즈 라인을 돌파합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 압도적인 탱크 운용으로 제압합니다!',
            ),
          ],
        ),
      ],
    ),
    // ── Phase 4: 확장 타이밍 분기 (lines 36-46) ── recovery 200/줄
    ScriptPhase(
      name: 'expansion_timing',
      recoveryArmyPerLine: 2,
      branches: [
        // 분기 A: 동시 확장 (가장 빈번)
        ScriptBranch(
          id: 'both_expand',
          baseProbability: 1.5,
          events: [
            ScriptEvent(
              text: '{home} 선수 앞마당에 커맨드센터를 건설합니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -400, // CC 400
              homeExpansion: true,
              altText: '{home} 선수 앞마당 확장.',
            ),
            ScriptEvent(
              text: '{away} 선수도 앞마당 커맨드센터를 건설합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -400,
              awayExpansion: true,
              altText: '{away} 선수도 앞마당 확장.',
            ),
            ScriptEvent(
              text: '{home} 선수 두 번째 팩토리를 건설합니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -300, // 팩토리 300
              altText: '{home} 선수 팩토리 두 개 체제로 전환합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수도 팩토리를 추가합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -300,
              altText: '{away} 선수도 팩토리 두 개로 전환.',
            ),
            ScriptEvent(
              text: '양측 확장과 팩토리 두 개 체제, 무난한 중후반 싸움으로 진행되겠습니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '양쪽 다 확장을 올렸습니다, 자원 싸움이 본격화됩니다.',
            ),
          ],
        ),
        // 분기 B: 홈 빠른 확장
        ScriptBranch(
          id: 'home_fast_expand',
          baseProbability: 0.7,
          events: [
            ScriptEvent(
              text: '{home} 선수 먼저 앞마당 커맨드센터를 건설합니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -400,
              homeExpansion: true,
              altText: '{home} 선수 선 확장, 자원 우위를 노립니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크를 추가 생산, 상대 확장을 노립니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -250,
              altText: '{away} 선수 확장 대신 탱크 물량을 올립니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 시즈 포격으로 확장을 압박합니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              altText: '{away} 선수 확장 타이밍을 노려 시즈 포격!',
            ),
            ScriptEvent(
              text: '{home} 선수 버텨냅니다, 확장이 완성되면 자원 우위입니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 수비 성공, 확장 자원이 들어오기 시작합니다.',
            ),
          ],
        ),
        // 분기 C: 어웨이 빠른 확장
        ScriptBranch(
          id: 'away_fast_expand',
          baseProbability: 0.7,
          events: [
            ScriptEvent(
              text: '{away} 선수 먼저 앞마당 커맨드센터를 건설합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -400,
              awayExpansion: true,
              altText: '{away} 선수 선 확장, 자원 우위를 가져가려 합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크를 추가 생산, 상대 확장을 압박합니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -250,
              altText: '{home} 선수 확장 대신 탱크 물량.',
            ),
            ScriptEvent(
              text: '{home} 선수 시즈 포격으로 확장을 공격합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              altText: '{home} 선수 확장 타이밍에 시즈 포격!',
            ),
            ScriptEvent(
              text: '{away} 선수 버텨냅니다, 확장이 돌아가면 유리합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 수비 성공, 자원이 들어오기 시작합니다.',
            ),
          ],
        ),
        // 분기 D: 홈 확장 스킵 공격 → decisive
        ScriptBranch(
          id: 'home_skip_expand_attack',
          baseProbability: 0.4,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{home} 선수 확장을 포기하고 탱크를 더블 생산합니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 4, homeResource: -500, // 탱크 2기
              altText: '{home} 선수 확장 없이 올인, 탱크 물량을 올립니다.',
            ),
            ScriptEvent(
              text: '{away} 선수는 확장을 시도합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -400,
              awayExpansion: true,
              altText: '{away} 선수 앞마당 확장, 그런데 상대가 밀고 옵니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 탱크 물량으로 밀어붙입니다! 확장 타이밍을 잡았습니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -4, homeArmy: -2,
              altText: '{home} 선수 올인 시즈 포격! 상대 확장이 위험합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 확장 포기 올인으로 밀어붙여 승리합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 확장 없이 탱크 올인으로 제압합니다!',
            ),
          ],
        ),
        // 분기 E: 어웨이 확장 스킵 공격 → decisive
        ScriptBranch(
          id: 'away_skip_expand_attack',
          baseProbability: 0.4,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{away} 선수 확장을 포기하고 탱크를 더블 생산합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4, awayResource: -500,
              altText: '{away} 선수 확장 없이 올인, 탱크 물량.',
            ),
            ScriptEvent(
              text: '{home} 선수는 확장을 시도합니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -400,
              homeExpansion: true,
              altText: '{home} 선수 앞마당 확장, 상대가 밀고 옵니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크 물량으로 밀어붙입니다! 확장 타이밍을 잡았습니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4, awayArmy: -2,
              altText: '{away} 선수 올인 시즈 포격! 상대 확장이 위험합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 확장 포기 올인으로 밀어붙여 승리합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 확장 없이 탱크 올인으로 제압합니다!',
            ),
          ],
        ),
      ],
    ),
    // ── Phase 5: 스타포트 + 드랍 준비 (lines 48-54) ── recovery 200/줄
    ScriptPhase(
      name: 'starport_prep',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 스타포트를 건설합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -250, // 스타포트 250
          altText: '{home} 선수 스타포트를 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 스타포트를 건설합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -250,
          altText: '{away} 선수도 스타포트.',
        ),
        ScriptEvent(
          text: '{home} 선수 탱크 더블 생산, 물량을 올립니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 4, homeResource: -500, // 탱크 2기
          altText: '{home} 선수 탱크 2기 추가 생산.',
        ),
        ScriptEvent(
          text: '{away} 선수도 탱크 더블 생산.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 4, awayResource: -500,
          altText: '{away} 선수도 탱크 2기 추가.',
        ),
        ScriptEvent(
          text: '양측 스타포트 완성, 드랍과 우회가 승부를 가를 수 있습니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.3,
          altText: '스타포트가 올라왔습니다, 드랍 운영이 중요해집니다.',
        ),
        // ── 맵 특성 이벤트 ──
        ScriptEvent(
          text: '{home} 선수 근거리 맵이라 탱크가 바로 사거리에 들어옵니다! 시즈 포격!',
          owner: LogOwner.home,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -2,
          requiresMapTag: 'rushShort',
          skipChance: 0.5,
        ),
        ScriptEvent(
          text: '{away} 선수도 근거리 맵 이점을 살려 시즈 포격!',
          owner: LogOwner.away,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -2,
          requiresMapTag: 'rushShort',
          skipChance: 0.5,
        ),
        ScriptEvent(
          text: '{home} 선수 고지대를 점령하고 시즈 포격! 아래에서는 사거리가 안 닿습니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -2,
          requiresMapTag: 'terrainHigh',
          skipChance: 0.5,
        ),
        ScriptEvent(
          text: '{away} 선수도 반대편 고지대에 탱크를 올립니다, 지형 싸움입니다.',
          owner: LogOwner.away,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -2,
          requiresMapTag: 'terrainHigh',
          skipChance: 0.5,
        ),
        ScriptEvent(
          text: '원거리 맵이라 확장이 안전합니다, 양측 자원이 풍부해집니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 200, awayResource: 200,
          requiresMapTag: 'rushLong',
        ),
      ],
    ),
    // ── Phase 6: 드랍 운영 다양성 분기 (lines 56+) ── recovery 200/줄
    ScriptPhase(
      name: 'drop_operations',
      recoveryArmyPerLine: 2,
      branches: [
        // 분기 A: 게릴라 드랍 (확장 견제 후 회수)
        ScriptBranch(
          id: 'guerrilla',
          baseProbability: 1.2,
          events: [
            ScriptEvent(
              text: '{home} 선수 드랍십에 탱크를 싣고 상대 확장으로 향합니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -200, // 드랍십 200
              altText: '{home} 선수 드랍십 출격, 상대 확장을 노립니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 확장 기지에 탱크 투하! SCV를 잡고 회수합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -200, // 일꾼 피해
              altText: '{home} 선수 드랍 견제! 일꾼 피해를 주고 빠져나갑니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 수비 병력이 달려왔지만 드랍십은 이미 빠져나갔습니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -150, // 수비 병력 생산
              altText: '{away} 선수 대응이 늦었습니다, 피해가 남았습니다.',
            ),
            ScriptEvent(
              text: '게릴라 드랍! 자잘한 피해가 쌓이고 있습니다.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
              altText: '드랍으로 시선을 끈 사이 정면 거리재기가 이어집니다.',
            ),
          ],
        ),
        // 분기 B: 마무리 드랍 → decisive
        ScriptBranch(
          id: 'finishing',
          baseProbability: 0.7,
          conditionStat: 'strategy',
          events: [
            ScriptEvent(
              text: '{home} 선수 드랍십 두 대를 출격시킵니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -400, // 드랍십 2기
              altText: '{home} 선수 드랍 두 방향으로 나갑니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 본진과 확장에 동시 투하! 정면 탱크도 전진합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -4, awayResource: -300,
              altText: '{home} 선수 양면 공격! 드랍과 정면 동시 압박!',
            ),
            ScriptEvent(
              text: '{away} 선수 수비가 분산됩니다! 세 방향 공격입니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              altText: '{away} 선수 병력을 나눌 수밖에 없습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 드랍과 정면 동시 공격으로 제압합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 양면작전 성공으로 승리합니다!',
            ),
          ],
        ),
        // 분기 C: 정면 시즈 교전 (드랍 없이)
        ScriptBranch(
          id: 'frontal',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '양측 시즈 라인이 정면에서 맞붙습니다! 포격전입니다!',
              owner: LogOwner.system,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2, awayArmy: -2,
              altText: '정면 시즈전! 탱크끼리 포격을 주고받습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 벌처로 마인을 매설, 상대 탱크 이동 경로를 차단합니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -75,
              altText: '{home} 선수 마인 매설, 탱크 전진 경로를 막습니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크가 마인을 밟습니다! 탱크 한 대가 터집니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              altText: '{away} 선수 탱크가 마인에 피격! 한 대를 잃습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 시즈 포격! 마인 피해와 겹쳐 상대 라인이 약해집니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2, homeArmy: -2,
              altText: '{home} 선수 마인과 시즈 연계 포격! 상대 전선이 밀립니다!',
            ),
          ],
        ),
        // 분기 D: 역전 드랍 (불리한 쪽 승부수)
        ScriptBranch(
          id: 'desperate',
          baseProbability: 0.6,
          events: [
            ScriptEvent(
              text: '{away} 선수 정면에서 밀리고 있습니다! 승부수를 던집니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
              altText: '{away} 선수 전선이 불리합니다! 드랍으로 승부합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 드랍십 두 대에 탱크를 싣고 상대 본진으로!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -400, // 드랍십 2기
              altText: '{away} 선수 올인 드랍! 본진에 탱크를 투하합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 본진에 탱크 투하! 시즈 모드! 팩토리를 노립니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -400, homeArmy: -2, // 생산시설+병력 피해
              altText: '{away} 선수 본진 시즈! 팩토리와 탱크에 피해를 줍니다!',
            ),
            ScriptEvent(
              text: '역전 드랍! 피해가 크면 경기가 뒤집힐 수 있습니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '본진 드랍 피해가 상당합니다! 경기가 요동칩니다!',
            ),
          ],
        ),
      ],
    ),
    // ── Phase 7: 최종 결전 (lines 64+) ── recovery 200/줄
    ScriptPhase(
      name: 'decisive_outcome',
      recoveryArmyPerLine: 2,
      branches: [
        ScriptBranch(
          id: 'home_wins_decisive',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{home} 선수 드랍십에 탱크를 싣고 뒤쪽 고지로!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: -300, awayArmy: -2, // 후방 피해
              altText: '{home} 선수 탱크 드랍! 상대 후방 고지에 시즈!',
            ),
            ScriptEvent(
              text: '{home} 선수 양면 시즈 포격! 정면과 후방 동시 공격!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -4, homeArmy: -2,
              altText: '{home} 선수 정면과 드랍 양면 공격! 상대가 분산됩니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 시즈 대결에서 위치 선점과 드랍으로 승리합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 탱크 운용이 한 수 위였습니다!',
            ),
          ],
        ),
        ScriptBranch(
          id: 'away_wins_decisive',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{away} 선수 벌처로 마인을 매설, 상대 이동 경로를 차단합니다.',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              altText: '{away} 선수 마인 매복! 상대 탱크가 밟습니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크가 유리한 위치에서 포격합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4, awayArmy: -2,
              altText: '{away} 선수 시즈 집중 포격! 상대 라인이 무너집니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 탱크 배치와 마인 운용으로 대결을 제압합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 시즈 거리재기에서 승리합니다!',
            ),
          ],
        ),
      ],
    ),
  ],
);
