part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 973 히드라 vs 아콘 질럿: 스톰 전에 히드라로 끝내야 한다
// ----------------------------------------------------------
const _zvp973HydraVsArchon = ScenarioScript(
  id: 'zvp_973_hydra_vs_archon',
  matchup: 'ZvP',
  homeBuildIds: ['zvp_trans_973_hydra', 'zvp_973_hydra', 'zvp_9pool'],
  awayBuildIds: ['pvz_trans_archon', 'pvz_corsair_reaver'],
  description: '973 히드라 vs 아콘 질럿 — 스톰이 나오면 히드라가 녹는다',
  phases: [
    // Phase 0: opening (lines 1-11)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 9드론에 스포닝풀을 올립니다! 빠른 히드라를 노리는군요!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -15,
          altText: '{home} 선수, 빠른 스포닝풀! 히드라 타이밍을 노립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 게이트웨이와 사이버네틱스 코어를 올립니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -20,
        ),
        ScriptEvent(
          text: '{home} 선수 앞마당을 확보하고 히드라덴을 건설합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -25,
        ),
        ScriptEvent(
          text: '{away} 선수 아둔을 건설합니다! 템플러 테크를 향해 가는군요.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -15,
          altText: '{away} 선수, 아둔이 올라갑니다! 하이템플러를 준비합니다.',
        ),
        ScriptEvent(
          text: '히드라 타이밍이 아콘 완성보다 빨라야 합니다! 시간 싸움입니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 1: 테크 경쟁 (lines 12-21)
    ScriptPhase(
      name: 'mid_game',
      recoveryArmyPerLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 히드라리스크를 대량 생산합니다! 빠른 타이밍!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 5,
          homeResource: -20,
        ),
        ScriptEvent(
          text: '{away} 선수 템플러 아카이브를 건설합니다! 스톰 연구 시작!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -20,
          altText: '{away} 선수, 템플러 아카이브가 올라갑니다! 스톰이 곧 완성!',
        ),
        ScriptEvent(
          text: '{home} 선수 히드라 부대를 모아서 프로토스로 출격합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: 2,
          skipChance: 0.2,
        ),
        ScriptEvent(
          text: '{away} 선수 질럿과 드라군으로 수비를 준비합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 3,
          awayResource: -10,
          altText: '{away} 선수, 질럿과 드라군이 앞마당을 지키고 있습니다.',
        ),
        ScriptEvent(
          text: '스톰이 완성되기 전에 히드라가 도착해야 합니다! 타이밍 경쟁!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 2: 히드라 어택 (lines 22-29)
    ScriptPhase(
      name: 'late_setup',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 히드라 부대가 프로토스 앞마당에 도착합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: 2,
          altText: '{home} 선수, 히드라 대군이 프로토스 앞에 도착했습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 하이템플러가 거의 완성됩니다! 조금만 더 버텨야 해요!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2,
          awayResource: -15,
        ),
        ScriptEvent(
          text: '{home} 선수 저글링을 측면으로 보내 견제합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 1,
          homeResource: -10,
          skipChance: 0.3,
        ),
        ScriptEvent(
          text: '스톰이 먼저냐 히드라가 먼저냐! 이 경기의 분수령!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 3: 결전 (lines 30+)
    ScriptPhase(
      name: 'decisive_battle',
      branches: [
        ScriptBranch(
          id: 'home_wins',
          baseProbability: 1.0,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{home} 선수 히드라가 스톰 완성 전에 돌파합니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 4,
              awayArmy: -3,
              altText: '{home} 선수, 히드라 타이밍 성공! 스톰보다 빨랐습니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 질럿만으로는 히드라 물량을 막을 수 없습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -3,
              awayResource: -15,
            ),
            ScriptEvent(
              text: '{home} 선수 넥서스를 공격합니다! 프로토스가 무너지고 있어요!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              homeArmy: 2,
              awayResource: -25,
            ),
            ScriptEvent(
              text: '스톰 전에 끝냈습니다! 히드라 타이밍의 승리!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        ScriptBranch(
          id: 'away_wins',
          baseProbability: 1.0,
          conditionStat: 'strategy',
          events: [
            ScriptEvent(
              text: '{away} 선수 사이오닉 스톰! 히드라 무리가 녹아내립니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 2,
              homeArmy: -5,
              altText: '{away} 선수, 스톰이 터집니다! 히드라가 한 방에 전멸!',
            ),
            ScriptEvent(
              text: '{away} 선수 아콘과 질럿이 남은 히드라를 정리합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 3,
              homeArmy: -2,
            ),
            ScriptEvent(
              text: '{home} 선수 히드라가 전멸했습니다! 재생산할 여력이 없어요!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: -2,
              homeResource: -20,
            ),
            ScriptEvent(
              text: '스톰의 위력! 히드라 뭉치가 한 방에 사라졌습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
