part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 하이브 디파일러 vs 드라군 푸시: 다크 스웜으로 드라군 무력화
// ----------------------------------------------------------
const _zvpHiveDefilerVsDragoonPush = ScenarioScript(
  id: 'zvp_hive_defiler_vs_dragoon_push',
  matchup: 'ZvP',
  homeBuildIds: ['zvp_trans_hive_defiler', 'zvp_scourge_defiler', 'zvp_3hatch_nopool'],
  awayBuildIds: ['pvz_trans_dragoon_push', 'pvz_2gate_zealot'],
  description: '하이브 디파일러 vs 드라군 푸시 — 푸시를 버티면 다크 스웜이 답이다',
  phases: [
    // Phase 0: opening (lines 1-11)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 앞마당 해처리를 올리며 드론을 늘립니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -30,
          altText: '{home}, 해처리부터 올리는 안정적인 오프닝입니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 게이트웨이에서 질럿을 뽑고 사이버네틱스 코어를 올립니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2,
          awayResource: -15,
        ),
        ScriptEvent(
          text: '{home} 선수 스포닝풀 완성! 저글링을 소량 생산합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 2,
          homeResource: -10,
        ),
        ScriptEvent(
          text: '{away} 선수 드라군 생산을 시작합니다! 푸시를 준비하는 모습이네요.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2,
          awayResource: -10,
          altText: '{away}, 드라군이 나오기 시작합니다!',
        ),
        ScriptEvent(
          text: '프로토스가 드라군 물량을 모으고 있습니다. 중반 푸시가 예상되는군요.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 1: 드라군 푸시 (lines 12-21)
    ScriptPhase(
      name: 'mid_game',
      recoveryArmyPerLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{away} 선수 드라군 6기를 모아서 전진합니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 4,
          awayResource: -15,
          altText: '{away}, 드라군 부대가 저그 앞마당을 향해 이동합니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 히드라리스크를 생산하며 수비를 준비합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 3,
          homeResource: -15,
        ),
        ScriptEvent(
          text: '{away} 선수 드라군이 저그 앞마당을 공격합니다!',
          owner: LogOwner.away,
          homeResource: 0,
          awayResource: 0,
          awayArmy: 1,
          homeArmy: -1,
          skipChance: 0.2,
        ),
        ScriptEvent(
          text: '{home} 선수 성큰과 히드라리스크로 라인을 잡습니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 2,
          homeResource: -10,
          altText: '{home}, 성큰 화력이 드라군을 잡아주고 있습니다!',
        ),
        ScriptEvent(
          text: '드라군 푸시를 막아내느냐가 이 경기의 분수령입니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 2: 하이브 전환 (lines 22-29)
    ScriptPhase(
      name: 'late_setup',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 레어를 올리며 하이브 테크를 서두릅니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -20,
          altText: '{home}, 레어가 완성되면 하이브로 바로 갈 수 있습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 추가 게이트웨이를 올리며 드라군을 보충합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2,
          awayResource: -15,
          skipChance: 0.3,
        ),
        ScriptEvent(
          text: '{home} 선수 하이브를 건설합니다! 디파일러를 향한 테크 트리!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -25,
        ),
        ScriptEvent(
          text: '디파일러의 다크 스웜이 나오면 드라군은 사격이 불가능합니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 3: 결전 (lines 30+)
    ScriptPhase(
      name: 'decisive_battle',
      branches: [
        ScriptBranch(
          id: 'home_wins',
          baseProbability: 2.0,
          conditionStat: 'strategy',
          events: [
            ScriptEvent(
              text: '{home} 선수 디파일러가 다크 스웜을 깔아줍니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 4,
              awayArmy: -2,
              altText: '{home}, 다크 스웜! 드라군의 사격이 완전히 차단됩니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 드라군이 다크 스웜 안에서 무력화됩니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -4,
              awayResource: -15,
            ),
            ScriptEvent(
              text: '{home} 선수 울트라리스크가 드라군을 짓밟습니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 3,
              awayArmy: -3,
            ),
            ScriptEvent(
              text: '다크 스웜으로 드라군을 완벽 차단! 저그의 승리입니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        ScriptBranch(
          id: 'away_wins',
          baseProbability: 1.0,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{away} 선수 드라군 물량이 저그 수비를 돌파합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 4,
              homeArmy: -3,
              altText: '{away}, 드라군의 집중 사격! 성큰이 무너지고 있습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 하이브가 완성되기 전에 앞마당이 밀렸습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: -2,
              homeResource: -25,
            ),
            ScriptEvent(
              text: '{away} 선수 드라군이 본진까지 진입합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 2,
              homeArmy: -2,
            ),
            ScriptEvent(
              text: '드라군 푸시 성공! 하이브 전에 끝냈습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
