part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// ZvP: 뮤탈 히드라 vs 아콘 + 질럿
// ----------------------------------------------------------
const _zvpMutalHydraVsArchon = ScenarioScript(
  id: 'zvp_mutal_hydra_vs_archon',
  matchup: 'ZvP',
  homeBuildIds: ['zvp_trans_mutal_hydra', 'zvp_2hatch_mutal', 'zvp_9overpool'],
  awayBuildIds: ['pvz_trans_archon', 'pvz_corsair_reaver'],
  description: '뮤탈 견제 + 히드라 vs 하이 템플러 아콘 합체',
  phases: [
    // Phase 0: 오프닝 (lines 1-11)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 해처리에서 드론을 뽑습니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -5,
        ),
        ScriptEvent(
          text: '{away} 선수 파일런 건설 후 게이트웨이를 올립니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -20,
        ),
        ScriptEvent(
          text: '{home} 선수 앞마당 해처리를 건설합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -30,
          altText: '{home} 선수, 앞마당 해처리! 자원을 확보합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 사이버네틱스 코어에서 아둔을 올립니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -20,
          altText: '{away} 선수, 아둔! 템플러 테크를 향합니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 스포닝풀과 가스를 넣으면서 레어를 향합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -25,
        ),
        ScriptEvent(
          text: '{away} 선수 아둔에서 템플러 아카이브 건설! 하이 템플러를 준비합니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -25,
          altText: '{away} 선수, 템플러 아카이브! 아콘 합체를 노립니다!',
        ),
      ],
    ),
    // Phase 1: 뮤탈 견제 + 아콘 준비 (lines 12-21)
    ScriptPhase(
      name: 'mid_game',
      recoveryArmyPerLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 스파이어 완성! 뮤탈리스크를 생산합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 4, homeResource: -25,
          altText: '{home} 선수, 뮤탈리스크! 프로브를 견제합니다!',
        ),
        ScriptEvent(
          text: '{home} 선수, 뮤탈이 프로브를 물어뜯습니다! 일꾼이 줄어듭니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -15,          altText: '{home} 선수 뮤탈 견제! 프로브 피해가 큽니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 하이 템플러 2기 생산! 사이오닉 스톰 연구 중!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 3, awayResource: -25,          altText: '{away} 선수, 하이 템플러! 스톰 연구가 진행됩니다!',
        ),
        ScriptEvent(
          text: '{away} 선수, 하이 템플러가 아콘으로 합체합니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: 3,
          altText: '{away} 선수 아콘 합체! 범위 공격이 위협적!',
        ),
        ScriptEvent(
          text: '아콘의 범위 공격은 뮤탈에게도 히드라에게도 위협적입니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.2,
        ),
      ],
    ),
    // Phase 2: 히드라 합류 (lines 22-29)
    ScriptPhase(
      name: 'late_setup',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 히드라덴 건설! 히드라를 함께 운용합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 4, homeResource: -20,
          altText: '{home} 선수, 히드라덴! 뮤탈과 히드라 조합!',
        ),
        ScriptEvent(
          text: '{home} 선수 뮤탈로 아콘을 유인합니다! 히드라가 집중 사격!',
          owner: LogOwner.home,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -2,          altText: '{home} 선수, 뮤탈 유인 전술! 히드라가 아콘을 집중합니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 아콘과 질럿으로 방어진을 구축합니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 3, awayResource: -15,
          altText: '{away} 선수, 아콘 앞에 질럿 벽! 수비 태세!',
        ),
        ScriptEvent(
          text: '뮤탈의 기동력으로 아콘을 상대할 수 있을까요?',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.3,
        ),
      ],
    ),
    // Phase 3: 결전 (lines 30+)
    ScriptPhase(
      name: 'decisive_battle',
      branches: [
        ScriptBranch(
          id: 'home_wins',
          baseProbability: 1.5,
          conditionStat: 'harass',
          events: [
            ScriptEvent(
              text: '{home} 선수 뮤탈이 아콘을 우회해 프로브를 견제합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -15,              altText: '{home} 선수, 뮤탈 우회! 프로브를 물어뜯습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수, 히드라가 아콘을 집중 사격합니다! 물량으로 밀어붙입니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -4, homeArmy: -2,            ),
            ScriptEvent(
              text: '{away} 선수 아콘이 무너지면서 방어선이 붕괴합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -3,
            ),
            ScriptEvent(
              text: '뮤탈 견제와 히드라 물량! 양면 공격에 아콘이 무너집니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        ScriptBranch(
          id: 'away_wins',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{away} 선수 스톰이 뮤탈 편대에 떨어집니다! 뮤탈이 녹습니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4,              altText: '{away} 선수, 스톰 투하! 뮤탈이 전멸합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수, 아콘이 히드라를 범위 공격으로 쓸어버립니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4,              altText: '{away} 선수 아콘 화력! 히드라가 녹아내립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 뮤탈과 히드라 모두 전멸합니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
            ),
            ScriptEvent(
              text: '스톰과 아콘! 뮤탈 히드라의 천적입니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
