part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 야바위 vs 2스타 커세어: 지상 기만 vs 공중 장악
// ----------------------------------------------------------
const _zvpYabarwiVs2starCorsair = ScenarioScript(
  id: 'zvp_yabarwi_vs_2star_corsair',
  matchup: 'ZvP',
  homeBuildIds: ['zvp_trans_yabarwi', 'zvp_yabarwi'],
  awayBuildIds: ['pvz_2star_corsair'],
  description: '저글링+히드라+럴커 기만 전술 vs 더블 스타게이트 커세어 — 지상 vs 공중',
  phases: [
    // Phase 0: opening (lines 1-11)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 앞마당 해처리를 올리며 자원 확보에 나섭니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: 10,
          altText: '{home}, 앞마당 해처리 건설! 드론 풀가동!',
        ),
        ScriptEvent(
          text: '{away} 선수 스타게이트 2개를 올립니다! 커세어 대량 생산 체제!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -20,
          altText: '{away}, 더블 스타게이트! 공중 장악을 노립니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 히드라덴 건설을 시작합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -10,
        ),
        ScriptEvent(
          text: '{away} 선수 커세어 첫 기가 출격합니다! 오버로드 사냥!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 3,
          awayResource: -10,
        ),
        ScriptEvent(
          text: '커세어가 하늘을 장악하려 합니다! 저그의 지상 전술이 통할까요!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 1: 커세어 vs 지상 병력 (lines 12-21)
    ScriptPhase(
      name: 'mid_game',
      recoveryArmyPerLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{away} 선수 커세어가 오버로드를 잡습니다! 정찰력이 줄어듭니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -10,
          altText: '{away}, 오버로드 격추! 저그가 앞을 볼 수 없습니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 히드라리스크를 생산합니다! 대공 방어 준비!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 4,
          homeResource: -15,
        ),
        ScriptEvent(
          text: '{home} 선수 저글링을 프로토스 센터 쪽으로 보냅니다. 가짜 공격!',
          owner: LogOwner.home,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: 2,
          altText: '{home}, 저글링 기습! 하지만 이것은 페이크일 수 있습니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 레어 업그레이드 후 럴커를 준비합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -10,
          skipChance: 0.25,
        ),
        ScriptEvent(
          text: '저그가 지상으로 승부를 걸고 있습니다! 커세어가 막을 수 있을까!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 2: 럴커 전환 + 기만전 (lines 22-29)
    ScriptPhase(
      name: 'late_setup',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 럴커가 완성됩니다! 여러 위치에 분산 배치합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 5,
          homeResource: -10,
          altText: '{home}, 럴커 다수 배치! 어디에 럴커가 있는지 알 수 없습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 커세어와 드라군 편대를 구성합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 3,
          awayResource: -10,
        ),
        ScriptEvent(
          text: '{home} 선수 저글링을 양쪽에서 동시에 보냅니다! 어디가 본공격인가!',
          owner: LogOwner.home,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: 3,
        ),
        ScriptEvent(
          text: '야바위 전술이 펼쳐집니다! 진짜와 가짜를 구분할 수 있을까!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 3: 결전 (lines 30+)
    ScriptPhase(
      name: 'decisive_battle',
      branches: [
        ScriptBranch(
          id: 'home_wins',
          conditionStat: 'strategy',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{home} 선수 럴커가 프로토스 진영을 관통합니다! 지상 병력이 녹아요!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 4,
              awayArmy: -5,
              altText: '{home}, 럴커 돌파! 사이버네틱스 코어의 드라군이 럴커를 잡지 못합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 저글링이 뒤에서 프로브를 잡아냅니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -20,
            ),
            ScriptEvent(
              text: '{away} 선수 커세어는 있지만 지상을 막을 수 없습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -3,
              awayResource: -10,
            ),
            ScriptEvent(
              text: '지상 기만 전술 성공! 커세어만으로는 야바위를 막을 수 없었습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        ScriptBranch(
          id: 'away_wins',
          conditionStat: 'control',
          baseProbability: 2.5,
          events: [
            ScriptEvent(
              text: '{away} 선수 커세어가 오버로드를 전멸시킵니다! 보급이 막힙니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayResource: 0,
              homeResource: -20,
              awayArmy: 3,
              altText: '{away}, 오버로드 전멸! 저그 보급이 걸립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 드라군이 럴커 위치를 파악하고 집중 사격합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 4,
              homeArmy: -5,
            ),
            ScriptEvent(
              text: '{home} 선수 병력 재생산이 안 됩니다! 보급이 부족해요!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: -4,
              homeResource: -10,
            ),
            ScriptEvent(
              text: '커세어의 오버로드 사냥이 결정적! 야바위가 통하지 않았습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
