part of '../../scenario_scripts.dart';

const _tvzBbsVsLurkerDefiler = ScenarioScript(
  id: 'tvz_bbs_vs_lurker_defiler',
  matchup: 'TvZ',
  homeBuildIds: ['tvz_bbs'],
  awayBuildIds: ['zvt_trans_lurker_defiler', 'zvt_2hatch_lurker'],
  description: 'BBS vs 럴커 디파일러',
  phases: [
    // Phase 0: BBS 오프닝 + 저그 오프닝
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      recoveryArmyPerLine: 0,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 배럭 건설을 시작합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -150,
          altText: '{home} 선수 배럭을 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 스포닝풀 건설을 시작합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -200,
          altText: '{away} 선수 스포닝풀을 올립니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 두 번째 배럭을 올립니다! 배럭을 두 개 올립니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -150,
          homeArmy: 2,
          altText: '{home} 선수 배럭 두 개에서 마린이 쏟아집니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 저글링을 생산합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: 4,
          altText: '{away} 선수 저글링이 나오기 시작합니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 SCV까지 끌고 상대 앞마당으로 돌진합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: 4,
          altText: '{home} 선수 전 병력 돌진! 마린을 계속 모으고 있습니다!',
        ),
        ScriptEvent(
          text: '마린을 계속 모으고 있습니다! 초반에 승부를 걸겠다는 겁니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.3,
          altText: '마린과 SCV를 끌고 갑니다! 올인 러쉬!',
        ),
      ],
    ),
    // Phase 1: BBS 돌진 결과
    ScriptPhase(
      name: 'bbs_rush',
      recoveryArmyPerLine: 1,
      branches: [
        ScriptBranch(
          id: 'bbs_success',
          baseProbability: 1.0,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{home} 선수 마린이 앞마당에 도착합니다! 벙커를 올립니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -100,
              homeArmy: 2,
              altText: '{home} 선수 앞마당에 벙커를 짓습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 벙커가 완성됩니다! 마린을 넣습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -3,
              altText: '{home} 선수 벙커 완성! 저글링을 막아냅니다!',
            ),
            ScriptEvent(
              text: '벙커 수리가 견고합니다! 저글링이 닿지 못합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -3,
              altText: 'SCV 수리로 벙커를 유지합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 마린을 추가 생산해 밀어붙입니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 3, awayArmy: -2,
              decisive: true,
              altText: '{home} 선수 마린 물량! 저그가 막을 수 없습니다!',
            ),
          ],
        ),
        ScriptBranch(
          id: 'bbs_partial',
          baseProbability: 0.8,
          events: [
            ScriptEvent(
              text: '{home} 선수 마린이 앞마당에 도착하지만 저글링이 막습니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2, awayArmy: -2,
              altText: '{home} 선수 앞마당 도착! 저글링과 격돌!',
            ),
            ScriptEvent(
              text: '{home} 선수 벙커 건설을 시도하지만 방해를 받습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayResource: 0,
              homeResource: -100, awayArmy: -1,
              altText: '{home} 선수 벙커 건설 시작! SCV가 적 병력에 쫓기고 있습니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 성큰 건설로 방어선을 구축합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: -150, awayArmy: 3,
              altText: '{away} 선수 성큰을 올립니다, 수비 태세입니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 드론을 동원해 벙커를 때립니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -3,
              altText: '{away} 선수 드론 합세! 벙커를 집중 공격합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 초반 공격을 막아냈습니다! 테란이 후속이 없습니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
              decisive: true,
              altText: '{away} 선수 방어 성공! 자원 차이가 벌어집니다!',
            ),
          ],
        ),
        ScriptBranch(
          id: 'bbs_fail',
          baseProbability: 1.0,
          conditionStat: 'defense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수 정찰 드론으로 배럭 두 개를 미리 파악합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away} 선수 드론 정찰! 배럭 두 개를 읽었습니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 성큰을 미리 건설하고 저글링을 모읍니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: -150, awayArmy: 4,
              altText: '{away} 선수 성큰 선제 건설! 저글링도 대기합니다!',
            ),
            ScriptEvent(
              text: '마린이 성큰 앞에서 녹아내립니다!',
              owner: LogOwner.system,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4, awayArmy: -1,
              altText: '성큰의 화력! 마린이 버티지 못합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링으로 마린 잔여 병력을 정리합니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -3,
              altText: '{away} 선수 저글링이 마린을 쓸어냅니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 초반 공격을 완벽히 막아냈습니다! 자원 차이가 압도적입니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 완벽 수비! 테란은 할 수 있는 게 없습니다!',
            ),
          ],
        ),
      ],
    ),
  ],
);
