part of '../../scenario_scripts.dart';

const _tvzNobarDoubleVsMutalLurker = ScenarioScript(
  id: 'tvz_nobar_double_vs_mutal_lurker',
  matchup: 'TvZ',
  homeBuildIds: ['tvz_nobar_double'],
  awayBuildIds: ['zvt_trans_mutal_lurker', 'zvt_12pool', 'zvt_9pool'],
  description: '노배럭더블 vs 뮤탈 럴커',
  phases: [
    // Phase 0: 오프닝
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      recoveryResourcePerLine: 100,
      recoveryArmyPerLine: 0,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 커맨드센터를 먼저 건설합니다.',
          owner: LogOwner.home,
          homeResource: -400,
          fixedCost: true,
          homeExpansion: true,
          altText: '{home} 선수 앞마당에 커맨드센터 퍼스트!',
        ),
        ScriptEvent(
          text: '{home} 선수 배럭 건설을 시작합니다.',
          owner: LogOwner.home,
          homeResource: -150,
          fixedCost: true,
          altText: '{home} 선수 뒤늦게 배럭을 올립니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 앞마당 커맨드센터가 완성됩니다. 일꾼 생산을 시작합니다.',
          owner: LogOwner.home,
          fixedCost: true,
          altText: '{home} 선수 앞마당 커맨드, 자원 채취가 시작됩니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 가스를 올리고 팩토리 건설을 시작합니다.',
          owner: LogOwner.home,
          homeResource: -400,
          fixedCost: true,
          altText: '{home} 선수 리파이너리와 팩토리를 착공합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 스포닝풀 건설을 시작합니다.',
          owner: LogOwner.away,
          awayResource: -200,
          fixedCost: true,
          altText: '{away} 선수 스포닝풀을 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 앞마당 해처리를 건설합니다.',
          owner: LogOwner.away,
          awayResource: -300,
          fixedCost: true,
          awayExpansion: true,
          altText: '{away} 선수 앞마당 확장입니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 가스를 올리고 저글링을 생산합니다.',
          owner: LogOwner.away,
          awayResource: -100,
          awayArmy: 3,
          fixedCost: true,
          altText: '{away} 선수 익스트랙터와 저글링 생산입니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 레어 업그레이드를 시작합니다.',
          owner: LogOwner.away,
          awayResource: -150,
          fixedCost: true,
          altText: '{away} 선수 레어로 업그레이드합니다.',
        ),
        ScriptEvent(
          text: '노배럭더블 vs 공중 매복, 치열한 대결이 예상됩니다.',
          owner: LogOwner.system,
          skipChance: 0.4,
          altText: '양측 빌드가 확인됩니다. 본격적인 전개가 시작됩니다.',
        ),
      ],
    ),
    // Phase 1: 중반 전개
    ScriptPhase(
      name: 'mid_game',
      startLine: 12,
      recoveryArmyPerLine: 1,
      recoveryResourcePerLine: 150,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 벌처를 생산하며 정찰을 보냅니다.',
          owner: LogOwner.home,
          homeArmy: 2,
          homeResource: -75,
          fixedCost: true,
          favorsStat: 'scout',
          altText: '{home} 선수 벌처가 정찰을 나갑니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 엔지니어링 베이 건설을 시작합니다.',
          owner: LogOwner.home,
          homeResource: -125,
          fixedCost: true,
          altText: '{home} 선수 엔지니어링 베이를 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 스파이어 건설을 시작합니다.',
          owner: LogOwner.away,
          awayResource: -200,
          fixedCost: true,
          altText: '{away} 선수 스파이어를 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 뮤탈리스크 생산을 시작합니다.',
          owner: LogOwner.away,
          awayArmy: 4,
          awayResource: -300,
          fixedCost: true,
          altText: '{away} 선수 뮤탈리스크가 나옵니다!',
        ),
        ScriptEvent(
          text: '양측 중반 전개가 시작됩니다.',
          owner: LogOwner.system,
          skipChance: 0.4,
          altText: '본격적인 중반 대결이 펼쳐집니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 터렛을 건설하며 방어 준비를 합니다.',
          owner: LogOwner.home,
          homeResource: -100,
          fixedCost: true,
          skipChance: 0.3,
          altText: '{home} 선수 터렛을 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 저글링으로 압박을 시도합니다.',
          owner: LogOwner.away,
          awayArmy: 2,
          favorsStat: 'attack',
          altText: '{away} 선수 저글링 공격! 테란 라인을 압박합니다.',
        ),
      ],
    ),
    // Phase 2: 전환기
    ScriptPhase(
      name: 'transition',
      startLine: 22,
      recoveryArmyPerLine: 2,
      recoveryResourcePerLine: 150,
      branches: [
        ScriptBranch(
          id: 'terran_enbe_3bar',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{home} 선수 엔지니어링 베이를 올리고 3배럭 체제로 전환합니다.',
              owner: LogOwner.home,
              homeResource: -300,
              fixedCost: true,
              altText: '{home} 선수 선엔베 3배럭 전환입니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 마린 생산을 시작합니다.',
              owner: LogOwner.home,
              homeArmy: 3,
              homeResource: -200,
              fixedCost: true,
              altText: '{home} 선수 마린가 나옵니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 뮤탈리스크 병력이 늘어갑니다.',
              owner: LogOwner.away,
              awayArmy: 3,
              favorsStat: 'strategy',
              altText: '{away} 선수 뮤탈리스크를 추가 생산합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 마린와 메딕로 공격 준비를 합니다.',
              owner: LogOwner.home,
              homeArmy: 2,
              favorsStat: 'macro',
              altText: '{home} 선수 병력을 모읍니다.',
            ),
          ],
        ),
        ScriptBranch(
          id: 'terran_5bar',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{home} 선수 배럭을 추가 건설합니다. 5배럭 체제합니다.',
              owner: LogOwner.home,
              homeResource: -300,
              fixedCost: true,
              altText: '{home} 선수 5배럭 푸시 전환입니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 마린 생산을 시작합니다.',
              owner: LogOwner.home,
              homeArmy: 3,
              homeResource: -200,
              fixedCost: true,
              altText: '{home} 선수 마린가 나옵니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 뮤탈리스크 병력이 늘어갑니다.',
              owner: LogOwner.away,
              awayArmy: 3,
              favorsStat: 'strategy',
              altText: '{away} 선수 뮤탈리스크를 추가 생산합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 마린와 메딕로 공격 준비를 합니다.',
              owner: LogOwner.home,
              homeArmy: 2,
              favorsStat: 'macro',
              altText: '{home} 선수 병력을 모읍니다.',
            ),
          ],
        ),
        ScriptBranch(
          id: 'terran_3fac_goliath',
          baseProbability: 0.7,
          events: [
            ScriptEvent(
              text: '{home} 선수 팩토리를 추가 건설합니다합니다.',
              owner: LogOwner.home,
              homeResource: -300,
              fixedCost: true,
              altText: '{home} 선수 3팩 골리앗 전환입니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 골리앗 생산을 시작합니다.',
              owner: LogOwner.home,
              homeArmy: 3,
              homeResource: -200,
              fixedCost: true,
              altText: '{home} 선수 골리앗가 나옵니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 뮤탈리스크 병력이 늘어갑니다.',
              owner: LogOwner.away,
              awayArmy: 3,
              favorsStat: 'strategy',
              altText: '{away} 선수 뮤탈리스크를 추가 생산합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 골리앗와 시즈탱크로 공격 준비를 합니다.',
              owner: LogOwner.home,
              homeArmy: 2,
              favorsStat: 'macro',
              altText: '{home} 선수 병력을 모읍니다.',
            ),
          ],
        ),
        ScriptBranch(
          id: 'zerg_transition',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{away} 선수 히드라덴을 건설하고 럴커로 전환합니다.',
              owner: LogOwner.away,
              awayResource: -300,
              fixedCost: true,
              altText: '{away} 선수 럴커를 매복시킵니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 뮤탈리스크로 테란 앞마당을 견제합니다!',
              owner: LogOwner.away,
              homeResource: -150,
              favorsStat: 'harass',
              altText: '{away} 선수 뮤탈리스크 견제! 일꾼 피해를 줍니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 병력을 모아 방어합니다.',
              owner: LogOwner.home,
              homeArmy: 2,
              favorsStat: 'defense',
              altText: '{home} 선수 수비 태세, 견제를 막아냅니다.',
            ),
            ScriptEvent(
              text: '{away} 선수 추가 확장을 시도합니다.',
              owner: LogOwner.away,
              awayResource: -300,
              fixedCost: true,
              awayExpansion: true,
              altText: '{away} 선수 멀티 확장! 자원 라인을 늘립니다.',
            ),
          ],
        ),
      ],
    ),
    // Phase 3: 결전
    ScriptPhase(
      name: 'decisive',
      startLine: 30,
      recoveryArmyPerLine: 2,
      recoveryResourcePerLine: 200,
      branches: [
        ScriptBranch(
          id: 'terran_wins',
          baseProbability: 1.0,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{home} 선수 대규모 병력을 이끌고 진격합니다!',
              owner: LogOwner.home,
              homeArmy: 4,
              favorsStat: 'strategy',
              altText: '{home} 선수 총공격! 병력을 쏟아냅니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 저그 앞마당을 밀어붙입니다!',
              owner: LogOwner.home,
              awayArmy: -5, homeArmy: -2,
              favorsStat: 'attack',
              altText: '{home} 선수 앞마당 공격! 저그 병력을 격파합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 저그의 방어선을 돌파합니다!',
              owner: LogOwner.home,
              awayArmy: -4,
              favorsStat: 'control',
              altText: '{home} 선수 돌파! 저그가 무너집니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 본진까지 밀고 들어갑니다! GG!',
              owner: LogOwner.home,
              awayArmy: -3,
              decisive: true,
              altText: '{home} 선수 완파! 테란의 승리입니다!',
            ),
          ],
        ),
        ScriptBranch(
          id: 'zerg_wins',
          baseProbability: 1.0,
          conditionStat: 'attack',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수 뮤탈리스크로 테란 라인을 공격합니다!',
              owner: LogOwner.away,
              homeArmy: -3, awayArmy: -1,
              favorsStat: 'attack',
              altText: '{away} 선수 뮤탈리스크 돌진! 테란 라인이 뚫립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링이 다방면으로 침투합니다!',
              owner: LogOwner.away,
              homeResource: -300,
              favorsStat: 'harass',
              altText: '{away} 선수 멀티 견제! 일꾼을 잡아냅니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 추가 병력이 밀려옵니다!',
              owner: LogOwner.away,
              homeArmy: -4, awayArmy: -2,
              favorsStat: 'macro',
              altText: '{away} 선수 물량 공세! 테란이 막기 힘듭니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 테란의 방어선을 완전히 돌파합니다! GG!',
              owner: LogOwner.away,
              homeArmy: -3,
              decisive: true,
              altText: '{away} 선수 완파! 저그의 승리입니다!',
            ),
          ],
        ),
        ScriptBranch(
          id: 'terran_timing',
          baseProbability: 0.6,
          conditionStat: 'strategy',
          events: [
            ScriptEvent(
              text: '{home} 선수 타이밍 공격을 갑니다!',
              owner: LogOwner.home,
              homeArmy: 3,
              favorsStat: 'strategy',
              altText: '{home} 선수 타이밍! 지금이 기회입니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 저그의 확장 기지를 노립니다!',
              owner: LogOwner.home,
              awayResource: -400,
              favorsStat: 'attack',
              altText: '{home} 선수 확장 기지 공격! 자원 라인을 끊습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 저그 확장을 파괴하고 병력을 압박합니다!',
              owner: LogOwner.home,
              awayArmy: -5, homeArmy: -3,
              favorsStat: 'control',
              altText: '{home} 선수 확장 파괴 후 밀어붙입니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 자원 라인을 끊었습니다! 승기를 잡습니다!',
              owner: LogOwner.home,
              decisive: true,
              altText: '{home} 선수 자원 고갈! 테란의 승리!',
            ),
          ],
        ),
        ScriptBranch(
          id: 'zerg_overrun',
          baseProbability: 0.6,
          conditionStat: 'macro',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수 다방면 동시 공격을 감행합니다!',
              owner: LogOwner.away,
              awayArmy: 3,
              favorsStat: 'strategy',
              altText: '{away} 선수 멀티 공격! 테란의 시선을 분산시킵니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 뮤탈리스크로 테란 본진을 위협합니다!',
              owner: LogOwner.away,
              homeArmy: -3,
              favorsStat: 'attack',
              altText: '{away} 선수 본진 위협! 테란이 갈팡질팡합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 물량으로 테란 방어선을 부숩니다!',
              owner: LogOwner.away,
              homeArmy: -4, awayArmy: -3,
              favorsStat: 'macro',
              altText: '{away} 선수 물량 공세! 테란이 버티지 못합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 테란을 완전히 제압합니다! GG!',
              owner: LogOwner.away,
              decisive: true,
              altText: '{away} 선수 압도적인 물량! 저그 승리!',
            ),
          ],
        ),
      ],
    ),
  ],
);
