part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 투게이트 질럿 오프닝 vs 업그레이드 운영
// ----------------------------------------------------------
const _pvt2gateOpenVsUpgrade = ScenarioScript(
  id: 'pvt_2gate_open_vs_upgrade',
  matchup: 'PvT',
  homeBuildIds: ['pvt_2gate_open', 'pvt_2gate_zealot'],
  awayBuildIds: ['tvp_trans_upgrade', 'tvp_1fac_gosu'],
  description: '투게이트 질럿 압박 vs 업그레이드 운영 — 초반 피해가 핵심',
  phases: [
    // Phase 0: 오프닝 (lines 1-11)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 게이트웨이를 세웁니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -15,
          altText: '{home}, 첫 게이트웨이 건설!',
        ),
        ScriptEvent(
          text: '{away} 선수 배럭 건설 후 앞마당 커맨드센터를 올립니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -30,
          altText: '{away}, 빠른 앞마당! 업그레이드를 준비하는 운영형 빌드네요!',
        ),
        ScriptEvent(
          text: '{home} 선수 두 번째 게이트웨이를 올립니다! 질럿을 빠르게 모으겠네요!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -15,
        ),
        ScriptEvent(
          text: '{away} 선수 엔지니어링 베이 건설! 공격력 업그레이드를 시작합니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -10,
        ),
        ScriptEvent(
          text: '테란이 업그레이드에 투자하고 있습니다! 초반이 약할 수밖에 없죠!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          text: '{home} 선수 질럿 2기를 모아 전진합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 3,
          homeResource: -10,
        ),
      ],
    ),
    // Phase 1: 질럿 압박 (lines 12-21)
    ScriptPhase(
      name: 'mid_game',
      recoveryArmyPerLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 질럿이 테란 앞마당에 도착합니다! SCV를 노립니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          homeResource: 0,
          homeArmy: 1,
          awayResource: -10,
          altText: '{home}, 질럿 침투! 일꾼을 잡으러 갑니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 마린이 부족합니다! 벙커를 급하게 올립니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 1,
          awayResource: -10,
        ),
        ScriptEvent(
          text: '{home} 선수 질럿이 SCV를 쫓아갑니다! 일꾼 피해가 나옵니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -15,
          altText: '{home}, 질럿이 라인을 휘젓습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 벙커에 마린을 넣어 질럿을 막습니다!',
          owner: LogOwner.away,
          homeResource: 0,
          awayResource: 0,
          homeArmy: -2,
          awayArmy: 1,
        ),
        ScriptEvent(
          text: '초반 피해를 얼마나 줬느냐가 이 경기의 분수령이 됩니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.2,
        ),
      ],
    ),
    // Phase 2: 드라군 전환 vs 업그레이드 완성 (lines 22-29)
    ScriptPhase(
      name: 'late_setup',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 사이버네틱스 코어를 올립니다! 드라군 전환!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -15,
          altText: '{home}, 사이버네틱스 코어 건설! 드라군으로 전환합니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 1차 공격력 업그레이드 완료! 마린 화력이 달라집니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: 3,
        ),
        ScriptEvent(
          text: '{home} 선수 넥서스를 건설합니다! 자원 확보가 중요합니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -30,
        ),
        ScriptEvent(
          text: '{away} 선수 아카데미 건설! 메딕과 스팀팩을 준비합니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -10,
          altText: '{away}, 아카데미가 올라갑니다! 스팀팩이 나오면 무섭습니다!',
        ),
        ScriptEvent(
          text: '업그레이드가 완성되기 시작합니다! 시간이 갈수록 테란이 유리해지죠!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.3,
        ),
      ],
    ),
    // Phase 3: 결전 (lines 30+)
    ScriptPhase(
      name: 'decisive_battle',
      branches: [
        ScriptBranch(
          id: 'home_wins',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{home} 선수 드라군 물량이 모였습니다! 업그레이드 완성 전에 밀어야 합니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 4,
              altText: '{home}, 드라군 대군! 지금이 타이밍입니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 아직 2차 업그레이드가 덜 됐습니다! 마린 화력이 부족합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -3,
              homeArmy: -1,
            ),
            ScriptEvent(
              text: '{home} 선수 초반 질럿 피해가 크게 작용합니다! 테란 병력이 적습니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 3,
              awayArmy: -4,
            ),
            ScriptEvent(
              text: '초반 질럿 압박의 효과! 업그레이드가 완성되기 전에 끝납니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{home} 선수 드라군이 테란 진지를 돌파합니다! 업그레이드를 기다릴 수 없었습니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 25,
              awayArmy: -15,
              decisive: true,
              altText: '{home} 선수 초반 피해를 살려 타이밍에 밀어냅니다!',
            ),
          ],
        ),
        ScriptBranch(
          id: 'away_wins',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              text: '{away} 선수 업그레이드 마린이 드라군을 상대합니다! 화력 차이가 납니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 4,
              homeArmy: -3,
              altText: '{away}, 업그레이드 완료 마린! 화력이 다릅니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 드라군이 녹습니다! 업그레이드 차이가 심합니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4,
              awayArmy: -1,
            ),
            ScriptEvent(
              text: '{away} 선수 메딕까지 합류합니다! 마린이 안 죽습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 3,
            ),
            ScriptEvent(
              text: '업그레이드의 힘! 초반을 버텨낸 테란이 물량으로 밀어붙입니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{away} 선수 업그레이드 마린 메딕으로 프로토스를 압도합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 25,
              homeArmy: -15,
              decisive: true,
              altText: '{away} 선수 초반을 버텨내고 업그레이드 차이로 승리합니다!',
            ),
          ],
        ),
      ],
    ),
  ],
);
