part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 리버 푸시 vs 타이밍 푸시: 셔틀 견제로 타이밍 지연
// ----------------------------------------------------------
const _pvtReaverPushVsTimingPush = ScenarioScript(
  id: 'pvt_reaver_push_vs_timing_push',
  matchup: 'PvT',
  homeBuildIds: ['pvt_trans_reaver_push', 'pvt_reaver_shuttle', 'pvt_proxy_dark'],
  awayBuildIds: ['tvp_trans_timing_push', 'tvp_fake_double', 'tvp_1fac_drop'],
  description: '리버 셔틀 푸시 vs 타이밍 공격 — 견제로 타이밍을 늦춰라',
  phases: [
    // Phase 0: opening (lines 1-11)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 게이트웨이 건설 후 사이버네틱스 코어를 올립니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -15,
        ),
        ScriptEvent(
          text: '{away} 선수 배럭에서 마린을 생산하고 팩토리를 건설합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 1,
          awayResource: -15,
        ),
        ScriptEvent(
          text: '{home} 선수 사이버네틱스 코어에서 드라군을 생산합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 2,
          homeResource: -10,
          altText: '{home}, 드라군 생산! 초반 방어 병력을 확보합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 팩토리에서 벌처를 뽑으면서 타이밍을 준비합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2,
          awayResource: -10,
        ),
        ScriptEvent(
          text: '{home} 선수 로보틱스와 서포트 베이 건설! 셔틀을 빠르게 확보하려 합니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -15,
          altText: '{home}, 로보틱스와 서포트 베이가 올라갑니다! 빠른 셔틀 빌드!',
        ),
        ScriptEvent(
          text: '{away} 선수 아카데미 건설 후 마린 메딕 생산을 시작합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayResource: -15,
          awayArmy: 1,
        ),
        ScriptEvent(
          text: '양측 모두 공격적인 빌드를 선택했습니다! 타이밍 싸움이 되겠군요!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 1: 셔틀 리버 출격 (lines 12-21)
    ScriptPhase(
      name: 'mid_game',
      recoveryArmyPerLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 셔틀에 리버를 태워 테란 진영으로 보냅니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 3,
          homeResource: -20,
        ),
        ScriptEvent(
          text: '{away} 선수 마린 메딕 병력을 모아서 출발합니다! 타이밍 공격!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 4,
          awayResource: -15,
          altText: '{away}, 마린 메딕 부대가 프로토스를 향해 출발합니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 리버 스캐럽이 테란 앞마당에서 SCV를 잡습니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -20,
          skipChance: 0.3,
        ),
        ScriptEvent(
          text: '{away} 선수 병력 일부를 돌려야 하는 상황! 타이밍이 늦어집니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: -1,
        ),
        ScriptEvent(
          text: '리버 견제가 타이밍을 흔들고 있습니다! 셔틀 마이크로가 관건이죠!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 2: 타이밍 공격 도착 (lines 22-29)
    ScriptPhase(
      name: 'late_setup',
      recoveryArmyPerLine: 2,
      linearEvents: [
        ScriptEvent(
          text: '{away} 선수 타이밍 병력이 프로토스 앞마당에 도착합니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayResource: 0,
          awayArmy: 3,
          altText: '{away}, 마린 메딕이 프로토스 진영에 모습을 드러냅니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 드라군으로 입구를 막으면서 리버를 회수합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 2,
          homeResource: -10,
        ),
        ScriptEvent(
          text: '{home} 선수 리버가 본진에서 정면 전투에 합류합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          homeArmy: 2,
          skipChance: 0.2,
        ),
        ScriptEvent(
          text: '타이밍 공격과 리버의 정면 대결! 누가 이길까요!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
        ),
      ],
    ),
    // Phase 3: 결전 (lines 30+)
    ScriptPhase(
      name: 'decisive_battle',
      branches: [
        ScriptBranch(
          id: 'home_wins',
          baseProbability: 1.0,
          conditionStat: 'control',
          events: [
            ScriptEvent(
              text: '{home} 선수 리버 스캐럽이 마린 뭉치에 명중합니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 2,
              awayArmy: -4,
              altText: '{home}, 스캐럽이 마린 집단에 떨어집니다! 엄청난 피해!',
            ),
            ScriptEvent(
              text: '{away} 선수 메딕이 힐을 하지만 화력이 부족합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
            ),
            ScriptEvent(
              text: '{home} 선수 드라군이 전진하며 남은 병력을 쓸어냅니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 3,
              awayArmy: -2,
            ),
            ScriptEvent(
              text: '리버 한 방이 타이밍을 박살냈습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        ScriptBranch(
          id: 'away_wins',
          baseProbability: 1.0,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{away} 선수 마린이 리버 사거리 밖에서 집중 사격합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 3,
              homeArmy: -3,
              altText: '{away}, 마린 화력이 드라군을 녹입니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 리버 스캐럽이 빗나갑니다! 치명적인 실수!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
            ),
            ScriptEvent(
              text: '{away} 선수 마린 메딕이 넥서스를 직접 공격합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayResource: 0,
              awayArmy: 2,
              homeResource: -25,
            ),
            ScriptEvent(
              text: '타이밍 공격이 성공합니다! 프로토스 무너집니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
