part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 12풀 미러 (스탠다드 미러)
// ----------------------------------------------------------
const _zvz12poolMirror = ScenarioScript(
  id: 'zvz_12pool_mirror',
  matchup: 'ZvZ',
  homeBuildIds: ['zvz_12pool'],
  awayBuildIds: ['zvz_12pool'],
  description: '12풀 미러 스탠다드 대결',
  phases: [
    // Phase 0: 오프닝 (lines 1-16)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 드론을 뽑기 시작합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -5,
        ),
        ScriptEvent(
          text: '{away} 선수 드론 생산합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -5,
        ),
        ScriptEvent(
          text: '{home} 선수 12드론에 스포닝풀 건설!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -15,
          altText: '{home} 선수, 스포닝풀! 스탠다드한 오프닝입니다!',
        ),
        ScriptEvent(
          text: '{away} 선수도 12드론에 스포닝풀!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -15,
          altText: '{away} 선수도 스포닝풀! 스탠다드한 오프닝이네요!',
        ),
        ScriptEvent(
          text: '{home} 선수 익스트랙터 건설! 가스를 채취합니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -5,
          altText: '{home}, 가스를 올립니다! 발업을 위한 준비!',
        ),
        ScriptEvent(
          text: '{away} 선수도 익스트랙터! 양쪽 다 가스를 모읍니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -5,
          altText: '{away} 선수도 가스! 발업 준비에 들어갑니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 저글링 생산! 발업 연구 시작합니다!',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 4, homeResource: -10,
        ),
        ScriptEvent(
          text: '{away} 선수도 저글링과 발업! 앞마당 타이밍을 노립니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 4, awayResource: -10,
        ),
        ScriptEvent(
          text: '앞마당 타이밍이 승부의 관건입니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.3,
        ),
      ],
    ),
    // Phase 1: 앞마당 확장 타이밍 - 분기
    ScriptPhase(
      name: 'expansion_timing',
      branches: [
        // 분기 A: 동시 확장 (가장 빈번)
        ScriptBranch(
          id: 'both_expand',
          baseProbability: 1.2,
          conditionStat: 'strategy',
          events: [
            ScriptEvent(
              text: '{home} 선수 저글링을 모으면서 앞마당 해처리를 건설합니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -25,
              altText: '{home}, 앞마당! 저글링을 앞에 세워두고 확장합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수도 앞마당 해처리! 저글링으로 입구를 막으면서 확장합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -25,
              altText: '{away}, 앞마당 건설! 서로 확장하는 모습입니다!',
            ),
            ScriptEvent(
              text: 'ZvZ에서 앞마당을 올리는 순간이 가장 위험한 타이밍이죠!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.2,
            ),
            ScriptEvent(
              text: '{home} 선수 성큰을 앞마당에 깔아놓습니다.',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -15,
              skipChance: 0.3,
            ),
            ScriptEvent(
              text: '{away} 선수도 성큰 건설! 수비 태세!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -15,
              skipChance: 0.3,
            ),
          ],
        ),
        // 분기 B: 홈 빠른 확장 → 어웨이 저글링 압박
        ScriptBranch(
          id: 'home_fast_expand',
          baseProbability: 0.5,
          conditionStat: 'macro',
          events: [
            ScriptEvent(
              text: '{home} 선수 먼저 앞마당 해처리를 건설합니다! 과감한 판단!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 2, homeResource: -25,
              altText: '{home}, 빠른 앞마당! 라바 이점을 노립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수, 상대 앞마당을 보고 저글링을 뭉칩니다! 압박 타이밍!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4, awayResource: -10,            ),
            ScriptEvent(
              text: '{home} 선수 성큰 완성 전! 드론과 저글링으로 필사적으로 막습니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2, awayArmy: -2,              altText: '{home}, 저글링으로 입구를 막으면서 시간을 법니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 버텨냅니다! 앞마당 드론이 돌기 시작합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: 10,
              altText: '수비 성공! {home} 선수 앞마당이 안정적으로 가동됩니다!',
            ),
          ],
        ),
        // 분기 C: 어웨이 빠른 확장 → 홈 저글링 압박
        ScriptBranch(
          id: 'away_fast_expand',
          baseProbability: 0.5,
          conditionStat: 'macro',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수 먼저 앞마당 해처리를 건설합니다! 과감한 판단!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2, awayResource: -25,
              altText: '{away}, 빠른 앞마당! 라바 이점을 노립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수, 상대 앞마당을 보고 저글링을 뭉칩니다! 압박 타이밍!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 4, homeResource: -10,            ),
            ScriptEvent(
              text: '{away} 선수 성큰 완성 전! 드론과 저글링으로 필사적으로 막습니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2, homeArmy: -2,              altText: '{away}, 저글링으로 입구를 막으면서 시간을 법니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 버텨냅니다! 앞마당 드론이 돌기 시작합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 10,
              altText: '수비 성공! {away} 선수 앞마당이 안정적으로 가동됩니다!',
            ),
          ],
        ),
        // 분기 D: 홈 저글링 올인 (확장 스킵)
        ScriptBranch(
          id: 'home_ling_allin',
          baseProbability: 0.3,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{home} 선수 앞마당을 올리지 않습니다! 저글링을 계속 뽑습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 6, homeResource: -15,
              altText: '{home}, 확장 포기! 저글링 물량으로 승부하겠다는 판단!',
            ),
            ScriptEvent(
              text: '{away} 선수 앞마당 건설중인데 저글링이 몰려옵니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -25,
            ),
            ScriptEvent(
              text: '{home} 선수 발업 저글링 물량 투입! 앞마당 드론을 초토화시킵니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayArmy: -5, awayResource: -20, homeArmy: -3,            ),
            ScriptEvent(
              text: '앞마당이 무너집니다! {home} 선수 저글링 올인 성공!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기 E: 어웨이 저글링 올인 (확장 스킵)
        ScriptBranch(
          id: 'away_ling_allin',
          baseProbability: 0.3,
          conditionStat: 'attack',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수 앞마당을 올리지 않습니다! 저글링을 계속 뽑습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 6, awayResource: -15,
              altText: '{away}, 확장 포기! 저글링 물량으로 승부하겠다는 판단!',
            ),
            ScriptEvent(
              text: '{home} 선수 앞마당 건설중인데 저글링이 몰려옵니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -25,
            ),
            ScriptEvent(
              text: '{away} 선수 발업 저글링 물량 투입! 앞마당 드론을 초토화시킵니다!',
              owner: LogOwner.away,
              awayResource: 0,
              homeArmy: -5, homeResource: -20, awayArmy: -3,            ),
            ScriptEvent(
              text: '앞마당이 무너집니다! {away} 선수 저글링 올인 성공!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
    // Phase 2: 저글링 견제 - 분기
    ScriptPhase(
      name: 'ling_skirmish',
      recoveryArmyPerLine: 1,
      branches: [
        // 분기 A: 홈이 저글링 견제 성공
        ScriptBranch(
          id: 'home_ling_harass',
          baseProbability: 0.6,
          conditionStat: 'harass',
          events: [
            ScriptEvent(
              text: '{home} 선수 저글링 견제! 앞마당 드론을 물어뜯습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: -10, awayArmy: -2,              altText: '{home}, 저글링으로 상대 앞마당 드론을 노립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 성큰이 아직 완성되지 않았습니다! 드론으로 막습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -1,
            ),
            ScriptEvent(
              text: '{home}, 드론 2기를 잡고 빠집니다! 약간의 이득!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -5,              altText: '{home} 선수 깔끔한 견제! 드론 피해를 주고 빠집니다!',
            ),
            ScriptEvent(
              text: '소소한 견제 성공! 이 작은 차이가 중요합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
            ),
          ],
        ),
        // 분기 B: 어웨이가 저글링 견제 성공
        ScriptBranch(
          id: 'away_ling_harass',
          baseProbability: 0.6,
          conditionStat: 'harass',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수 저글링 견제! 앞마당 드론을 물어뜯습니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -10, homeArmy: -2,              altText: '{away}, 저글링으로 상대 앞마당 드론을 노립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 성큰이 아직 완성되지 않았습니다! 드론으로 막습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -1,
            ),
            ScriptEvent(
              text: '{away}, 드론 2기를 잡고 빠집니다! 약간의 이득!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -5,              altText: '{away} 선수 깔끔한 견제! 드론 피해를 주고 빠집니다!',
            ),
            ScriptEvent(
              text: '소소한 견제 성공! 이 작은 차이가 중요합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
            ),
          ],
        ),
        // 분기 C: 저글링 이븐 (양쪽 소모전)
        ScriptBranch(
          id: 'ling_even',
          baseProbability: 0.8,
          conditionStat: 'control',
          events: [
            ScriptEvent(
              text: '{home} 선수 저글링으로 정찰! {away} 선수도 저글링을 내보냅니다!',
              owner: LogOwner.system,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -1, awayArmy: -1,
            ),
            ScriptEvent(
              text: '양쪽 저글링이 맞붙습니다! 서로 비슷한 피해를 주고받습니다!',
              owner: LogOwner.system,
              homeArmy: -2, awayArmy: -2, homeResource: -5, awayResource: -5,
              altText: '저글링 소모전! 큰 이득 없이 서로 소비합니다!',
            ),
            ScriptEvent(
              text: '양쪽 다 저글링을 보충하면서 테크로 넘어갑니다!',
              owner: LogOwner.system,
              homeArmy: 2, awayArmy: 2, homeResource: -10, awayResource: -10,
              altText: '소모전 끝! 이제 테크 싸움입니다!',
            ),
          ],
        ),
      ],
    ),
    // Phase 3: 스파이어 경쟁
    ScriptPhase(
      name: 'spire_race',
      recoveryArmyPerLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 레어 진화를 시작합니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -15,
          altText: '{home}, 해처리를 레어로 진화시킵니다!',
        ),
        ScriptEvent(
          text: '{away} 선수도 레어 진화! 누가 먼저 완성할까요?',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -15,
          altText: '{away} 선수도 레어! 테크 싸움이 시작됩니다!',
        ),
        ScriptEvent(
          text: '레어를 진화시키는 동안이 서로에게 가장 위험합니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          skipChance: 0.2,
        ),
        ScriptEvent(
          text: '{home} 선수 성큰을 추가하면서 저글링 공격에 대비합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 2, homeResource: -15,
          skipChance: 0.3,
        ),
        ScriptEvent(
          text: '{home} 선수 레어 완성! 다음 단계로 넘어갑니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -5,
          altText: '{home}, 레어 완성! 테크가 올라갑니다!',
        ),
        ScriptEvent(
          text: '{home} 선수 스파이어 건설! 공중 유닛 생산이 코앞입니다!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -10,
        ),
        ScriptEvent(
          text: '{away} 선수도 스파이어 건설! 누가 먼저 공중 유닛을 뽑을까요?',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -15,
          altText: '{away}, 스파이어! 양쪽 공중전이 본격화됩니다!',
        ),
      ],
    ),
    // Phase 4: 뮤탈 교전 - 분기
    ScriptPhase(
      name: 'mutal_clash',
      branches: [
        // 분기 A: 홈 뮤탈 컨트롤 우위 (공격형)
        ScriptBranch(
          id: 'home_mutal_wins',
          baseProbability: 0.6,
          conditionStat: 'control',
          events: [
            ScriptEvent(
              text: '{home} 선수 뮤탈리스크가 나옵니다! 스커지도 섞습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 5, homeResource: -20,
            ),
            ScriptEvent(
              text: '{away} 선수도 뮤탈 편대 완성! 스커지도 섞습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 5, awayResource: -20,
            ),
            ScriptEvent(
              text: '{home}, 뮤탈 집중 사격! 상대 뮤탈을 노립니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -5, homeArmy: -3,              altText: '{home} 선수 뮤탈 컨트롤! 효율적인 교환!',
            ),
            ScriptEvent(
              text: '{home}, 드론을 물어뜯으면서 압박합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -10,            ),
          ],
        ),
        // 분기 B: 어웨이 뮤탈 컨트롤 우위 (공격형)
        ScriptBranch(
          id: 'away_mutal_wins',
          baseProbability: 0.6,
          conditionStat: 'control',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{home} 선수 뮤탈리스크가 나옵니다! 스커지도 섞습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 5, homeResource: -20,
            ),
            ScriptEvent(
              text: '{away} 선수도 뮤탈 편대 완성! 스커지도 섞습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 5, awayResource: -20,
            ),
            ScriptEvent(
              text: '{away}, 스커지로 뮤탈을 격추합니다! 동반 추락!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -5, awayArmy: -3,              altText: '{away} 선수 스커지 자폭! 뮤탈을 잡습니다!',
            ),
            ScriptEvent(
              text: '{away}, 드론을 물어뜯으면서 압박합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -10,            ),
          ],
        ),
        // 분기 C: 홈 스포어 수비형 (에볼루션 챔버 + 스포어)
        ScriptBranch(
          id: 'home_spore_defense',
          baseProbability: 0.4,
          conditionStat: 'defense',
          events: [
            ScriptEvent(
              text: '{home} 선수 뮤탈리스크가 나옵니다! 에볼루션 챔버에 스포어까지! 수비적인 선택!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 5, homeResource: -25,
            ),
            ScriptEvent(
              text: '{away} 선수도 뮤탈 편대 완성! 스커지도 섞습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 5, awayResource: -20,
            ),
            ScriptEvent(
              text: '{home}, 스포어가 상대 뮤탈을 견제합니다! 안정적인 수비!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -3,              altText: '{home} 선수 스포어 수비! 뮤탈 피해를 줄입니다!',
            ),
            ScriptEvent(
              text: '{home}, 뮤탈로 상대 드론을 물어뜯습니다! 드론 투자한 만큼 견제로 회수!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -10,            ),
          ],
        ),
        // 분기 D: 어웨이 스포어 수비형 (에볼루션 챔버 + 스포어)
        ScriptBranch(
          id: 'away_spore_defense',
          baseProbability: 0.4,
          conditionStat: 'defense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{home} 선수 뮤탈리스크가 나옵니다! 스커지도 섞습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 5, homeResource: -20,
            ),
            ScriptEvent(
              text: '{away} 선수도 뮤탈 편대 완성! 에볼루션 챔버에 스포어까지! 수비적인 선택!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 5, awayResource: -25,
            ),
            ScriptEvent(
              text: '{away}, 스포어가 상대 뮤탈을 견제합니다! 안정적인 수비!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -3,              altText: '{away} 선수 스포어 수비! 뮤탈 피해를 줄입니다!',
            ),
            ScriptEvent(
              text: '{away}, 뮤탈로 상대 드론을 물어뜯습니다! 드론 투자한 만큼 견제로 회수!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -10,            ),
          ],
        ),
      ],
    ),
    // Phase 5: 결전 - 분기
    ScriptPhase(
      name: 'decisive_battle',
      branches: [
        // 분기 A: 홈 뮤탈 견제 승리
        ScriptBranch(
          id: 'home_decisive_win',
          baseProbability: 1.0,
          conditionStat: 'control',
          events: [
            ScriptEvent(
              text: '뮤탈 소모전! 여기서 승부가 갈립니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{home}, 뮤탈로 상대 드론을 견제합니다! 효율적인 교환!',
              owner: LogOwner.home,
              homeResource: 0,
              homeArmy: 5, awayArmy: -5, awayResource: -15,              altText: '{home} 선수 드론 견제! 자원 차이를 벌립니다!',
            ),
            ScriptEvent(
              text: '{home}, 뮤탈 수 차이로 제공권 장악!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 3, awayArmy: -5,            ),
            ScriptEvent(
              text: '누적된 드론 차이가 결정적! {home} 선수 뮤탈 물량으로 밀어붙입니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기 B: 어웨이 뮤탈 견제 승리
        ScriptBranch(
          id: 'away_decisive_win',
          baseProbability: 1.0,
          conditionStat: 'control',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '뮤탈 소모전! 여기서 승부가 갈립니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{away}, 뮤탈로 상대 드론을 견제합니다! 효율적인 교환!',
              owner: LogOwner.away,
              awayResource: 0,
              awayArmy: 5, homeArmy: -5, homeResource: -15,              altText: '{away} 선수 드론 견제! 자원 차이를 벌립니다!',
            ),
            ScriptEvent(
              text: '{away}, 뮤탈 수 차이로 제공권 장악!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 3, homeArmy: -5,            ),
            ScriptEvent(
              text: '누적된 드론 차이가 결정적! {away} 선수 뮤탈 물량으로 밀어붙입니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기 C: 홈 역전 (스커지 회피 + 스커지 적중)
        ScriptBranch(
          id: 'home_comeback',
          baseProbability: 0.05,
          conditionStat: 'control',
          events: [
            ScriptEvent(
              text: '밀리던 {home} 선수! 뮤탈 컨트롤로 상대 스커지를 전부 떨쳐냅니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: 2,
              altText: '{home} 선수 불리한 상황! 하지만 뮤탈 컨트롤이 살아있습니다!',
            ),
            ScriptEvent(
              text: '상대 스커지가 빗나갑니다! {home} 선수 뮤탈이 살아남았습니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{home} 선수 스커지는 정확히 적중! 상대 뮤탈이 격추됩니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -8, homeArmy: -2,              altText: '{home} 선수 스커지 명중! 한 순간에 뮤탈 수가 뒤집어집니다!',
            ),
            ScriptEvent(
              text: '스커지 회피와 적중이 동시에! {home} 선수 기적같은 역전승!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -20,              decisive: true,
            ),
          ],
        ),
        // 분기 D: 어웨이 역전 (스커지 회피 + 스커지 적중)
        ScriptBranch(
          id: 'away_comeback',
          baseProbability: 0.05,
          conditionStat: 'control',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '밀리던 {away} 선수! 뮤탈 컨트롤로 상대 스커지를 전부 떨쳐냅니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: 2,
              altText: '{away} 선수 불리한 상황! 하지만 뮤탈 컨트롤이 살아있습니다!',
            ),
            ScriptEvent(
              text: '상대 스커지가 빗나갑니다! {away} 선수 뮤탈이 살아남았습니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{away} 선수 스커지는 정확히 적중! 상대 뮤탈이 격추됩니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -8, awayArmy: -2,              altText: '{away} 선수 스커지 명중! 한 순간에 뮤탈 수가 뒤집어집니다!',
            ),
            ScriptEvent(
              text: '스커지 회피와 적중이 동시에! {away} 선수 기적같은 역전승!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -20,              decisive: true,
            ),
          ],
        ),
        // 분기 E: 홈 저글링 서라운드 승리
        ScriptBranch(
          id: 'home_ling_surround',
          baseProbability: 0.6,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '뮤탈 소모전이 길어집니다! 양쪽 다 드론 피해가 쌓이고 있습니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{home} 선수 저글링을 대량으로 보충합니다! 뮤탈 견제 틈을 노립니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 8, homeResource: -15,            ),
            ScriptEvent(
              text: '{home} 선수 저글링 서라운드! 상대 본진까지 밀고 들어갑니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -5, homeArmy: -3,            ),
            ScriptEvent(
              text: '{home} 선수 뮤탈 견제와 저글링 서라운드 동시 공격! 막을 수가 없습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기 F: 어웨이 저글링 서라운드 승리
        ScriptBranch(
          id: 'away_ling_surround',
          baseProbability: 0.6,
          conditionStat: 'attack',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '뮤탈 소모전이 길어집니다! 양쪽 다 드론 피해가 쌓이고 있습니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '{away} 선수 저글링을 대량으로 보충합니다! 뮤탈 견제 틈을 노립니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 8, awayResource: -15,            ),
            ScriptEvent(
              text: '{away} 선수 저글링 서라운드! 상대 본진까지 밀고 들어갑니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -5, awayArmy: -3,            ),
            ScriptEvent(
              text: '{away} 선수 뮤탈 견제와 저글링 서라운드 동시 공격! 막을 수가 없습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기 G: 소모전 끝에 홈 승리 (장기전)
        ScriptBranch(
          id: 'home_long_game',
          baseProbability: 0.4,
          conditionStat: 'macro',
          events: [
            ScriptEvent(
              text: '뮤탈 소모전이 길어집니다! 양쪽 다 드론을 보충하면서 버팁니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 10, awayResource: 10,
            ),
            ScriptEvent(
              text: '{home} 선수 드론 보충이 빠릅니다! 뮤탈을 추가로 뽑습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: 0,
              homeArmy: 4, homeResource: -15,              altText: '{home}, 라바 차이! 뮤탈 추가 생산이 빠릅니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 드론 수가 점점 밀립니다! 뮤탈 보충이 느려지고 있습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -3,
            ),
            ScriptEvent(
              text: '미세한 자원 차이가 누적되면서 {home} 선수가 서서히 밀어붙입니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기 H: 소모전 끝에 어웨이 승리 (장기전)
        ScriptBranch(
          id: 'away_long_game',
          baseProbability: 0.4,
          conditionStat: 'macro',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '뮤탈 소모전이 길어집니다! 양쪽 다 드론을 보충하면서 버팁니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 10, awayResource: 10,
            ),
            ScriptEvent(
              text: '{away} 선수 드론 보충이 빠릅니다! 뮤탈을 추가로 뽑습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4, awayResource: -15,              altText: '{away}, 라바 차이! 뮤탈 추가 생산이 빠릅니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 드론 수가 점점 밀립니다! 뮤탈 보충이 느려지고 있습니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -3,
            ),
            ScriptEvent(
              text: '미세한 자원 차이가 누적되면서 {away} 선수가 서서히 밀어붙입니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
