part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 4풀 미러 (극초반 올인 미러)
// ----------------------------------------------------------
const _zvz4PoolMirror = ScenarioScript(
  id: 'zvz_4pool_mirror',
  matchup: 'ZvZ',
  homeBuildIds: ['zvz_4pool'],
  awayBuildIds: ['zvz_4pool'],
  description: '4풀 미러 극초반 저글링 대결',
  phases: [
    // Phase 0: 오프닝 (lines 1-10)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 드론 1기를 뽑고 더이상 드론을 생산하지 않는데요!',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: 0,
          altText: '{home} 선수, 5드론 이후에 드론이 추가되지 않습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 드론이 5개에서 멈춥니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '{away} 선수, 드론 1기를 뽑고 더이상 드론 생산을 하지 않습니다!',
        ),
        ScriptEvent(
          text: '쉽게 볼 수 없는 극 초반 빌드를 양쪽 모두 선택합니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '양 선수 모두 올인 빌드라고 볼 수 있는 공격적인 선택!',
        ),
        ScriptEvent(
          text: '{home} 선수 미네랄 200이 모이자마자 스포닝풀을 짓습니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -200,
          altText: '{home} 선수 드론 한 기를 빼 스포닝풀 건설합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 드론 한 마리를 빼서 스포닝풀 건설합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -200,
          altText: '{away} 선수 자원이 모이자마자 스포닝풀 짓기 시작합니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 저글링 6기 생산 시작합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 3,
          homeResource: -150,
          altText: '{home} 선수 스포닝풀 완성 되자마자 모아놨던 라바 3개를 저글링으로 선택합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 거의 비슷한 시간에 저글링 6기 생산 시작합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 3,
          awayResource: -150,
          altText: '{away} 선수, 거의 동시에 저글링 6기 누릅니다.',
        ),
        ScriptEvent(
          text: '각 저글링들이 어디서 만나게 될지도 중요한 부분입니다! 지켜보겠습니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: -50,
          awayResource: -50,
          skipChance: 0.3,
        ),
        ScriptEvent(
          text: '{home} 선수 상대방 진영 쪽으로 저글링 이동합니다.',
          owner: LogOwner.home,
          homeArmy: 1,
          awayArmy: 0,
          homeResource: -50,
          awayResource: 0,
          altText: '{home} 선수 상대방 쪽으로 저글링 움직입니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 저글링으로 상대방 진영을 찾아나섭니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 1,
          homeResource: 0,
          awayResource: -50,
          altText: '{away} 선수 저글링 움직임을 상대방 진영 쪽으로 가져갑니다.',
        ),
      ],
    ),
    // Phase 1: 저글링 교전 - 센터 vs 엇갈림 분기 (lines 9-30)
    ScriptPhase(
      name: 'ling_battle',
      recoveryArmyPerLine: 1,
      branches: [
        // ── 분기 A: 센터 교전 → 홈 컨트롤 승리 ──
        ScriptBranch(
          id: 'center_home_wins',
          description: '(phase1) 분기A - 센터 교전 홈 승',
          conditionStat: 'control+attack',
          events: [
            ScriptEvent(
              text: '양쪽 저글링 서로의 진영으로 이동 중 센터에서 마주합니다. 서로 빼지 않고 교전하는데요!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: -1,
              homeResource: -50,
              awayResource: -100,
            ),
            ScriptEvent(
              text: '{home} 선수의 저글링 컨트롤이 조금 더 앞서며 저글링 싸움에서 승리합니다!',
              owner: LogOwner.home,
              homeResource: -100,
              awayResource: -150,
              awayArmy: -2,
              homeArmy: -1,
              altText: '{home} 선수 저글링 싸움 승리하며 압박 이어갑니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링 싸움의 패배로 저글링 숫자 차이가 납니다!',
              owner: LogOwner.away,
              homeArmy: 1,
              homeResource: -100,
              awayResource: -150,
              awayArmy: -2,
              altText: '{away} 선수 저글링 싸움 대패하여 저글링 숫자에서 밀립니다!',
            ),
            ScriptEvent(
              text: '{home} 선수의 저글링이 {away} 선수의 본진까지 들어옵니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: -1,
              homeResource: 0,
              awayResource: -50,
              altText: '{home} 선수 저글링 상대방 본진 돌파, 드론을 공격합니다!',
            ),
            ScriptEvent(
              text: '같은 빌드 시작이지만 초반의 저글링 컨트롤이 승부를 가릅니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: -1,
              homeResource: 0,
              awayResource: -50,
              decisive: true,
            ),
          ],
        ),
        // ── 분기 B: 센터 교전 → 어웨이 컨트롤 승리 ──
        ScriptBranch(
          id: 'center_away_wins',
          description: '(phase1) 분기B - 센터 교전 어웨이 승',
          conditionStat: 'control+attack',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '양쪽 저글링 이동 중 센터에서 마주치고 양쪽 다 빼지 않고 싸웁니다!',
              owner: LogOwner.system,
              homeArmy: -1,
              awayArmy: 0,
              homeResource: -100,
              awayResource: -50,
            ),
            ScriptEvent(
              text: '{away} 선수, 저글링 컨트롤 차이! 상대 저글링을 잡아냅니다!',
              owner: LogOwner.away,
              homeResource: -150,
              awayResource: -50,
              homeArmy: -2,
              awayArmy: 0,
              altText: '{away} 선수 저글링 컨트롤! 압도적인 저글링 교환비!',
            ),
            ScriptEvent(
              text: '{home} 선수 저글링이 녹습니다! 저글링 숫자 차이가 나는데요!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: -150,
              awayResource: -50,
              homeArmy: -2,
              altText: '{home} 선수 저글링 싸움 대패! 추가 합류되는 저글링도 본진으로 밀립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 싸움을 이긴 저글링으로 상대방 본진으로 진격합니다!',
              owner: LogOwner.away,
              homeArmy: -2,
              awayArmy: 1,
              awayResource: -50,
              homeResource: -150,
              altText: '{away} 선수 저글링 상대방 본진 입성! 드론을 공격합니다!',
            ),
            ScriptEvent(
              text: '완벽하게 같은 빌드라 사소한 컨트롤 차이가 더 극명하게 갈렸습니다!',
              owner: LogOwner.away,
              homeArmy: 1,
              awayArmy: -2,
              homeResource: -50,
              awayResource: -100,
              decisive: true,
            ),
          ],
        ),
        // ── 분기 C: 엇갈림 → 홈 멀티태스킹 승리 ──
        ScriptBranch(
          id: 'cross_home_wins',
          description: '(phase1) 분기C - 엇갈림 홈 승',
          conditionStat: 'control+defense',
          events: [
            ScriptEvent(
              text: '저글링이 엇갈립니다! 서로의 본진으로 직행!',
              owner: LogOwner.system,
              homeArmy: 1,
              awayArmy: 1,
              homeResource: -50,
              awayResource: -50,
              altText: '양쪽 저글링이 서로를 지나칩니다! 각자 어떤 선택을 할까요?',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링이 {home} 선수 본진에 도착! 드론을 노립니다!',
              owner: LogOwner.away,
              homeArmy: -1,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -50,
              altText: '{away} 선수 저글링이 본진 침투! 드론이 위험합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 드론 뭉치기! 저글링을 감싸면서 추가 저글링도 나옵니다!',
              owner: LogOwner.home,
              homeArmy: 1,
              homeResource: -50,
              awayResource: -150,
              awayArmy: -2,
              altText: '{home} 선수, 드론 컨트롤로 저글링을 잡습니다! 추가 저글링까지 나오면서 수비 진행합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 본인 피해는 최소화하고 상대 본진 드론은 잡아줍니다!',
              owner: LogOwner.home,
              homeArmy: 1,
              awayArmy: -2,
              homeResource: -50,
              awayResource: -150,
              altText: '{home} 선수 저글링이 상대 본진에서 드론을 사냥합니다! 이기적인 교환이네요!',
            ),
            ScriptEvent(
              text: '{home} 선수 멀티태스킹 차이로 수비는 성공하고 상대방에게 피해는 입힙니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: -50,
              homeArmy: 2,
              awayResource: -100,
              altText: '{home} 선수, 양쪽 전선을 동시에 관리합니다! 피해 차이가 큽니다!',
            ),
            ScriptEvent(
              text: '멀티태스킹 차이가 승부를 갈랐습니다! {home} 선수 초반 컨트롤 싸움에서 승리를 거둡니다!',
              owner: LogOwner.home,
              homeArmy: 1,
              awayArmy: -1,
              homeResource: -50,
              awayResource: -100,
              decisive: true,
            ),
          ],
        ),
        // ── 분기 D: 엇갈림 → 어웨이 멀티태스킹 승리 ──
        ScriptBranch(
          id: 'cross_away_wins',
          description: '(phase1) 분기D - 엇갈림 어웨이 승',
          conditionStat: 'control+defense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '저글링이 엇갈리는데요! 각자 어떤 선택을할까요?',
              owner: LogOwner.system,
              homeArmy: 1,
              awayArmy: 1,
              homeResource: -50,
              awayResource: -50,
              altText: '양쪽 저글링이 엇갈려 서로의 본진으로 향합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 저글링이 상대방 본진 도착! 드론 피해를 입힐 수 있을까요!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: -1,
              homeResource: 0,
              awayResource: -50,
              altText: '{home} 선수 저글링이 {away} 선수의 본진에 침투했습니다! 상대방 드론을 노립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 드론을 뭉치며 드론을 뭉쳐서 저글링 수비를 합니다. 추가 저글링도 나오며 수비를 돕는데요!',
              owner: LogOwner.away,
              awayArmy: 1,
              homeResource: -150,
              awayResource: -50,
              homeArmy: -2,
              altText: '{away} 선수, 드론 뭉치기로 저글링을 잡습니다. 추가 저글링 합류로 수비가 됩니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 수비와 함께 본인 저글링은 상대방 드론을 괴롭힙니다!',
              owner: LogOwner.away,
              homeArmy: -2,
              awayArmy: 1,
              awayResource: -50,
              homeResource: -150,
              altText: '{away} 선수 이기적인 컨트롤로 본인은 수비하고, 상대방 드론은 잡아줍니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 멀티태스킹 차이를 보여주며 격차를 벌립니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayResource: -50,
              awayArmy: 2,
              homeResource: -100,
              altText: '{away} 선수 뛰어난 화면전환과 컨트롤로 초반 같은 빌드지만 큰 피해를 입힙니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 계속해서 저글링을 상대방 본진으로 합류시키며 승기를 굳힙니다!',
              owner: LogOwner.away,
              homeArmy: -1,
              awayArmy: 1,
              homeResource: -100,
              awayResource: -50,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
