part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 4풀 미러 (극초반 올인 미러)
// ----------------------------------------------------------
const _zvz4PoolMirror = ScenarioScript(
  id: 'zvz_4pool_mirror',
  matchup: 'ZvZ',
  homeBuildIds: ['zvz_4pool'],
  awayBuildIds: ['zvz_4pool'],
  description: '4드론 미러 극초반 저글링 대결',
  phases: [
    // Phase 0: 오프닝
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 드론 1기를 뽑고 더이상 드론을 생산하지 않는데요!',
          owner: LogOwner.home,
          homeArmy: 1,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -50,
          altText: '{home} 선수, 5드론 이후에 드론이 추가되지 않습니다!',
        ),
        ScriptEvent(
          text: '{away} 선수 드론이 5개에서 멈춥니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 1,
          homeResource: 0,
          awayResource: -50,
          altText: '{away} 선수, 드론 1기를 뽑고 더이상 드론 생산을 하지 않습니다!',
        ),
        ScriptEvent(
          text: '쉽게 볼 수 없는 극 초반 빌드를 양쪽 모두 선택합니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 0,
          altText: '양 선수 모두 올인 빌드라고 볼 수 있는 공격적인 선택!',
        ),
        ScriptEvent(
          text: '{home} 선수 미네랄 200이 모이자마자 스포닝풀을 짓습니다.',
          owner: LogOwner.home,
          homeArmy: -1,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -200,
          altText: '{home} 선수 드론 한 기를 빼 스포닝풀 건설합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 드론 한 마리를 빼서 스포닝풀 건설합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: -1,
          homeResource: 0,
          awayResource: -200,
          altText: '{away} 선수 자원이 모이자마자 스포닝풀 짓기 시작합니다.',
        ),
        ScriptEvent(
          text: '{home} 선수 저글링 6기 생산 시작합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 6,
          homeResource: -150,
          altText: '{home} 선수 스포닝풀 완성 되자마자 모아놨던 라바 3개를 저글링으로 선택합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수도 거의 비슷한 시간에 저글링 6기 생산 시작합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 6,
          awayResource: -150,
          altText: '{away} 선수, 거의 동시에 저글링 6기 누릅니다.',
        ),
        ScriptEvent(
          text: '각 저글링들이 어디서 만나게 될지도 중요한 부분입니다! 지켜보겠습니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: -50,
          awayResource: -50,
          altText: '초반 움직임에 따라 허무하게 끝날 수도 있는 상황입니다! 지켜보시죠.',
        ),
      ],
    ),
    // Phase 1: 저글링 교전 - 센터 vs 엇갈림 분기
    ScriptPhase(
      name: 'first_phase',
      branches: [
        // ── 분기 A: 센터 교전 → 홈 컨트롤 승리 ──
        ScriptBranch(
          id: 'center_home_wins',
          conditionStat: 'control+attack',
          events: [
            ScriptEvent(
              text: '{home}, 저글링이 센터에서 마주칩니다! 수가 같습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: -50,
              awayResource: -50,
              altText: '{home} 선수 저글링 교전! 컨트롤이 전부입니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링도 맞붙습니다! 드론 수가 적어서 이게 전부예요!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away}, 저글링 맞대결! 한 기 차이가 승패를 가릅니다!',
            ),
            ScriptEvent(
              text: '저글링 컨트롤이 곧 승패입니다! 컨트롤 싸움이 중요하겠습니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
            ),
            ScriptEvent(
              text: '{home}, 저글링 컨트롤 차이! 상대 저글링을 잡아냅니다!',
              owner: LogOwner.home,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -4,
              homeArmy: -2,
              altText: '{home} 선수 저글링 컨트롤! 효율적인 교환!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링이 녹습니다! 드론으로 막아야 합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -2,
            ),
            ScriptEvent(
              text: '{home}, 남은 저글링으로 드론을 물어뜯습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -15,
              altText: '{home} 선수 저글링 돌파! 드론을 공격합니다!',
            ),
            ScriptEvent(
              text: '저글링 컨트롤 차이가 승부를 갈랐습니다! 저글링 싸움 승리를 거둡니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // ── 분기 B: 센터 교전 → 어웨이 컨트롤 승리 ──
        ScriptBranch(
          id: 'center_away_wins',
          conditionStat: 'control+attack',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{home}, 저글링이 센터에서 마주칩니다! 수가 같습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{home} 선수 저글링 교전! 컨트롤이 전부입니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링도 맞붙습니다! 한 기 차이가 승패를 가릅니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '{away}, 저글링 맞대결! 드론 수가 적어서 이게 전부예요!',
            ),
            ScriptEvent(
              text: '저글링 컨트롤이 곧 승패입니다! 컨트롤 싸움이 중요하겠습니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
            ),
            ScriptEvent(
              text: '{away}, 저글링 컨트롤 차이! 상대 저글링을 잡아냅니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -4,
              awayArmy: -2,
              altText: '{away} 선수 저글링 컨트롤! 효율적인 교환!',
            ),
            ScriptEvent(
              text: '{home} 선수 저글링이 녹습니다! 드론으로 막아야 합니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -2,
            ),
            ScriptEvent(
              text: '{away}, 남은 저글링으로 드론을 물어뜯습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -15,
              altText: '{away} 선수 저글링 돌파! 드론을 공격합니다!',
            ),
            ScriptEvent(
              text: '저글링 컨트롤 차이가 승부를 갈랐습니다! 저글링 싸움 승리를 거둡니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // ── 분기 C: 엇갈림 → 홈 멀티태스킹 승리 ──
        ScriptBranch(
          id: 'cross_home_wins',
          conditionStat: 'control+sense',
          events: [
            ScriptEvent(
              text: '저글링이 엇갈립니다! 서로의 본진으로 직행!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '양쪽 저글링이 서로를 지나칩니다! 본진 급습!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링이 {home} 본진에 도착! 드론을 노립니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -10,
              altText: '{away} 저글링이 본진 침투! 드론이 위험합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 드론 뭉치기! 저글링을 감싸면서 추가 저글링도 합류!',
              owner: LogOwner.home,
              homeArmy: 0,
              homeResource: 0,
              awayResource: 0,
              awayArmy: -3,
              altText: '{home}, 드론으로 저글링을 잡습니다! 추가 저글링까지!',
            ),
            ScriptEvent(
              text: '{home} 선수 저글링이 상대 본진 드론을 물어뜯습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -15,
              altText: '{home} 저글링이 상대 본진에서 드론을 사냥합니다!',
            ),
            ScriptEvent(
              text: '양쪽 본진에서 동시에 싸움! 멀티태스킹 승부!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
            ),
            ScriptEvent(
              text: '{home} 선수 본진 수비하면서 상대 드론까지 잡아냅니다! 멀티태스킹 차이!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              homeArmy: 2,
              awayResource: -10,
              altText: '{home}, 양쪽 전선을 동시에 관리합니다! 컨트롤의 차이!',
            ),
            ScriptEvent(
              text: '멀티태스킹 차이가 승부를 갈랐습니다! 저글링 싸움 승리를 거둡니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // ── 분기 D: 엇갈림 → 어웨이 멀티태스킹 승리 ──
        ScriptBranch(
          id: 'cross_away_wins',
          conditionStat: 'control+sense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '저글링이 엇갈립니다! 서로의 본진으로 직행!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              altText: '양쪽 저글링이 서로를 지나칩니다! 본진 급습!',
            ),
            ScriptEvent(
              text: '{home} 선수 저글링이 {away} 본진에 도착! 드론을 노립니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -10,
              altText: '{home} 저글링이 본진 침투! 드론이 위험합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 드론 뭉치기! 저글링을 감싸면서 추가 저글링도 합류!',
              owner: LogOwner.away,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              homeArmy: -3,
              altText: '{away}, 드론으로 저글링을 잡습니다! 추가 저글링까지!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링이 상대 본진 드론을 물어뜯습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -15,
              altText: '{away} 저글링이 상대 본진에서 드론을 사냥합니다!',
            ),
            ScriptEvent(
              text: '양쪽 본진에서 동시에 싸움! 멀티태스킹 승부!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              skipChance: 0.3,
            ),
            ScriptEvent(
              text: '{away} 선수 본진 수비하면서 상대 드론까지 잡아냅니다! 멀티태스킹 차이!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayResource: 0,
              awayArmy: 2,
              homeResource: -10,
              altText: '{away}, 양쪽 전선을 동시에 관리합니다! 컨트롤의 차이!',
            ),
            ScriptEvent(
              text: '멀티태스킹 차이가 승부를 갈랐습니다! 저글링 싸움 승리를 거둡니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
