part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 4풀 vs 9오버풀 (치즈 vs 준스탠다드)
// ----------------------------------------------------------
const _zvz4PoolVs9overpool = ScenarioScript(
  id: 'zvz_4pool_vs_9overpool',
  matchup: 'ZvZ',
  homeBuildIds: ['zvz_4pool'],
  awayBuildIds: ['zvz_9overpool'],
  description: '4풀 치즈 vs 9오버풀',
  phases: [
    // Phase 0: 오프닝 (lines 1-10)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 드론 한 기를 뽑고 더이상 드론을 생산하지 않는데요!',
          altText: '{home} 선수, 5드론 이후에 드론이 추가되지 않습니다!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수 드론을 뽑으면서 9드론에 오버로드를 먼저 올립니다.',
          altText: '{away} 선수, 9드론에 오버로드를 먼저 올리고 스포닝풀로 이어갑니다!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: -100,
        ),
        ScriptEvent(
          owner: LogOwner.system,
          text: '드론을 뽑지 않고 있습니다! 극초반 올인 빌드가 나왔네요!',
          altText: '5드론에서 멈추고 스포닝풀부터 올리는데요! 오버로드를 먼저 올린 상대에게 위험합니다!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 미네랄이 모이자마자 스포닝풀을 건설합니다.',
          altText: '{home} 선수 드론 한 기를 빼서 스포닝풀 건설합니다.',
          homeArmy: 0,
          homeResource: -200,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 스포닝풀 완성! 저글링 6기 생산 시작합니다!',
          altText: '{home} 선수, 라바 3개를 모두 저글링으로! 상대 진영으로 출발합니다!',
          homeArmy: 3,
          homeResource: -150,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수 오버로드 후 스포닝풀! 오버로드를 먼저 올려서 풀이 더 늦습니다!',
          altText: '{away} 선수, 오버로드를 먼저 올렸기 때문에 스포닝풀이 더 늦어요!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: -200,
        ),
        ScriptEvent(
          owner: LogOwner.system,
          text: '스포닝풀이 아주 빨리 올라갔는데 상대는 오버로드를 먼저 올린 만큼 풀이 더 늦습니다!',
          altText: '오버로드를 먼저 올리는 빌드라 이렇게 빠른 스포닝풀에 가장 취약합니다!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: 0,
          skipChance: 0.3,
        ),
      ],
    ),
    // Phase 1: 4풀 저글링 도착 (lines 8-12)
    ScriptPhase(
      name: 'ling_rush',
      linearEvents: [
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 저글링이 도착합니다! 상대 풀이 아직 완성 안 됐습니다!',
          altText: '{home} 선수, 저글링 도착! 오버로드를 먼저 올려서 풀이 더 늦어요!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수 드론으로 막아야 합니다! 저글링이 한참 남았습니다!',
          altText: '{away} 선수, 스포닝풀이 아직 멀었습니다! 드론으로 버텨야 해요!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 3,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.system,
          text: '오버로드를 먼저 올린 대가를 치르고 있습니다!',
          altText: '풀 완성까지 드론으로 버텨야 하는 상황! 드론 컨트롤이 관건!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: 0,
          skipChance: 0.3,
        ),
      ],
    ),
    // Phase 2: 교전 결과 - 분기 (lines 13-24)
    ScriptPhase(
      name: 'rush_result',
      branches: [
        // 분기 A: 4풀 올인 성공
        ScriptBranch(
          id: 'pool_crushes',
          description: '(phase2) 분기A - 4풀 올인 성공',
          baseProbability: 0.3,
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 저글링이 드론을 물어뜯습니다! 풀이 너무 늦었습니다!',
              altText: '{home} 선수, 저글링 돌파! 드론이 녹고 있습니다!',
              homeArmy: 1,
              homeResource: 0,
              awayArmy: -3,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 드론 손실이 심각합니다! 풀이 아직 멀었습니다!',
              altText: '{away} 선수, 드론이 빠르게 줄어듭니다! 스포닝풀이 아직 안 됐어요!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 추가 저글링 합류! 오버로드 먼저 올린 약점을 정확히 찔렀습니다!',
              altText: '{home} 선수, 저글링이 계속 들어갑니다! 남은 드론까지 추격!',
              homeArmy: 2,
              homeResource: -100,
              awayArmy: 0,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '극초반 저글링 올인이 성공합니다! 오버로드를 먼저 올린 대가가 컸습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기 B: 드론 컨트롤로 버팀
        ScriptBranch(
          id: 'drone_holds',
          description: '(phase2) 분기B - 드론 수비 버팀',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 드론을 뭉쳐서 저글링과 교전합니다! 필사적인 수비!',
              altText: '{away} 선수, 드론 컨트롤! 저글링을 하나씩 잡습니다!',
              homeArmy: -3,
              homeResource: 0,
              awayArmy: -1,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 저글링이 드론에 당하고 있습니다!',
              altText: '{home} 선수, 초반 저글링이 밀립니다! 드론 물량에 막히고 있어요!',
              homeArmy: -2,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 스포닝풀이 완성됩니다! 저글링 생산 시작!',
              altText: '{away} 선수, 풀 완성! 저글링으로 반격합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 5,
              awayResource: -250,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '초반 저글링 러시를 막아냈습니다! 드론 수 이점이 살아있습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
