part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 9. 9오버풀 미러 (준스탠다드 미러)

// 9오버풀 미러전
//  오프닝 : 9개 드론 생산, 오버로드 생산, 스포닝풀 건설 까지
//
// phase1 (추가 해처리 페이즈) - 앞마당 선택은 과감한 선택임
// 	분기1-A : home 앞마당 해처리 / away 본진 해처리 후 다음 페이즈			(macro+defense)
// 	분기1-B : away 앞마당 해처리 / home 본진 해처리 후 다음 페이즈			(macro+defense)
//
// phase2 (저글링 싸움 페이즈)
// 	분기2-A : away 저글링 싸움 승리 후 home 앞마당 해처리 취소 or 파괴 > away 승 (attack) [선행 : 분기1-A]
// 	분기2-B : 저글링 교전이 진행되지만 home 이 앞마당 수비 성공 후 양쪽 레어 선택 후 다음 페이즈  [선행 : 분기1-A]
// 								- away 저글링이 home의 본진/앞마당 양갈래 피해 입히는 시도를 하고 드론 2기 제거 (skipChance)
// 	분기2-C : 저글링 교전이 진행되지만 away 이 앞마당 수비 성공 후 양쪽 레어 선택 후 다음 페이즈  [선행 : 분기1-B]
// 								- home 저글링이 away의 본진/앞마당 양갈래 피해 입히는 시도를 하고 드론 2기 제거 (skipChance)
// 	분기2-D : home 저글링 싸움 승리 후 away 앞마당 해처리 취소 or 파괴 > home 승 (attack) [선행 : 분기1-B]
//
// phase3 (뮤탈 싸움 페이즈)
// 	분기3-A : home 앞마당, 본진에 스포어 건설하며 수비적 운영하며 본인은 뮤탈,스커지 컨트롤에만 신경쓰며 뮤탈 싸움 승리 > home 승 [선행 : 분기2-B]
// 									- away의 저글링이 앞마당 스포어를 건드리며 신경쓰이게 하지만 뮤탈로 쉽게 수비 (skipChance)
// 									- home의 저글링이 상대방 본진을 건드리며 상대방 뮤탈 병력 휘두르기 (skipChance)
// 	분기3-B : away가 home의 앞마당, 본진을 뮤탈과 저글링으로 번갈아가며 괴롭히며 병력을 휘두르다가 뮤탈 한방 싸움 승리 > away 승 [선행 : 분기2-B]
// 	분기3-C : away 앞마당, 본진에 스포어 건설하며 수비적 운영하며 본인은 뮤탈,스커지 컨트롤에만 신경쓰며 뮤탈 싸움 승리 > away 승 [선행 : 분기2-C]
// 									- home의 저글링이 앞마당 스포어를 건드리며 신경쓰이게 하지만 뮤탈로 쉽게 수비 (skipChance)
// 									- away의 저글링이 상대방 본진을 건드리며 상대방 뮤탈 병력 휘두르기 (skipChance)
// 	분기3-D : home가 away의 앞마당, 본진을 뮤탈과 저글링으로 번갈아가며 괴롭히며 병력을 휘두르다가 뮤탈 한방 싸움 승리 > home 승 [선행 : 분기2-C]
//
//
// ----------------------------------------------------------
const _zvz9overpoolMirror = ScenarioScript(
  id: 'zvz_9overpool_mirror',
  matchup: 'ZvZ',
  homeBuildIds: ['zvz_9overpool'],
  awayBuildIds: ['zvz_9overpool'],
  description: '9오버풀 미러 대결',
  phases: [
    // ── Phase 0: 오프닝 ──
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 드론을 9개까지 뽑습니다.',
          altText: '{home} 선수, 9드론까지 생산합니다.',
          homeArmy: 0,
          homeResource: 200,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수도 드론 9개까지 찍습니다.',
          altText: '{away} 선수, 9드론까지 생산합니다.',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: 200,
        ),
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 9드론에 오버로드를 올립니다!',
          altText: '{home} 선수, 9드론에 오버로드 생산!',
          homeArmy: 0,
          homeResource: -100,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 스포닝풀 건설!',
          altText: '{home} 선수, 오버로드에 이어 스포닝풀을 올립니다!',
          homeArmy: 0,
          homeResource: -200,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수도 오버로드 생산!',
          altText: '{away} 선수, 역시 9드론에 오버로드!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: -100,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수도 스포닝풀!',
          altText: '{away} 선수 스포닝풀 건설! 드론 수가 같습니다!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: -200,
        ),
        ScriptEvent(
          owner: LogOwner.system,
          text: '양쪽 다 9오버풀! 드론 수도 동일합니다!',
          altText: '양쪽 빌드가 같습니다! 미세한 컨트롤 차이가 승부를 가릅니다!',
          homeArmy: 0,
          homeResource: 150,
          awayArmy: 0,
          awayResource: 150,
        ),
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 저글링 생산과 발업 연구 시작!',
          altText: '{home} 선수, 저글링을 뽑으면서 발업까지 돌립니다!',
          homeArmy: 2,
          homeResource: -300,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수도 저글링과 발업!',
          altText: '{away} 선수도 저글링 생산! 발업도 같이 돌립니다!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2,
          awayResource: -300,
        ),
      ],
    ),

    // ── Phase 1: 앞마당 선택 ──
    ScriptPhase(
      name: 'expansion_choice',
      branches: [
        ScriptBranch(
          id: 'home_expand',
          description: '(phase1) 분기A - 홈 앞마당 확장',
          baseProbability: 0.5,
          conditionStat: 'macro+defense',
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 저글링을 앞에 세우고 앞마당 해처리를 건설합니다! 과감한 선택!',
              altText: '{home} 선수 앞마당 건설! 저글링으로 입구를 막으면서 확장합니다!',
              homeArmy: 0,
              homeResource: -300,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수는 본진에 해처리를 추가합니다. 안정적인 선택!',
              altText: '{away} 선수, 본진 해처리 추가! 안전하게 갑니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -300,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '앞마당을 올린 {home} 선수! 가스를 두 곳에서 캘 수 있지만 위험합니다!',
              altText: '{home} 선수 앞마당! 가스가 두 배지만 저글링 공격에 취약합니다!',
              homeArmy: 0,
              homeResource: 200,
              awayArmy: 0,
              awayResource: 200,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '저글링이 앞마당 주변을 어슬렁거립니다! 긴장되는 순간!',
              altText: '앞마당을 올린 쪽이 위험한 타이밍! 저글링 수가 중요합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              skipChance: 0.3,
            ),
          ],
        ),
        ScriptBranch(
          id: 'away_expand',
          description: '(phase1) 분기B - 어웨이 앞마당 확장',
          baseProbability: 0.5,
          conditionStat: 'macro+defense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 저글링을 앞에 세우고 앞마당 해처리를 건설합니다! 과감한 선택!',
              altText: '{away} 선수 앞마당 건설! 저글링으로 입구를 막으면서 확장합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -300,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수는 본진에 해처리를 추가합니다. 안정적인 선택!',
              altText: '{home} 선수, 본진 해처리 추가! 안전하게 갑니다!',
              homeArmy: 0,
              homeResource: -300,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '앞마당을 올린 {away} 선수! 가스를 두 곳에서 캘 수 있지만 위험합니다!',
              altText: '{away} 선수 앞마당! 가스가 두 배지만 저글링 공격에 취약합니다!',
              homeArmy: 0,
              homeResource: 200,
              awayArmy: 0,
              awayResource: 200,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '저글링이 앞마당 주변을 어슬렁거립니다! 긴장되는 순간!',
              altText: '앞마당을 올린 쪽이 위험한 타이밍! 저글링 수가 중요합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              skipChance: 0.3,
            ),
          ],
        ),
      ],
    ),

    // ── Phase 2: 저글링 싸움 ──
    ScriptPhase(
      name: 'ling_fight',
      recoveryArmyPerLine: 1,
      branches: [
        // 분기 A: away 저글링 승 → home 앞마당 파괴 > away 승
        ScriptBranch(
          id: 'ling_away_win',
          description: '(phase2) 분기A - 저글링 어웨이 승',
          conditionStat: 'attack',
          homeStatMustBeHigher: false,
          baseProbability: 0.5,
          conditionPriorBranchIds: ['home_expand'],
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 저글링을 계속 뽑습니다! 물량이 쌓입니다!',
              altText: '{away} 선수 저글링 추가 생산! 앞마당을 노리고 있습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 발업 저글링으로 앞마당을 급습합니다!',
              altText: '{away} 선수 저글링이 앞마당으로 돌진합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '성큰이 완성되기 전입니다! 타이밍이 절묘합니다!',
              altText: '성큰 완성 전! 이 타이밍을 노렸습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              skipChance: 0.4,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 저글링이 막아보지만 수가 부족합니다!',
              altText: '{home} 선수 드론까지 동원해서 막아보지만 밀립니다!',
              homeArmy: -2,
              homeResource: -100,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 저글링이 앞마당 해처리를 부숩니다!',
              altText: '{away} 선수, 앞마당 해처리 파괴!',
              homeArmy: 0,
              homeResource: -200,
              awayArmy: -1,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 해처리가 무너졌습니다! 피해가 막심합니다!',
              altText: '{home} 선수 앞마당이 무너집니다! 드론 피해도 심각합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 드론까지 물어뜯습니다! 피해가 큽니다!',
              altText: '{away} 선수, 남은 저글링이 드론을 잡아냅니다!',
              homeArmy: -1,
              homeResource: -100,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '앞마당을 잃은 {home} 선수! 자원 차이가 너무 큽니다!',
              altText: '앞마당 투자가 전부 날아갔습니다! {home} 선수 회복이 불가능합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),

        // 분기 B: home 앞마당 수비 성공 → 레어 + 스파이어
        ScriptBranch(
          id: 'ling_defend_home',
          description: '(phase2) 분기B - 홈 앞마당 수비',
          conditionStat: 'defense+sense',
          baseProbability: 0.5,
          conditionPriorBranchIds: ['home_expand'],
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 저글링으로 앞마당을 노립니다!',
              altText: '{away} 선수 저글링이 앞마당 쪽으로 움직입니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 1,
              awayResource: -50,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 저글링과 성큰으로 앞마당을 지켜냅니다! 수비 성공!',
              altText: '{home} 선수 성큰이 제때 완성됩니다! 앞마당 수비 성공!',
              homeArmy: 1,
              homeResource: -75,
              awayArmy: -2,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 에볼루션 챔버도 건설합니다!',
              altText: '{home} 선수 챔버까지 올립니다! 스포어를 준비합니다!',
              homeArmy: 0,
              homeResource: -50,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 소수 저글링이 본진 침투! 드론을 물어뜯습니다!',
              altText: '{away} 선수, 앞마당은 못 뚫었지만 본진 드론 2기를 잡아냅니다!',
              homeArmy: 0,
              homeResource: -100,
              awayArmy: -1,
              awayResource: 0,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 드론을 보충합니다! 앞마당 자원이 돌기 시작합니다!',
              altText: '{home} 선수 드론 보충! 앞마당에서 자원이 들어옵니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              skipChance: 0.4,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 앞마당 가스까지 확보! 레어 진화를 시작합니다!',
              altText: '{home} 선수, 가스 두 곳에서 캡니다! 레어 진화!',
              homeArmy: 0,
              homeResource: -250,
              awayArmy: 0,
              awayResource: 0,
              homeExpansion: true,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수도 레어 진화! 본진 가스 하나로 버팁니다!',
              altText: '{away} 선수 레어! 가스가 하나라 병력 구성에서 벅찰 수 있습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -250,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 레어 완성! 스파이어를 바로 올립니다!',
              altText: '{home} 선수 스파이어 건설! 가스 수급이 빨라 타이밍이 앞섭니다!',
              homeArmy: 2,
              homeResource: -350,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수도 스파이어! 타이밍이 약간 늦습니다!',
              altText: '{away} 선수 스파이어 건설! 가스 하나로 따라가고 있습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -350,
            ),
          ],
        ),

        // 분기 C: away 앞마당 수비 성공 → 레어 + 스파이어
        ScriptBranch(
          id: 'ling_defend_away',
          description: '(phase2) 분기C - 어웨이 앞마당 수비',
          conditionStat: 'defense+sense',
          homeStatMustBeHigher: false,
          baseProbability: 0.5,
          conditionPriorBranchIds: ['away_expand'],
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 저글링으로 앞마당을 노립니다!',
              altText: '{home} 선수 저글링이 앞마당 쪽으로 움직입니다!',
              homeArmy: 1,
              homeResource: -50,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 저글링과 성큰으로 앞마당을 지켜냅니다! 수비 성공!',
              altText: '{away} 선수 성큰이 제때 완성됩니다! 앞마당 수비 성공!',
              homeArmy: -2,
              homeResource: 0,
              awayArmy: 1,
              awayResource: -75,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 에볼루션 챔버도 건설합니다!',
              altText: '{away} 선수 챔버까지 올립니다! 스포어를 준비합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -50,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 소수 저글링이 본진 침투! 드론을 물어뜯습니다!',
              altText: '{home} 선수, 앞마당은 못 뚫었지만 본진 드론 2기를 잡아냅니다!',
              homeArmy: -1,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -100,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 드론을 보충합니다! 앞마당 자원이 돌기 시작합니다!',
              altText: '{away} 선수 드론 보충! 앞마당에서 자원이 들어옵니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              skipChance: 0.4,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 앞마당 가스까지 확보! 레어 진화를 시작합니다!',
              altText: '{away} 선수, 가스 두 곳에서 캡니다! 레어 진화!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -250,
              awayExpansion: true,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수도 레어 진화! 본진 가스 하나로 버팁니다!',
              altText: '{home} 선수 레어! 가스가 하나라 상대방 병력 조합이 벅찰 수 있습니다!',
              homeArmy: 0,
              homeResource: -250,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 레어 완성! 스파이어를 바로 올립니다!',
              altText: '{away} 선수 스파이어 건설! 가스 수급이 빨라 타이밍이 앞섭니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 2,
              awayResource: -350,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수도 스파이어! 타이밍이 약간 늦습니다!',
              altText: '{home} 선수 스파이어 건설! 가스 하나로 따라가고 있습니다!',
              homeArmy: 0,
              homeResource: -350,
              awayArmy: 0,
              awayResource: 0,
            ),
          ],
        ),

        // 분기 D: home 저글링 승 → away 앞마당 파괴 > home 승
        ScriptBranch(
          id: 'ling_home_win',
          description: '(phase2) 분기D - 저글링 홈 승',
          conditionStat: 'attack',
          baseProbability: 0.5,
          conditionPriorBranchIds: ['away_expand'],
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 저글링을 계속 뽑습니다! 물량이 쌓입니다!',
              altText: '{home} 선수 저글링 추가 생산! 앞마당을 노리고 있습니다!',
              homeArmy: 2,
              homeResource: -100,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 발업 저글링으로 앞마당을 급습합니다!',
              altText: '{home} 선수 저글링이 앞마당으로 돌진합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '성큰이 완성되기 전입니다! 타이밍이 절묘합니다!',
              altText: '성큰 완성 전! 이 타이밍을 노렸습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              skipChance: 0.4,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 저글링이 막아보지만 수가 부족합니다!',
              altText: '{away} 선수 드론까지 동원해서 막아보지만 밀립니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -2,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 저글링이 앞마당 해처리를 부숩니다!',
              altText: '{home} 선수, 앞마당 해처리 파괴!',
              homeArmy: -1,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 해처리가 무너졌습니다! 피해가 막심합니다!',
              altText: '{away} 선수 앞마당이 무너집니다! 드론 피해도 심각합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 드론까지 물어뜯습니다! 피해가 큽니다!',
              altText: '{home} 선수, 남은 저글링이 드론을 잡아냅니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -1,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '앞마당을 잃은 {away} 선수! 자원 차이가 너무 큽니다!',
              altText: '앞마당 투자가 전부 날아갔습니다! {away} 선수 회복이 불가능합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),

    // ── Phase 3: 뮤탈 싸움 ──
    ScriptPhase(
      name: 'muta_fight',
      recoveryArmyPerLine: 2,
      branches: [
        // 분기 A: home 스포어 수비형 뮤탈 승리 > home 승
        ScriptBranch(
          id: 'muta_home_spore_win',
          description: '(phase3) 분기A - 스포어 수비형 홈 승',
          conditionStat: 'defense+control',
          baseProbability: 0.5,
          conditionPriorBranchIds: ['ling_defend_home'],
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 뮤탈리스크 생산! 앞마당과 본진에 스포어까지 깔아줍니다!',
              altText: '{home} 선수 뮤탈 생산 시작! 스포어로 수비 태세를 갖춥니다!',
              homeArmy: 5,
              homeResource: -625,
              awayArmy: 0,
              awayResource: 100,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수도 뮤탈리스크 생산! 스커지를 섞어 공격적으로 나옵니다!',
              altText: '{away} 선수 뮤탈에 스커지까지! 공격적인 편성입니다!',
              homeArmy: 0,
              homeResource: 100,
              awayArmy: 3,
              awayResource: -300,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 저글링이 앞마당 스포어를 건드립니다! 하지만 뮤탈이 바로 수비!',
              altText: '{away} 선수, 저글링으로 스포어를 노리지만 뮤탈에 막힙니다!',
              homeArmy: 2,
              homeResource: -100,
              awayArmy: -1,
              awayResource: -50,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 저글링이 상대 본진 드론을 괴롭힙니다! 뮤탈을 끌어옵니다!',
              altText: '{home} 선수, 저글링 견제로 상대 뮤탈을 본진으로 돌려세웁니다!',
              homeArmy: -1,
              homeResource: -50,
              awayArmy: 2,
              awayResource: -100,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 스포어 위에서 뮤탈 교전! 효율적으로 상대 뮤탈을 잡아냅니다!',
              altText: '{home} 선수 스포어 화력 지원! 뮤탈 교환에서 압도합니다!',
              homeArmy: -2,
              homeResource: -200,
              awayArmy: -5,
              awayResource: -500,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 뮤탈 수가 밀립니다! 제공권을 잃고 있습니다!',
              altText: '{away} 선수, 뮤탈이 녹아내립니다! 수비가 어렵습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 남은 뮤탈로 드론을 물어뜯습니다! 자원 차이가 벌어집니다!',
              altText: '{home} 선수 뮤탈 수 우위! 상대 드론을 초토화합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -4,
              awayResource: -400,
              decisive: true,
            ),
          ],
        ),

        // 분기 B: away 공격형 뮤탈+저글링 승리 > away 승
        ScriptBranch(
          id: 'muta_away_attack_win',
          description: '(phase3) 분기B - 공격형 어웨이 승',
          conditionStat: 'attack+control',
          homeStatMustBeHigher: false,
          baseProbability: 0.5,
          conditionPriorBranchIds: ['ling_defend_home'],
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 뮤탈리스크 생산! 앞마당 수비에 집중합니다!',
              altText: '{home} 선수 뮤탈 생산 시작! 앞마당을 지키면서 운영합니다!',
              homeArmy: 2,
              homeResource: -200,
              awayArmy: 0,
              awayResource: 100,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수도 뮤탈리스크! 저글링을 대량으로 모읍니다!',
              altText: '{away} 선수 뮤탈에 저글링 물량까지! 양방향 공격을 준비합니다!',
              homeArmy: 0,
              homeResource: 100,
              awayArmy: 3,
              awayResource: -300,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 뮤탈로 앞마당 드론을 물어뜯습니다!',
              altText: '{away} 선수 뮤탈 견제! 앞마당 드론 피해를 줍니다!',
              homeArmy: -1,
              homeResource: -100,
              awayArmy: 0,
              awayResource: -50,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 양쪽에서 공격이 들어옵니다! 대응이 어렵습니다!',
              altText: '{home} 선수 드론을 빼보지만 피해가 큽니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 저글링이 본진까지 밀고 들어갑니다!',
              altText: '{away} 선수 저글링 본진 침투! 드론을 괴롭힙니다!',
              homeArmy: -1,
              homeResource: -100,
              awayArmy: -1,
              awayResource: -50,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 뮤탈을 추가로 뽑습니다! 스커지도 섞습니다!',
              altText: '{away} 선수 뮤탈 보충! 수가 점점 벌어집니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 병력을 휘두르며 {home} 선수를 흔듭니다! 뮤탈 한방 교전!',
              altText: '{away} 선수 뮤탈 집중! 상대 뮤탈을 한 순간에 잡아냅니다!',
              homeArmy: -3,
              homeResource: -500,
              awayArmy: -1,
              awayResource: -200,
              decisive: true,
            ),
          ],
        ),

        // 분기 C: away 스포어 수비형 뮤탈 승리 > away 승
        ScriptBranch(
          id: 'muta_away_spore_win',
          description: '(phase3) 분기C - 스포어 수비형 어웨이 승',
          conditionStat: 'defense+control',
          homeStatMustBeHigher: false,
          baseProbability: 0.5,
          conditionPriorBranchIds: ['ling_defend_away'],
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 뮤탈리스크 생산! 앞마당과 본진에 스포어까지 깔아줍니다!',
              altText: '{away} 선수 뮤탈 생산 시작! 스포어로 수비 태세를 갖춥니다!',
              homeArmy: 0,
              homeResource: 100,
              awayArmy: 5,
              awayResource: -625,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수도 뮤탈리스크 생산! 스커지를 섞어 공격적으로 나옵니다!',
              altText: '{home} 선수 뮤탈에 스커지까지! 공격적인 편성입니다!',
              homeArmy: 3,
              homeResource: -300,
              awayArmy: 0,
              awayResource: 100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 저글링이 앞마당 스포어를 건드립니다! 하지만 뮤탈이 바로 수비!',
              altText: '{home} 선수, 저글링으로 스포어를 노리지만 뮤탈에 막힙니다!',
              homeArmy: -1,
              homeResource: -50,
              awayArmy: 2,
              awayResource: -100,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 저글링이 상대 본진 드론을 괴롭힙니다! 뮤탈을 끌어옵니다!',
              altText: '{away} 선수, 저글링 견제로 상대 뮤탈을 본진으로 돌려세웁니다!',
              homeArmy: 2,
              homeResource: -100,
              awayArmy: -1,
              awayResource: -50,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 스포어 위에서 뮤탈 교전! 효율적으로 상대 뮤탈을 잡아냅니다!',
              altText: '{away} 선수 스포어 화력 지원! 뮤탈 교환에서 압도합니다!',
              homeArmy: -5,
              homeResource: -500,
              awayArmy: -2,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 뮤탈 수가 밀립니다! 제공권을 잃고 있습니다!',
              altText: '{home} 선수, 뮤탈이 녹아내립니다! 수비가 어렵습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 남은 뮤탈로 드론을 물어뜯습니다! 자원 차이가 벌어집니다!',
              altText: '{away} 선수 뮤탈 수 우위! 상대 드론을 초토화합니다!',
              homeArmy: -4,
              homeResource: -400,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),

        // 분기 D: home 공격형 뮤탈+저글링 승리 > home 승
        ScriptBranch(
          id: 'muta_home_attack_win',
          description: '(phase3) 분기D - 공격형 홈 승',
          conditionStat: 'attack+control',
          baseProbability: 0.5,
          conditionPriorBranchIds: ['ling_defend_away'],
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 뮤탈리스크 생산! 앞마당 수비에 집중합니다!',
              altText: '{away} 선수 뮤탈 생산 시작! 앞마당을 지키면서 운영합니다!',
              homeArmy: 0,
              homeResource: 100,
              awayArmy: 2,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수도 뮤탈리스크! 저글링을 대량으로 모읍니다!',
              altText: '{home} 선수 뮤탈에 저글링 물량까지! 양방향 공격을 준비합니다!',
              homeArmy: 3,
              homeResource: -300,
              awayArmy: 0,
              awayResource: 100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 뮤탈로 앞마당 드론을 물어뜯습니다!',
              altText: '{home} 선수 뮤탈 견제! 앞마당 드론 피해를 줍니다!',
              homeArmy: 0,
              homeResource: -50,
              awayArmy: -1,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 양쪽에서 공격이 들어옵니다! 대응이 어렵습니다!',
              altText: '{away} 선수 드론을 빼보지만 피해가 큽니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 저글링이 본진까지 밀고 들어갑니다!',
              altText: '{home} 선수 저글링 본진 침투! 드론을 괴롭힙니다!',
              homeArmy: -1,
              homeResource: -50,
              awayArmy: -1,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 뮤탈을 추가로 뽑습니다! 스커지도 섞습니다!',
              altText: '{home} 선수 뮤탈 보충! 수가 점점 벌어집니다!',
              homeArmy: 0,
              homeResource: -100,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 병력을 휘두르며 {away} 선수를 흔듭니다! 뮤탈 한방 교전!',
              altText: '{home} 선수 뮤탈 집중! 상대 뮤탈을 한 순간에 잡아냅니다!',
              homeArmy: -1,
              homeResource: -200,
              awayArmy: -3,
              awayResource: -500,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
