part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 9드론 레어 미러전(9pool_lair_mirror.dart)
//
// 오프닝 : 레어 선택 및 이어서 발업 누르는 것 까지
//
// phase1 (저글링 싸움 페이즈)
// 	분기A : home 저글링 싸움 압도 > home 승	  (attack+control)
// 	분기B : away 저글링 싸움 압도 > away 승		(attack+control)
// 	분기C : 저글링으로 눈치보며 별일없이 다음 페이즈
//          - home 쪽 소수의 저글링이 away 본진 드론 일 못하게 함(skipChance)
//          - away 쪽 소수의 저글링이 home 본진 드론 일 못하게 함(skipChance)
//
// phase2 (스파이어 페이즈)
// 	분기A : home 뮤탈 싸움 압도 > home 승		  (sense+control)
//          - home 저글링이 돌아서 상대방 본진 드론 타격 2기 잡고 일 못하게 함(skipChance)
// 	분기B : away 뮤탈 싸움 압도 > away 승			(sense+control)
//          - away 저글링이 돌아서 상대방 본진 드론 타격 2기 잡고 일 못하게 함(skipChance)
// 	분기C : 양쪽 치고 박고 결판 안나고 앞마당 시도 후 다음 페이즈
//
// phase3 (중반 페이즈)
// 	분기A : home 뮤탈 업그레이드 앞서며 대규모 뮤탈 싸움에서 승리 > home 승		  (control)
//          - home 의 교전 승리 표현이 최소 2번 (skipChance)
// 	분기B : away 뮤탈 업그레이드 앞서며 대규모 뮤탈 싸움에서 승리 > away 승			(control)
//          - away 의 교전 승리 표현이 최소 2번 (skipChance)
// 	분기C : away 뮤탈 업그레이드 앞서지만 스커지 컨트롤 및 home 본진에서 싸우며 데미지 분산되어 home 교전 승리 그대로 상대 본진 > home 승		(strategy+sense)
//          - home 스커지가 away 뮤탈에 적중했다는 표현 최소 2번 (skipChance)
// 	분기D : home 뮤탈 업그레이드 앞서지만 스커지 컨트롤 및 away 본진에서 싸우며 데미지 분산되어 away 교전 승리 그대로 상대 본진 > away 승			(strategy+sense)
//          - away 스커지가 home 뮤탈에 적중했다는 표현 최소 2번 (skipChance)
// 	분기E : 치고 박고 싸우지만 서로 피해 조금씩 입히고 승자는 없이 추가 확장을 진행한 후 다음 페이즈

// phase4 (후반 페이즈)
// 	분기A(낮은 확률) : 디바우러까지 뽑으며 home 대규모 공중전 승리 > home 승  (macro)
// 	분기B(낮은 확률) : 디바우러까지 뽑으며 away 대규모 공중전 승리 > away 승  (macro)
// ----------------------------------------------------------
const _zvz9poolLairMirror = ScenarioScript(
  id: 'zvz_9pool_lair_mirror',
  matchup: 'ZvZ',
  homeBuildIds: ['zvz_9pool_lair'],
  awayBuildIds: ['zvz_9pool_lair'],
  description: '9풀 레어 미러 — 발업 스킵 후 뮤탈 선점 싸움',
  phases: [
    // ── Phase 0: 오프닝 — 9드론 → 풀+가스 → 레어 → 저글링+발업 ──
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 드론 9개까지 찍습니다.',
          altText: '{home} 선수, 9드론까지 생산합니다.',
          homeArmy: 0,
          homeResource: 200,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수도 9드론까지 뽑습니다.',
          altText: '{away} 선수, 9드론까지 생산합니다.',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: 200,
        ),
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 스포닝풀과 가스 동시에 짓습니다.',
          altText: '{home} 선수, 9드론에 스포닝풀과 가스! 빠른 테크를 노리는 빌드!',
          homeArmy: 0,
          homeResource: -250,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수도 스포닝풀과 가스를 짓습니다.',
          altText: '{away} 선수, 9드론에 스포닝풀과 가스까지! 레어를 노리는데요~',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: -250,
        ),
        ScriptEvent(
          owner: LogOwner.system,
          text: '양 선수, 선발업과 선레어 중 어떤 걸 선택할지도 지켜보겠습니다!',
          altText: '양쪽 다 공격적인 빌드, 선레어와 선발업 중 선택이 갈릴 수 있습니다!',
          homeArmy: 0,
          homeResource: 100,
          awayArmy: 0,
          awayResource: 100,
        ),
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수, 가스 100이 모이자마자 레어 진화! 발업보다 테크를 우선합니다!',
          altText: '{home} 선수 선 레어 선택! 공중 유닛을 최대한 빨리 뽑겠다는 판단!',
          homeArmy: 0,
          homeResource: -250,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수도 레어 진화 시작! 양쪽 다 테크를 올립니다!',
          altText: '{away} 선수도 선 레어! 양쪽 다 테크를 우선합니다!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: -250,
        ),
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수, 저글링 6기 생산하면서 가스 100이 모이자마자 발업도 눌러줍니다!',
          altText: '{home} 선수 저글링 생산! 가스 100이 모이자마자 발업도 시작합니다!',
          homeArmy: 3,
          homeResource: -350,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수, 저글링 6기! 발업도 같이 돌립니다! 레어가 올라가는 동안 견제!',
          altText: '{away} 선수도 저글링에 발업! 비슷한 타이밍입니다!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 3,
          awayResource: -350,
        ),
        ScriptEvent(
          owner: LogOwner.system,
          text: '양쪽 다 선 레어 선택 후 발업! 테크 타이밍이 비슷합니다!',
          altText: '발업도 비슷한 타이밍에 끝납니다!',
          homeArmy: 0,
          homeResource: -50,
          awayArmy: 0,
          awayResource: -50,
          skipChance: 0.3,
        ),
      ],
    ),
    // ── Phase 1: 저글링 싸움 페이즈 ──
    ScriptPhase(
      name: 'ling_fight',
      branches: [
        // 분기A: home 저글링 싸움 압도 → home 승
        ScriptBranch(
          id: 'home_ling_win',
          description: '(phase1) 분기A - 저글링 홈 승',
          baseProbability: 0.6,
          conditionStat: 'attack+control',
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 발업 저글링이 상대 본진으로 돌진합니다!',
              altText: '{home} 선수 발업 저글링이 상대 진영으로 침투합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 저글링으로 막아보지만 수가 밀립니다!',
              altText: '{away} 선수 저글링이 하나둘 녹아내립니다!',
              homeArmy: -1,
              homeResource: -50,
              awayArmy: -2,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 저글링이 드론까지 물어뜯습니다! 일꾼 피해가 큽니다!',
              altText: '{home} 선수, 드론을 잡아냅니다! 자원 차이가 벌어집니다!',
              homeArmy: -2,
              homeResource: -100,
              awayArmy: -4,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '저글링 싸움에서 압도적 차이! {home} 선수가 밀어붙입니다!',
              altText: '초반 저글링 싸움에서 결판이 났습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기B: away 저글링 싸움 압도 → away 승
        ScriptBranch(
          id: 'away_ling_win',
          description: '(phase1) 분기B - 저글링 어웨이 승',
          baseProbability: 0.6,
          conditionStat: 'attack+control',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 발업 저글링이 상대 본진으로 돌진합니다!',
              altText: '{away} 선수 발업 저글링이 상대 진영으로 침투합니다!',
              homeArmy: 0,
              homeResource: -100,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 저글링으로 막아보지만 수가 밀립니다!',
              altText: '{home} 선수 저글링이 하나둘 녹아내립니다!',
              homeArmy: -2,
              homeResource: -100,
              awayArmy: -1,
              awayResource: -50,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 저글링이 드론까지 물어뜯습니다! 일꾼 피해가 큽니다!',
              altText: '{away} 선수, 드론을 잡아냅니다! 자원 차이가 벌어집니다!',
              homeArmy: -4,
              homeResource: -200,
              awayArmy: -2,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '저글링 싸움에서 압도적 차이! {away} 선수가 밀어붙입니다!',
              altText: '초반 저글링 싸움에서 결판이 났습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기C: 비등 → 다음 페이즈
        ScriptBranch(
          id: 'ling_even',
          description: '(phase1) 분기C - 저글링 비등',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              owner: LogOwner.system,
              text: '양쪽 발업 저글링이 센터에서 마주칩니다! 소규모 교전!',
              altText: '발업 저글링끼리 교전! 비등하게 교환됩니다!',
              homeArmy: -2,
              homeResource: -100,
              awayArmy: -2,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 저글링 몇 기가 상대 본진에 붙어 일꾼 견제가 들어갑니다!',
              altText: '{home} 선수 저글링이 상대 드론을 잠깐 괴롭힙니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -80,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 저글링 몇 기가 상대 본진에 붙어 드론을 위협합니다!',
              altText: '{away} 선수 저글링이 상대 드론을 잠깐 괴롭힙니다!',
              homeArmy: 0,
              homeResource: -80,
              awayArmy: 0,
              awayResource: 0,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '결정적인 차이가 안 납니다! 뮤탈전으로 넘어갑니다!',
              altText: '저글링 교전은 비등! 승부는 뮤탈전에서 갈립니다!',
              homeArmy: 0,
              homeResource: -50,
              awayArmy: 0,
              awayResource: -50,
            ),
          ],
        ),
      ],
    ),
    // ── Phase 2: 레어 완성 → 스파이어 건설 ──
    ScriptPhase(
      name: 'spire_build',
      recoveryArmyPerLine: 1,
      linearEvents: [
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 레어 완성.',
          altText: '{home} 선수, 레어 완성.',
          homeArmy: 2,
          homeResource: -100,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수도 레어 완성.',
          altText: '{away} 선수, 레어 완성.',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2,
          awayResource: -100,
        ),
        ScriptEvent(
          owner: LogOwner.home,
          text: '{home} 선수 스파이어를 바로 올립니다!',
          altText: '{home} 선수, 스파이어 건설! 공중 유닛까지 얼마 안 남았습니다!',
          homeArmy: 0,
          homeResource: -300,
          awayArmy: 0,
          awayResource: 0,
        ),
        ScriptEvent(
          owner: LogOwner.away,
          text: '{away} 선수도 스파이어 건설!',
          altText: '{away} 선수, 스파이어! 타이밍이 비슷합니다!',
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 0,
          awayResource: -300,
        ),
        ScriptEvent(
          owner: LogOwner.system,
          text: '오버로드로 상대 빌드가 다 보이죠! 양쪽 저글링으로 눈치를 봅니다!',
          altText: '스파이어 올라가는 동안 저글링으로 정찰! 상대 움직임을 확인합니다!',
          homeArmy: 2,
          homeResource: -100,
          awayArmy: 2,
          awayResource: -100,
          skipChance: 0.3,
        ),
      ],
    ),
    // ── Phase 3: 스파이어 페이즈 — 뮤탈 싸움 분기 ──
    ScriptPhase(
      name: 'muta_fight',
      recoveryArmyPerLine: 1,
      branches: [
        // 분기A: home 뮤탈 압도 → home 승
        ScriptBranch(
          id: 'muta_home_win',
          description: '(phase3) 분기A - 뮤탈 홈 승',
          baseProbability: 0.7,
          conditionStat: 'sense+control',
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수 스파이어 완성! 뮤탈리스크가 나옵니다!',
              altText: '{home} 선수, 스파이어에서 뮤탈이 쏟아집니다!',
              homeArmy: 4,
              homeResource: -400,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수도 스파이어 완성! 뮤탈 수가 엇비슷합니다!',
              altText: '{away} 선수도 뮤탈 생산! 비슷한 타이밍입니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4,
              awayResource: -400,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 뮤탈로 상대 드론을 급습! 스커지를 절묘하게 피합니다!',
              altText: '{home} 선수 뮤탈 견제가 날카롭습니다! 드론을 물어뜯습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 저글링이 돌아서 상대 본진 드론을 물어뜯습니다! 드론 2기 제거!',
              altText: '{home} 선수 저글링까지 합류! 상대 드론을 잡아냅니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -150,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '{home} 선수 뮤탈 운용이 압도적입니다! 상대가 대응을 못합니다!',
              altText: '뮤탈 싸움에서 {home} 선수가 완전히 앞섭니다!',
              homeArmy: 2,
              homeResource: -200,
              awayArmy: -6,
              awayResource: -300,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '뮤탈 수 차이가 결정적! {home} 선수 밀어붙입니다!',
              altText: '{home} 선수 뮤탈 물량으로 압도합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기B: away 뮤탈 압도 → away 승
        ScriptBranch(
          id: 'muta_away_win',
          description: '(phase3) 분기B - 뮤탈 어웨이 승',
          baseProbability: 0.7,
          conditionStat: 'sense+control',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수 스파이어 완성! 뮤탈리스크가 나옵니다!',
              altText: '{away} 선수, 스파이어에서 뮤탈이 쏟아집니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 4,
              awayResource: -400,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수도 스파이어 완성! 뮤탈 수가 엇비슷합니다!',
              altText: '{home} 선수도 뮤탈 생산! 비슷한 타이밍입니다!',
              homeArmy: 4,
              homeResource: -400,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 뮤탈로 상대 드론을 급습! 스커지를 절묘하게 피합니다!',
              altText: '{away} 선수 뮤탈 견제가 날카롭습니다! 드론을 물어뜯습니다!',
              homeArmy: 0,
              homeResource: -200,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 저글링이 돌아서 상대 본진 드론을 물어뜯습니다! 드론 2기 격추!',
              altText: '{away} 선수 저글링까지 합류! 상대 드론을 잡아냅니다!',
              homeArmy: 0,
              homeResource: -150,
              awayArmy: 0,
              awayResource: 0,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '{away} 선수 뮤탈 운용이 압도적입니다! 상대가 대응을 못합니다!',
              altText: '뮤탈 싸움에서 {away} 선수가 완전히 앞섭니다!',
              homeArmy: -2,
              homeResource: -100,
              awayArmy: 2,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '뮤탈 수 차이가 결정적! {away} 선수 밀어붙입니다!',
              altText: '{away} 선수 뮤탈 물량으로 압도합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기C: 비등 → 앞마당 시도 → 다음 페이즈
        ScriptBranch(
          id: 'muta_even',
          description: '(phase3) 분기C - 뮤탈 비등',
          baseProbability: 1.0,
          events: [
            ScriptEvent(
              owner: LogOwner.system,
              text: '양쪽 스파이어 완성! 뮤탈리스크가 나옵니다!',
              altText: '양쪽 뮤탈이 동시에 나옵니다!',
              homeArmy: 4,
              homeResource: -400,
              awayArmy: 4,
              awayResource: -400,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '뮤탈 동수! 서로 견제를 주고받지만 결정적인 차이가 안 납니다!',
              altText: '뮤탈 수가 엇비슷합니다! 치고 빠지기를 반복합니다!',
              homeArmy: -1,
              homeResource: -100,
              awayArmy: -1,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 뮤탈로 견제하면서 앞마당 해처리를 슬쩍 올립니다!',
              altText: '{home} 선수 앞마당 확장! 라바 회전을 늘리겠다!',
              homeArmy: 0,
              homeResource: -300,
              awayArmy: 0,
              awayResource: 0,
              homeExpansion: true,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수도 앞마당! 상대만 확장하게 둘 수 없습니다!',
              altText: '{away} 선수, 앞마당 해처리! 양쪽 다 확장합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -300,
              awayExpansion: true,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '양쪽 앞마당! 라바 회전이 2배! 뮤탈 물량전으로 가겠습니다!',
              altText: '장기전 돌입! 드론 관리와 라바 운용이 승부를 가릅니다!',
              homeArmy: 2,
              homeResource: 200,
              awayArmy: 2,
              awayResource: 200,
            ),
          ],
        ),
      ],
    ),
    // ── Phase 4: 중반 페이즈 — 업그레이드 뮤탈전 ──
    ScriptPhase(
      name: 'mid_muta_war',
      recoveryArmyPerLine: 1,
      branches: [
        // 분기A: home 뮤탈 업그레이드 우위 → home 승
        ScriptBranch(
          id: 'upgrade_home_win',
          description: '(phase4) 분기A - 업그레이드 홈 승',
          baseProbability: 0.7,
          conditionStat: 'control',
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 뮤탈 공격력 업그레이드가 먼저 완성됩니다!',
              altText: '{home} 선수 뮤탈 업그레이드가 앞섭니다!',
              homeArmy: 3,
              homeResource: -300,
              awayArmy: 2,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 업그레이드 앞선 뮤탈로 교전! 상대 뮤탈을 격추합니다!',
              altText: '{home} 선수 뮤탈이 교전에서 앞섭니다! 상대 뮤탈이 녹아내립니다!',
              homeArmy: 0,
              homeResource: -50,
              awayArmy: -3,
              awayResource: -50,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 추가 뮤탈이 합류하면서 또 한 번 교전 승리!',
              altText: '{home} 선수 뮤탈 물량 차이가 점점 벌어집니다!',
              homeArmy: 2,
              homeResource: -200,
              awayArmy: -2,
              awayResource: -100,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '뮤탈 업그레이드 차이가 누적됩니다! {home} 선수가 공중을 장악합니다!',
              altText: '업그레이드 차이로 교전마다 {home} 선수가 이깁니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '대규모 뮤탈 싸움에서 {home} 선수 완승! 상대 공중 병력이 전멸합니다!',
              altText: '{home} 선수 뮤탈 대전에서 압도적 승리!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기B: away 뮤탈 업그레이드 우위 → away 승
        ScriptBranch(
          id: 'upgrade_away_win',
          description: '(phase4) 분기B - 업그레이드 어웨이 승',
          baseProbability: 0.7,
          conditionStat: 'control',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 뮤탈 공격력 업그레이드가 먼저 완성됩니다!',
              altText: '{away} 선수 뮤탈 업그레이드가 앞섭니다!',
              homeArmy: 2,
              homeResource: -200,
              awayArmy: 3,
              awayResource: -300,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 업그레이드 앞선 뮤탈로 교전! 상대 뮤탈을 격추합니다!',
              altText: '{away} 선수 뮤탈이 교전에서 앞섭니다! 상대 뮤탈이 녹아내립니다!',
              homeArmy: -3,
              homeResource: -50,
              awayArmy: 0,
              awayResource: -50,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 추가 뮤탈이 합류하면서 또 한 번 교전 승리!',
              altText: '{away} 선수 뮤탈 물량 차이가 점점 벌어집니다!',
              homeArmy: -2,
              homeResource: -100,
              awayArmy: 2,
              awayResource: -200,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '뮤탈 업그레이드 차이가 누적됩니다! {away} 선수가 공중을 장악합니다!',
              altText: '업그레이드 차이로 교전마다 {away} 선수가 이깁니다!',
              homeArmy: 0,
              homeResource: -200,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '대규모 뮤탈 싸움에서 {away} 선수 완승! 상대 공중 병력이 전멸합니다!',
              altText: '{away} 선수 뮤탈 대전에서 압도적 승리!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기C: away 업그레이드 앞서지만 home 스커지+본진 방어 역전 → home 승
        ScriptBranch(
          id: 'scourge_reversal_home',
          description: '(phase4) 분기C - 스커지 역전 홈 승',
          baseProbability: 0.5,
          conditionStat: 'strategy+sense',
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 뮤탈 업그레이드가 앞섭니다! 공격적으로 나옵니다!',
              altText: '{away} 선수 업그레이드 우위! 뮤탈을 몰고 공격합니다!',
              homeArmy: 2,
              homeResource: -200,
              awayArmy: 3,
              awayResource: -300,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 스커지를 섞어서 대응! 상대 뮤탈에 스커지가 적중합니다!',
              altText: '{home} 선수 스커지가 상대 뮤탈 뭉치를 관통합니다!',
              homeArmy: 0,
              homeResource: -100,
              awayArmy: -3,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 본진에서 스포어 콜로니와 함께 싸웁니다! 스커지가 또 적중!',
              altText: '{home} 선수 스커지가 한 번 더! 상대 뮤탈이 떨어집니다!',
              homeArmy: 0,
              homeResource: -50,
              awayArmy: -2,
              awayResource: 0,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '본진 방어에서 데미지가 분산됩니다! 스커지 컨트롤이 빛을 발합니다!',
              altText: '{home} 선수 본진 방어가 효과적입니다! 스커지가 핵심이었습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 교전 승리 후 남은 뮤탈로 그대로 상대 본진으로!',
              altText: '{home} 선수, 역전 성공! 남은 병력으로 밀어붙입니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -200,
              decisive: true,
            ),
          ],
        ),
        // 분기D: home 업그레이드 앞서지만 away 스커지+본진 방어 역전 → away 승
        ScriptBranch(
          id: 'scourge_reversal_away',
          description: '(phase4) 분기D - 스커지 역전 어웨이 승',
          baseProbability: 0.5,
          conditionStat: 'strategy+sense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 뮤탈 업그레이드가 앞섭니다! 공격적으로 나옵니다!',
              altText: '{home} 선수 업그레이드 우위! 뮤탈을 몰고 공격합니다!',
              homeArmy: 3,
              homeResource: -300,
              awayArmy: 2,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 스커지를 섞어서 대응! 상대 뮤탈에 스커지가 적중합니다!',
              altText: '{away} 선수 스커지가 상대 뮤탈 뭉치를 관통합니다!',
              homeArmy: -3,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 본진에서 스포어 콜로니와 함께 싸웁니다! 스커지가 또 적중!',
              altText: '{away} 선수 스커지가 한 번 더! 상대 뮤탈이 떨어집니다!',
              homeArmy: -2,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -50,
              skipChance: 0.5,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '본진 방어에서 데미지가 분산됩니다! 스커지 컨트롤이 빛을 발합니다!',
              altText: '{away} 선수 본진 방어가 효과적입니다! 스커지가 핵심이었습니다!',
              homeArmy: 0,
              homeResource: -100,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 교전 승리 후 남은 뮤탈로 그대로 상대 본진으로!',
              altText: '{away} 선수, 역전 성공! 남은 병력으로 밀어붙입니다!',
              homeArmy: 0,
              homeResource: -200,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기E: 비등 → 추가 확장 → 다음 페이즈
        ScriptBranch(
          id: 'mid_even',
          description: '(phase4) 분기E - 중반 비등',
          baseProbability: 0.5,
          events: [
            ScriptEvent(
              owner: LogOwner.system,
              text: '양쪽 뮤탈이 치고 빠지기를 반복합니다! 결정적 차이가 안 납니다!',
              altText: '뮤탈 싸움이 계속되지만 어느 쪽도 확실한 우위를 잡지 못합니다!',
              homeArmy: 2,
              homeResource: -200,
              awayArmy: 2,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 서드 해처리를 올리면서 장기전을 준비합니다!',
              altText: '{home} 선수, 추가 확장! 자원 확보에 나섭니다!',
              homeArmy: 0,
              homeResource: -300,
              awayArmy: 0,
              awayResource: 0,
              homeExpansion: true,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수도 서드! 양쪽 다 장기전 체제입니다!',
              altText: '{away} 선수, 추가 확장! 뮤탈전이 길어집니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: -300,
              awayExpansion: true,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '서로 피해를 조금씩 주면서도 결판은 안 납니다! 초장기전으로!',
              altText: '양쪽 확장까지 완료! 디바우러 테크가 나올 수도 있습니다!',
              homeArmy: 0,
              homeResource: 200,
              awayArmy: 0,
              awayResource: 200,
            ),
          ],
        ),
      ],
    ),
    // ── Phase 5: 후반 페이즈 — 디바우러 공중전 ──
    ScriptPhase(
      name: 'devourer_war',
      recoveryArmyPerLine: 1,
      branches: [
        // 분기A: home 디바우러 → home 승
        ScriptBranch(
          id: 'devourer_home_win',
          description: '(phase5) 분기A - 디바우러 홈 승',
          baseProbability: 0.6,
          conditionStat: 'macro',
          events: [
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 퀸즈네스트에 이어 하이브까지 올립니다!',
              altText: '{home} 선수, 하이브 테크! 최종 단계입니다!',
              homeArmy: 0,
              homeResource: -550,
              awayArmy: 0,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수도 하이브를 올리지만 {home} 선수보다 한 발 늦습니다!',
              altText: '{away} 선수, 하이브 테크! 하지만 타이밍이 살짝 늦습니다!',
              homeArmy: 0,
              homeResource: -200,
              awayArmy: 0,
              awayResource: -550,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 그레이터 스파이어 완성! 뮤탈리스크가 디바우러로 변태합니다!',
              altText: '{home} 선수, 디바우러가 나옵니다! 공중전의 끝판왕!',
              homeArmy: 3,
              homeResource: -450,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '디바우러의 산성 포자가 상대 뮤탈에 쌓입니다! 뮤탈이 녹아내립니다!',
              altText: '디바우러 앞에서 뮤탈이 버틸 수가 없습니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: -4,
              awayResource: -100,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수, 디바우러와 뮤탈 조합으로 대규모 공중전 승리!',
              altText: '{home} 선수, 공중전에서 완전히 압도합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
        // 분기B: away 디바우러 → away 승
        ScriptBranch(
          id: 'devourer_away_win',
          description: '(phase5) 분기B - 디바우러 어웨이 승',
          baseProbability: 0.6,
          conditionStat: 'macro',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 퀸즈네스트에 이어 하이브까지 올립니다!',
              altText: '{away} 선수, 하이브 테크! 최종 단계입니다!',
              homeArmy: 0,
              homeResource: -200,
              awayArmy: 0,
              awayResource: -550,
            ),
            ScriptEvent(
              owner: LogOwner.home,
              text: '{home} 선수도 하이브를 올리지만 {away} 선수보다 한 발 늦습니다!',
              altText: '{home} 선수, 하이브 테크! 하지만 타이밍이 살짝 늦습니다!',
              homeArmy: 0,
              homeResource: -550,
              awayArmy: 0,
              awayResource: -200,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 그레이터 스파이어 완성! 뮤탈리스크가 디바우러로 변태합니다!',
              altText: '{away} 선수, 디바우러가 나옵니다! 공중전의 끝판왕!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 3,
              awayResource: -450,
            ),
            ScriptEvent(
              owner: LogOwner.system,
              text: '디바우러의 산성 포자가 상대 뮤탈에 쌓입니다! 뮤탈이 녹아내립니다!',
              altText: '디바우러 앞에서 뮤탈이 버틸 수가 없습니다!',
              homeArmy: -4,
              homeResource: -100,
              awayArmy: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              owner: LogOwner.away,
              text: '{away} 선수, 디바우러와 뮤탈 조합으로 대규모 공중전 승리!',
              altText: '{away} 선수, 공중전에서 완전히 압도합니다!',
              homeArmy: 0,
              homeResource: 0,
              awayArmy: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),
      ],
    ),
  ],
);
