part of '../../scenario_scripts.dart';

// ----------------------------------------------------------
// 9풀 발업 미러 — 발업 대기 → 상대 발업 확인 → 싸움/전환/올인 분기
// ----------------------------------------------------------
const _zvz9poolSpeedMirror = ScenarioScript(
  id: 'zvz_9pool_speed_mirror',
  matchup: 'ZvZ',
  homeBuildIds: ['zvz_9pool_speed'],
  awayBuildIds: ['zvz_9pool_speed'],
  description: '9풀 발업 미러 — 발업 대기 후 컨트롤 싸움 or 뮤탈 전환 or 저글링 올인',
  phases: [
    // Phase 0: 오프닝 — 발업 대기하며 저글링 축적 (lines 1-10)
    ScriptPhase(
      name: 'opening',
      startLine: 1,
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수 드론 9개까지 찍습니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: 200,
        ),
        ScriptEvent(
          text: '{away} 선수도 9드론까지 뽑습니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: 200,
        ),
        ScriptEvent(
          text: '{home} 선수 스포닝풀과 가스 동시에 짓습니다.',
          owner: LogOwner.home,
          homeArmy: 0,
          awayArmy: 0,
          awayResource: 0,
          homeResource: -250,
          altText: '{home} 선수, 스포닝풀과 가스까지 올립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수 스포닝풀과 가스 동시 건설합니다.',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 0,
          awayResource: -250,
          altText: '{away} 선수, 스포닝풀 건설하며 가스도 올립니다.',
        ),
        ScriptEvent(
          text: '양 선수, 선발업과 선레어 중 어떤 걸 선택할지도 지켜보겠습니다!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: 100,
          awayResource: 100,
          altText: '양쪽 다 공격적인 빌드, 선레어와 선발업 중 선택이 갈릴 수 있습니다!',
        ),
        ScriptEvent(
          text: '{home} 선수, 스포닝풀 완성 후 저글링 6기 생산. 이어서 저글링 스피드업까지 눌러줍니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 3,
          homeResource: -350,
          altText: '{home} 선수 저글링 생산 시작, 저글링 발업도 진행합니다.',
        ),
        ScriptEvent(
          text: '{away} 선수, 저글링 6기 누릅니다. 양쪽 다 발업을 선택하네요.',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 3,
          awayResource: -350,
          altText: '{away} 선수 저글링 6기 생산, {away} 선수도 저글링 스피드업 선택합니다.',
        ),
        ScriptEvent(
          text: '초반 저글링 싸움으로 이어질까요? 한번 지켜보겠습니다.',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: -50,
          awayResource: -50,
        ),
        ScriptEvent(
          text: '이동 중 서로의 저글링이 만났지만 아직 발업이 되지 않았습니다. 서로 본인만 발업이 된다고 착각할 수 있겠는데요!',
          owner: LogOwner.system,
          homeArmy: 0,
          awayArmy: 0,
          homeResource: -50,
          awayResource: -50,
        ),
        ScriptEvent(
          text: '{home} 선수, 곧 완료될 발업을 믿고 저글링 컨트롤 싸움 거는데요!',
          owner: LogOwner.home,
          awayArmy: -2,
          awayResource: -100,
          homeArmy: -1,
          homeResource: -50,
          altText: '{home} 선수 본인만 스피드업 될거라는 자신감으로 저글링 싸움 겁니다!',
        ),
        ScriptEvent(
          text: '{away} 선수, 발업이 완료되면 유리하다는 생각에 저글링 빼지않고 싸워줍니다!',
          owner: LogOwner.away,
          homeArmy: -2,
          homeResource: -100,
          awayArmy: -1,
          awayResource: -50,
          altText: '{away} 선수 스피드업으로 추가 합류할 저글링을 믿고 싸움에 응수합니다!',
        ),
        ScriptEvent(
          text: '{home} 선수, 라바가 나올 때마다 저글링을 추가합니다.',
          owner: LogOwner.home,
          awayArmy: 0,
          awayResource: 0,
          homeArmy: 2,
          homeResource: -100,
          altText: '{home} 선수 저글링을 계속 추가하면서 발업을 기다립니다.',
        ),
        ScriptEvent(
          text: '{away} 선수, 저글링을 늘리면서 발업 완료를 기다립니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          homeResource: 0,
          awayArmy: 2,
          awayResource: -100,
          altText: '{away} 선수 추가적인 라바 모두 저글링으로 누릅니다.',
        ),
      ],
    ),

    // Phase 1: 발업 완료 + 상대도 발업 확인
    ScriptPhase(
      name: 'speed_done',
      linearEvents: [
        ScriptEvent(
          text: '{home} 선수, 저글링 발업 완료! 추가 저글링이 빠르게 합류합니다!',
          owner: LogOwner.home,
          homeArmy: 1,
          awayArmy: 0,
          homeResource: -50,
          awayResource: 0,
          altText: '{home} 선수 발업 완료! 저글링을 몰고 나갑니다!',
        ),
        ScriptEvent(
          text: '{away} 선수도 저글링 스피드업 완료! 양쪽 다 저글링의 스피드업을 확인합니다!',
          owner: LogOwner.away,
          homeArmy: 0,
          awayArmy: 1,
          homeResource: 0,
          awayResource: -50,
          altText: '{away} 선수도 발업 완료! 서로 발업을 찍었단 걸 확인합니다!',
        ),
      ],
    ),

    // Phase 2: 판단 분기 — 싸움(decisive) or 전환(non-decisive)
    ScriptPhase(
      name: 'decision',
      recoveryArmyPerLine: 1,
      branches: [
        // ── 분기 A: 센터 저글링 싸움 → 홈 컨트롤 승리 (decisive) ──
        ScriptBranch(
          id: 'center_home_wins',
          description: '(phase2) 분기A - 센터 저글링 홈 승',
          baseProbability: 0.2,
          conditionStat: 'control+attack',
          events: [
            ScriptEvent(
              text: '{home} 선수, 그래도 밀어붙이려고 합니다. 그만큼 컨트롤에 자신있다는거죠!',
              owner: LogOwner.home,
              homeArmy: 1,
              awayArmy: 0,
              homeResource: -50,
              awayResource: 0,
              altText: '{home} 선수 본인의 컨트롤을 믿고 저글링 교전 강행하려고 하는데요! ',
            ),
            ScriptEvent(
              text: '{away} 선수도 뺄 생각이 없습니다! 추가 저글링 합류하며 교전 시작합니다!',
              owner: LogOwner.away,
              homeResource: 0,
              awayResource: -50,
              homeArmy: 0,
              awayArmy: 1,
              altText: '{away} 선수, 빼지않고 맞붙습니다! 발업 저글링끼리 교전!',
            ),
            ScriptEvent(
              text: '{home} 선수, 혼신의 저글링 컨트롤이 이루어지면서 상대방 저글링을 크게 줄입니다!',
              owner: LogOwner.home,
              homeResource: -100,
              awayResource: -250,
              awayArmy: -5,
              homeArmy: -2,
              altText: '{home} 선수 저글링 컨트롤로 교전에서 큰 차이를 냅니다!',
            ),
            ScriptEvent(
              text: '{home} 선수, 추가 저글링 합류! 물량 차이가 벌어집니다!',
              owner: LogOwner.home,
              homeResource: -100,
              awayResource: -150,
              // 저글링 1기 추가됐지만 2기 죽으며 150
              homeArmy: 2,
              awayArmy: -1,
              // 1기 추가됐지만 2기 죽으며
              altText: '{home} 선수 모든 라바를 저글링에! 승기를 굳히려고 합니다!',
            ),
            ScriptEvent(
              text: '첫 교전의 결과로 저글링 숫자 차이가 너무 벌어졌습니다! {home} 선수 상대방 본진까지 진격합니다!',
              owner: LogOwner.home,
              homeArmy: -1,
              awayArmy: -4,
              homeResource: -50,
              awayResource: -200,
              decisive: true,
              altText: '저글링 컨트롤 차이가 초반에 큰 차이를 만들어내며 {home} 선수의 저글링이 상대방 본진까지 밀고 올라갑니다!',
            ),
          ],
        ),

        // ── 분기 B: 센터 저글링 싸움 → 어웨이 컨트롤 승리 (decisive) ──
        ScriptBranch(
          id: 'center_away_wins',
          description: '(phase2) 분기B - 센터 저글링 어웨이 승',
          baseProbability: 0.2,
          conditionStat: 'control+attack',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수, 본인의 컨트롤을 믿고 그대로 밀어붙이려고 합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 1,
              homeResource: 0,
              awayResource: -50,
              altText: '{away} 선수 서로의 발업을 확인했음에도 자신감으로 저글링 교전 강행하려고 하는데요!',
            ),
            ScriptEvent(
              text: '{home} 선수도 추가 저글링 합류시키며 교전 시작합니다!',
              owner: LogOwner.home,
              homeResource: -50,
              awayResource: 0,
              homeArmy: 1,
              awayArmy: 0,
              altText: '{home} 선수도 자신있게 맞붙습니다. 저글링 교전이 이루어집니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 공격적인 컨트롤로 상대방 저글링을 크게 줄입니다!',
              owner: LogOwner.away,
              homeResource: -250,
              awayResource: -100,
              awayArmy: -2,
              homeArmy: -5,
              altText: '{away} 선수 저글링 컨트롤로 교전에서 큰 이득을 가져갑니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링을 끊임없이 합류시킵니다. 한 눈에 봐도 이젠 저글링 물량 차이가 보이는데요!',
              owner: LogOwner.away,
              homeResource: -150,
              // 저글링 1기 추가됐지만 2기 죽으며 150
              awayResource: -100,
              homeArmy: -1,
              // 1기 추가됐지만 2기 죽으며
              awayArmy: 2,
              altText: '{away} 선수 승기를 굳히기 위해 저글링 추가를 멈추지 않습니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링 교전의 승리로 상대방의 본진까지 진격합니다!',
              owner: LogOwner.away,
              homeArmy: -4,
              awayArmy: -1,
              homeResource: -200,
              awayResource: -50,
              decisive: true,
              altText: '{away} 선수 발군의 저글링 컨트롤이네요 물량 차이를 내며 상대방 본진도 점령합니다!',
            ),
          ],
        ),

        // ── 분기 C: 엇갈림 → 홈 멀티태스킹 승리 (decisive) ──
        ScriptBranch(
          id: 'cross_home_wins',
          description: '(phase2) 분기C - 엇갈림 홈 승',
          baseProbability: 0.2,
          conditionStat: 'control+defense',
          events: [
            ScriptEvent(
              text: '초반 저글링 교전 후 약간의 소강상태입니다. 저글링 추가하고 발업을 기다리며 다시 기회를 보는데요.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '발업 저글링이 서로의 진영으로 움직임을 가져갑니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: -50,
              awayResource: -50,
              altText: '양쪽 발업 저글링이 서로를 못보고 지나칩니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링이 {home} 선수의 본진에 도착해서 드론을 노립니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: -1,
              awayResource: -50,
              homeResource: 0,
              altText: '{away} 선수의 저글링이 먼저 상대방 진영에 도착하여 상대방 드론 수를 줄이려고 합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 드론 뭉치기 컨트롤이 대단합니다! 추가 생산된 저글링까지 수비에 합류합니다.',
              owner: LogOwner.home,
              homeArmy: -1,
              homeResource: -50,
              awayResource: -150,
              awayArmy: -3,
              altText: '{home} 선수 드론을 피해없이 빼주면서 저글링 추가 생산을 기다린 후 드론과 저글링으로 같이 수비합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 수비는 수비대로 공격은 공격대로 성공합니다! 상대방이 공격에 신경쓰고 있을 때 본진 드론을 솎아냅니다!',
              owner: LogOwner.home,
              homeArmy: -1,
              awayArmy: -3,
              homeResource: -50,
              awayResource: -150,
              altText: '{home} 선수 수비를 완벽하게 해낸 후 상대방의 드론은 집요하게 잡아냅니다! 본인 피해는 최소화, 상대방 피해는 최대로, 이기적이네요!',
            ),
            ScriptEvent(
              text: '{home} 선수 본진 수비하면서 상대 드론까지 잡아냅니다!',
              owner: LogOwner.home,
              awayArmy: -1,
              homeResource: -100,
              homeArmy: 2,
              awayResource: -150,
              altText: '{home} 선수 일방적인 이득을 통해 승기를 굳힙니다!',
            ),
            ScriptEvent(
              text: '{home} 선수의 멀티태스킹 능력을 여실히 볼 수 있는 경기였네요!',
              owner: LogOwner.home,
              homeArmy: 1,
              awayArmy: -2,
              homeResource: -50,
              awayResource: -100,
              decisive: true,
              altText: '{home} 선수 컨트롤 차이를 보여주며 빠르게 경기를 끝내려고 합니다!',
            ),
          ],
        ),
        // ── 분기 D: 엇갈림 → 어웨이 멀티태스킹 승리 (decisive) ──
        ScriptBranch(
          id: 'cross_away_wins',
          description: '(phase2) 분기D - 엇갈림 어웨이 승',
          baseProbability: 0.2,
          conditionStat: 'control+defense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '초반 저글링 교전 후 약간의 소강상태입니다. 저글링 추가하고 발업을 기다리며 다시 기회를 보는데요.',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
            ),
            ScriptEvent(
              text: '서로의 저글링이 만나지 못하고 엇갈립니다! 양쪽 진영을 노립니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: -50,
              awayResource: -50,
              altText: '양쪽 발업 저글링이 서로의 병력을 보지 못하고 지나칩니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 저글링이 {away} 선수의 진영을 먼저 공격합니다!',
              owner: LogOwner.home,
              homeArmy: -1,
              awayArmy: 0,
              homeResource: -50,
              awayResource: 0,
              altText: '{home} 선수가 먼저 상대방 드론을 노려줍니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 환상적인 드론 뭉치기! 추가 저글링도 합류해서 잡아냅니다!',
              owner: LogOwner.away,
              awayArmy: -1,
              homeResource: -150,
              awayResource: -50,
              homeArmy: -3,
              altText: '{away} 드론을 뭉쳐서 히드라처럼 사용하며 피해를 최소화 합니다! 저글링도 추가 생산되며 수비합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 뛰어난 화면전환으로 본인 드론은 다 살리고 상대방 드론은 끝까지 쫓아가서 죽입니다, 상대방의 추가 저글링도 각개격파 당합니다!',
              owner: LogOwner.away,
              homeArmy: -3,
              awayArmy: -1,
              awayResource: -50,
              homeResource: -150,
              altText: '{away} 선수 본진 수비를 진행하며 상대방의 본진은 초토화시킵니다! 추가로 생산되는 상대방 저글링도 끊어줍니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 추가 저글링을 상대방 본진으로 계속 투입시키며 승기를 굳히려고 합니다!',
              owner: LogOwner.away,
              homeArmy: -1,
              awayResource: -100,
              awayArmy: 2,
              homeResource: -150,
              altText: '{away} 선수, 양쪽 전선을 동시 관리에 성공합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수의 집중력이 멀티태스킹으로 이어지고 멀티태스킹이 승부를 갈랐습니다!',
              owner: LogOwner.away,
              homeArmy: -2,
              awayArmy: 1,
              homeResource: -100,
              awayResource: -50,
              decisive: true,
              altText: '{away} 선수 빠른 손놀림을 보여주며 컨트롤 차이를 보여줍니다!',
            ),
          ],
        ),
        // ── 분기 E: 양쪽 눈치 싸움 → 레어 전환 (non-decisive → Phase 3) ──
        ScriptBranch(
          id: 'both_transition',
          description: '(phase2) 분기E - 양쪽 레어 전환',
          baseProbability: 2.0,
          events: [
            ScriptEvent(
              text: '양쪽 다 큰 싸움은 피하며 소수의 저글링으로 계속 상대방을 확인합니다.',
              owner: LogOwner.system,
              homeArmy: -2,
              awayArmy: -2,
              homeResource: -100,
              awayResource: -100,
              altText: '서로 저글링 수를 유지하면서 소수의 저글링을 돌리며 눈치싸움을 이어갑니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 레어 진화 시작합니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -250,
              altText: '{home} 선수 레어 올립니다.',
            ),
            ScriptEvent(
              text: '{away} 선수도 레어 진화를 선택합니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -250,
              altText: '{away} 선수도 레어 진화합니다.',
            ),
            ScriptEvent(
              text: '두 선수 저글링 숫자가 차이가 부담되어 함부로 확장이나 드론을 뽑지 못하고 저글링을 계속 추가해줍니다.',
              owner: LogOwner.system,
              homeArmy: 2,
              awayArmy: 2,
              homeResource: -100,
              awayResource: -100,
              altText: '확장이나 드론 생산 시 상대방의 공격이 이루어질 수 있기 때문에 두 선수 모두 계속해서 저글링을 추가합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수 레어 완성되며 스파이어 건설합니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              awayResource: 0,
              homeResource: -350,
              altText: '{home} 선수 레어 완성과 동시에 스파이어 올립니다.',
            ),
            ScriptEvent(
              text: '{away} 선수도 레어 진화 완료 후 스파이어 따라갑니다.',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: -350,
              altText: '{away} 선수도 스파이어 따라가며 테크 맞춰줍니다.',
            ),
          ],
        ),
        // ── 분기 F: 홈 저글링 올인 vs 어웨이 레어 (non-decisive → Phase 3) ──
        // 레어 150원 = 저글링 6기 차이를 노리는 타이밍 공격
        ScriptBranch(
          id: 'home_ling_allin',
          description: '(phase2) 분기F - 홈 저글링 올인',
          baseProbability: 0.2,
          conditionStat: 'attack',
          events: [
            ScriptEvent(
              text: '{away} 선수, 상대도 발업인 것 확인하고 저글링 빼면서 레어 진화합니다.',
              owner: LogOwner.away,
              homeArmy: 1,
              awayArmy: 0,
              homeResource: -50,
              awayResource: -250,
              altText: '{away} 선수 저글링을 빼고 레어 선택, 뮤탈 싸움을 이어가겠다는 거죠.',
            ),
            ScriptEvent(
              text: '{home} 선수 레어는 조금 미루고 저글링을 추가적으로 더 뽑는데요!',
              owner: LogOwner.home,
              awayArmy: 0,
              awayResource: -50,
              homeArmy: 3,
              homeResource: -150,
              altText: '{home} 선수 레어 대신 저글링 선택, 숫자 차이가 나겠는데요!',
            ),
            ScriptEvent(
              text: '{home} 선수가 상대방이 테크에 돈을 쓴 타이밍을 노립니다!',
              owner: LogOwner.system,
              homeArmy: 1,
              awayArmy: 0,
              homeResource: -50,
              awayResource: 50,
              altText: '{home} 선수 저글링 물량으로 밀어붙이겠다는 판단!',
            ),
          ],
        ),
        // ── 분기 G: 어웨이 저글링 올인 vs 홈 레어 (non-decisive → Phase 3) ──
        ScriptBranch(
          id: 'away_ling_allin',
          description: '(phase2) 분기G - 어웨이 저글링 올인',
          baseProbability: 0.2,
          conditionStat: 'attack',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{home} 선수, 상대방 발업 확인 후 저글링 복귀 시키며 레어를 누릅니다.',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 1,
              awayResource: -50,
              homeResource: -250,
              altText: '{home} 선수 저글링을 빼고 레어를 가며 공중전을 노립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수, 타이밍을 노리며 저글링을 더 뽑습니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              homeResource: -50,
              awayArmy: 3,
              awayResource: -150,
              altText: '{away} 선수 레어 대신 저글링 추가 선택, 어떤 결과로 이어질까요?',
            ),
            ScriptEvent(
              text: '{away} 선수가 병력에 돈을 더 쓰고 약간의 틈을 노리려고 합니다!',
              owner: LogOwner.system,
              homeArmy: 0,
              awayArmy: 1,
              homeResource: 50,
              awayResource: -50,
              altText: '{away} 선수 테크에 돈을 사용한 상대방을 잡아먹을 생각을 합니다!',
            ),
          ],
        ),
      ],
    ),
    // Phase 3: 중반 해결 — 뮤탈 경쟁 or 올인 결과
    ScriptPhase(
      name: 'midgame_resolution',
      recoveryArmyPerLine: 1,
      branches: [
        // ── 양쪽 레어 → 뮤탈전 여러 라운드 → 홈 승리 ──
        ScriptBranch(
          id: 'both_muta_home_wins',
          description: '(phase3) 분기A - 뮤탈전 홈 승',
          conditionPriorBranchIds: ['both_transition'],
          conditionStat: 'control+sense',
          events: [
            ScriptEvent(
              text: '뮤탈 싸움 직전인데요, 오버로드를 잘 숨기는 것도 실력입니다.',
              owner: LogOwner.system,
              homeResource: -100,
              awayResource: -100,
              homeArmy: 0,
              awayArmy: 0,
              altText: '곧 뮤탈이 뜨면서 싸움이 시작될텐데 오버로드 한 두기 끊기는 건 영향이 클 수 있으니 잘 숨겨놔야합니다.',
            ),
            ScriptEvent(
              text: '{home} 선수, 굉장히 안전하게 본진에 성큰을 박고 스커지를 먼저 뽑아줍니다.',
              owner: LogOwner.home,
              homeArmy: 1,
              awayArmy: 0,
              homeResource: -225,
              awayResource: 0,
              altText: '{home} 선수 상대방이 저글링으로 멀티태스킹을 거는 것을 방지하기 위해 본진에 성큰을 올리며 스커지를 먼저 생산합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수, 뮤탈이 상대방 스커지 도착 전 나오기 시작하며 스커지도 섞어줍니다.',
              owner: LogOwner.away,
              awayArmy: 3,
              homeResource: 0,
              awayResource: -300,
              homeArmy: 0,
              altText: '{away} 선수 뮤탈이 상대방 스커지가 도착하기 전 나와서 나오자마자 격추 되는 것을 피합니다. 스커지도 추가해주는데요.',
            ),
            ScriptEvent(
              text: '{home} 선수도 뮤탈을 모으며 아직 멀리 빼지 못한 {away} 선수의 오버로드 한기를 끊어줍니다!',
              owner: LogOwner.home,
              homeArmy: 4,
              awayArmy: 0,
              awayResource: -100,
              homeResource: -400,
              altText: '{home} 선수, 뮤탈로 가까이에 있는 {away} 선수의 오버로드를 발견하고 제거합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수, 랠리를 상대방 본진으로 찍은 후 인구수가 막혔을 때를 노려 컨트롤 싸움을 겁니다!',
              owner: LogOwner.home,
              awayArmy: 0,
              homeResource: 0,
              homeArmy: 2,
              awayResource: -200,
              altText: '{home} 선수 오버로드를 뽑아야해서 병력 추가를 못하는 {away} 선수 진영을 노립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수는 지금까지 뽑아놓은 저글링을 돌려 신경쓰이게 하려 하지만 {home} 선수의 본진엔 성큰이 있습니다!',
              owner: LogOwner.away,
              homeArmy: -2,
              awayArmy: -6,
              homeResource: -50,
              awayResource: -300,
              altText: '{away} 선수, 회심의 저글링 돌리기! 그러나 {home} 선수는 성큰으로 대비를 하고 공격을 갔습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수, 상대방 본진을 공격합니다. 오버로드가 끊겼던 사이 물량 차이가 발생합니다!',
              owner: LogOwner.home,
              awayArmy: -9,
              homeResource: -200,
              homeArmy: -3,
              awayResource: -500,
              altText: '{home} 선수 상대방의 인구수가 막혔던 시간만큼 벌어진 물량 차이로 상대방 병력을 압도합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 계속해서 병력 보내며 압박합니다. 작은 틈도 놓치지 않고 파고드네요!',
              owner: LogOwner.home,
              homeArmy: -1,
              awayArmy: -2,
              homeResource: -100,
              awayResource: -300,
              decisive: true,
            ),
          ],
        ),
        // ── 양쪽 레어 → 뮤탈전 여러 라운드 → 어웨이 승리 ──
        ScriptBranch(
          id: 'both_muta_away_wins',
          description: '(phase3) 분기B - 뮤탈전 어웨이 승',
          conditionPriorBranchIds: ['both_transition'],
          conditionStat: 'control+sense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '오버로드를 상대방 진영에서 빼주면서 서로 뮤탈 싸움을 준비합니다.',
              owner: LogOwner.system,
              homeResource: -100,
              awayResource: -100,
              homeArmy: 0,
              awayArmy: 0,
              altText: '서로 스파이어를 본 순간 오버로드를 최대한 멀리 보내야죠.',
            ),
            ScriptEvent(
              text: '{away} 선수 뮤탈을 뽑기 시작합니다. 그리고 저글링 소수를 돌려 상대방 본진 견제를 노립니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 2,
              homeResource: 0,
              awayResource: -200,
              altText: '{away} 선수, 뮤탈 생산하며 소수의 저글링으로 상대방 본진의 드론을 견제합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 나가있던 저글링이 수비하러 돌아오지만 드론 한기가 잡히고 일을 못한 피해를 입습니다.',
              owner: LogOwner.home,
              homeArmy: -1,
              awayArmy: -1,
              awayResource: -50,
              homeResource: -100,
              altText: '{home} 선수 상대방 본진을 향하던 저글링이 돌아와서 수비하지만 이미 드론 한기가 죽는 피해가 생깁니다.',
            ),
            ScriptEvent(
              text: '양쪽 뮤탈이 나옵니다. 계속해서 소수의 저글링을 던지며 상대방 병력 조합 및 위치를 확인하려 합니다.',
              owner: LogOwner.system,
              homeResource: -250,
              awayResource: -250,
              homeArmy: 3,
              awayArmy: 3,
              altText: '서로 뮤탈이 나오기 시작합니다. 소수의 저글링을 던짐으로써 서로의 병력 위치 및 조합을 확인합니다.',
            ),
            ScriptEvent(
              text: '{away} 선수, 본인 오버로드를 제거하느라 밖에 있는 상대방 뮤탈을 확인하고는 남아있는 저글링으로 상대방 본진을 습격합니다!',
              owner: LogOwner.away,
              homeArmy: -2,
              awayArmy: -1,
              awayResource: 150,
              homeResource: 0,
              altText: '{away} 선수 상대방 뮤탈이 본인 오버로드를 제거하는 동안 저글링으로 {home} 선수 본진에 침투합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 오버로드를 끊어내고 곧바로 돌아와 수비를 하지만 드론 피해가 있습니다!',
              owner: LogOwner.home,
              homeArmy: -1,
              homeResource: -50,
              awayResource: 50,
              awayArmy: 0,
              altText: '{home} 선수 상대방 저글링에 의한 드론 피해가 쌓이고 있습니다!',
            ),
            ScriptEvent(
              text: '{home} 선수도 저글링을 상대방 본진으로 투입하고 뮤탈과 스커지도 이동하며 양방향 컨트롤을 겁니다!',
              owner: LogOwner.home,
              homeArmy: 4,
              awayArmy: 2,
              homeResource: 0,
              awayResource: 100,
              altText: '{home} 선수 이대로가면 드론 숫자 차이로 결국 벌어지기 때문에 저글링과 뮤탈로 컨트롤 싸움을 겁니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 뮤탈 컨트롤에 온 신경을 집중하며 상대방 스커지를 모두 격추 시킵니다!',
              owner: LogOwner.away,
              awayArmy: 2,
              awayResource: -300,
              homeArmy: -5,
              homeResource: -500,
              altText: '{away} 선수의 뮤탈은 상대방 스커지가 박을 수가 없네요 환상적인 컨트롤!',
            ),
            ScriptEvent(
              text: '{home} 선수 상대방 뮤탈이 스커지를 잡는 컨트롤을 하는동안 뒤를 잡았지만 스커지가 몰살하며 병력차이로 밀립니다!',
              owner: LogOwner.home,
              awayArmy: 1,
              awayResource: -50,
              homeArmy: -3,
              homeResource: -100,
              altText: '{home} 선수의 스커지가 하나도 적중하지 못하며 뮤탈 개체수 차이를 극복하기 어려워 보입니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 뮤탈 싸움에서 우위를 점하며 본진에 들어온 저글링을 제거합니다!',
              owner: LogOwner.away,
              awayArmy: 0,
              awayResource: -50,
              homeArmy: -3,
              homeResource: -150,
              altText: '{away} 선수 약간의 드론 피해는 있었지만 뮤탈 싸움을 승리하며 저글링도 처리합니다!',
            ),
            ScriptEvent(
              text: '몇 차례 견제를 주고받았지만 {away} 선수 쪽이 드론을 더 많이 끊었습니다!',
              owner: LogOwner.system,
              homeArmy: 1,
              awayArmy: 2,
              homeResource: 50,
              awayResource: 100,
              altText: '교전의 결과로 나타난 차이, {away} 선수가 드론 수에서 앞서기 시작합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수, 스커지를 계속해서 추가하며 상대방 뮤탈을 줄이려고 하지만 뮤탈이 모일 수록 쉽지않습니다!',
              owner: LogOwner.home,
              homeArmy: -2,
              awayResource: -100,
              awayArmy: 1,
              homeResource: -150,
              altText: '{home} 선수 드론 개수 차이로 인해 자원이 밀리기 시작합니다! 뮤탈이 모이면 스커지 잡기가 더 쉬워지죠!',
            ),
            ScriptEvent(
              text: '누적된 드론 차이가 큰데요! {away} 선수 뮤탈 물량으로 밀어붙입니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
            ),
          ],
        ),

        // ── 홈 올인 성공: 저글링 물량으로 레어 건설 중인 어웨이 붕괴 ──
        ScriptBranch(
          id: 'home_ling_crush',
          description: '(phase3) 분기C - 홈 올인 성공',
          conditionPriorBranchIds: ['home_ling_allin'],
          conditionStat: 'control+sense',
          events: [
            ScriptEvent(
              text: '{home} 선수, 저글링을 몰고 들어갑니다! 물량 차이가 납니다!',
              owner: LogOwner.home,
              homeArmy: 1,
              homeResource: -50,
              awayResource: -100,
              awayArmy: -2,
              altText: '{home} 선수 저글링 돌진! 계속해서 추가 저글링이 합류합니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 저글링이 밀리는데요 이러면 레어를 가는 이점이 없습니다!',
              owner: LogOwner.away,
              homeArmy: -2,
              homeResource: -100,
              awayArmy: -6,
              awayResource: -300,
              altText: '{away} 선수 드론과 함께 막아보려하지만 저글링 숫자 차이로 밀립니다!',
            ),
            ScriptEvent(
              text: '상대방의 테크 선택, 그 작은 틈을 노린 {home} 선수의 타이밍이 일품입니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 자칫하면 테크에서 밀릴 수 있던 과감한 선택이 승기를 가져옵니다!',
            ),
          ],
        ),
        // ── 홈 올인 실패: 어웨이가 수비 → 빠른 뮤탈 → 스커지 저격 ──
        ScriptBranch(
          id: 'home_allin_fails',
          description: '(phase3) 분기D - 홈 올인 실패',
          conditionPriorBranchIds: ['home_ling_allin'],
          conditionStat: 'defense+sense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수, 언덕 저글링으로 입구를 막습니다! 시간을 벌며 추가 저글링 뽑습니다!',
              owner: LogOwner.away,
              homeResource: -100,
              awayResource: -50,
              homeArmy: -4,
              awayArmy: -3,
              altText: '{away} 선수 좁은 입구에서 저글링을 배치하며 소수 저글링끼리만 싸우게 컨트롤합니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 피해를 크게 주지 못하면 테크에서 밀리는데요. 계속해서 입구를 뚫지 못합니다!',
              owner: LogOwner.home,
              awayArmy: -2,
              awayResource: -100,
              homeArmy: -3,
              homeResource: -150,
              altText: '{home} 선수 저글링 숫자 차이를 교전에 사용을 못합니다! 손해가 쌓이는데요.',
            ),
            ScriptEvent(
              text: '{away} 선수, 레어가 먼저 완성! 스파이어 올리며 수비를 이어갑니다.',
              owner: LogOwner.away,
              homeArmy: 1,
              awayArmy: 0,
              homeResource: -50,
              awayResource: -300,
              altText: '{away} 선수 레어 완성 후 곧바로 스파이어 올립니다.',
            ),
            ScriptEvent(
              text: '{away} 선수, 뮤탈 기다리며 본진에 성큰까지 올립니다. 상대방은 저글링 올인밖에 없다는 판단이죠!',
              owner: LogOwner.away,
              homeArmy: 1,
              homeResource: -50,
              awayArmy: 2,
              awayResource: -125,
              altText: '{away} 선수 안전하게 성큰까지 건설합니다! 뮤탈은 무조건 먼저 나오니 저글링 수비만 하면된다는 판단이죠!',
            ),
            ScriptEvent(
              text: '{home} 선수 마지막으로 저글링을 쥐어 짜내서 공격하지만 {away} 선수의 성큰과 수비병력을 뚫지 못합니다!',
              owner: LogOwner.home,
              homeArmy: -6,
              awayArmy: -1,
              awayResource: -50,
              homeResource: -250,
              altText: '{home} 선수 저글링으로 끝장을 보려고 최후의 공격을 하지만 성큰과 수비병력에 너무 쉽게 막힙니다!',
            ),
            ScriptEvent(
              text: '{away} 선수의 뮤탈이 생산되는걸 보자마자 {home} 선수는 전의를 상실합니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 뮤탈 나오자마자 상대방 본진으로 날아갑니다. {home} 선수 막을 길이 없죠!',
            ),
          ],
        ),

        // ── 어웨이 올인 성공: 저글링 물량으로 레어 건설 중인 홈 붕괴 ──
        ScriptBranch(
          id: 'away_ling_crush',
          description: '(phase3) 분기E - 어웨이 올인 성공',
          conditionPriorBranchIds: ['away_ling_allin'],
          conditionStat: 'control+sense',
          homeStatMustBeHigher: false,
          events: [
            ScriptEvent(
              text: '{away} 선수, 저글링을 몰고 들어갑니다! 레어에 자원을 쓴 상대는 저글링이 확실히 적습니다!',
              owner: LogOwner.away,
              awayArmy: 1,
              homeResource: -100,
              awayResource: -50,
              homeArmy: -2,
              altText: '{away} 선수 저글링 돌진! 저글링이 계속해서 추가됩니다!',
            ),
            ScriptEvent(
              text: '{home} 선수 저글링 숫자에서 밀립니다! 입구가 벌써 뚫립니다!',
              owner: LogOwner.home,
              awayArmy: -2,
              awayResource: -100,
              homeArmy: -6,
              homeResource: -300,
              altText: '{home} 선수 수비진영을 탄탄하게 못 만들었어요 숫자 차이로 쉽게 밀립니다!',
            ),
            ScriptEvent(
              text: '빠른 테크 선택을 한 상대방의 작은 틈을 노린 {away} 선수의 과감함이 돋보입니다!',
              owner: LogOwner.away,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{away} 선수 정교한 타이밍으로 승기를 잡습니다!',
            ),
          ],
        ),
        // ── 어웨이 올인 실패: 홈이 수비 → 빠른 뮤탈 → 스커지 저격 ──
        ScriptBranch(
          id: 'away_allin_fails',
          description: '(phase3) 분기F - 어웨이 올인 실패',
          conditionPriorBranchIds: ['away_ling_allin'],
          conditionStat: 'defense+sense',
          events: [
            ScriptEvent(
              text: '{home} 선수, 입구를 좁히며 저글링으로 학익진을 펼칩니다. 이러면 병력이 많아도 뚫기에 시간이 걸립니다!',
              owner: LogOwner.home,
              homeResource: -50,
              awayResource: -100,
              awayArmy: -2,
              homeArmy: -1,
              altText: '{home} 상대방 저글링이 도착하기전 입구에 수비 병력을 배치합니다. 이렇게 되면 소수 저글링싸움만 반복되죠!',
            ),
            ScriptEvent(
              text: '{away} 선수 좁은 입구를 많은 병력으로도 쉽사리 뚫지 못합니다! 피해를 줘야하는데요!',
              owner: LogOwner.away,
              homeArmy: -2,
              awayArmy: -3,
              homeResource: -100,
              awayResource: -150,
              altText: '{away} 선수 계속해서 소수 저글링싸움이 되는 언덕 교전에 답답함을 느낍니다!',
            ),
            ScriptEvent(
              text: '{home} 선수, 레어 완성 후 스파이어까지 올립니다. 수비만 하면 상대방은 뮤탈을 막을 수단이 없습니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 1,
              awayResource: -50,
              homeResource: -300,
              altText: '{away} 선수 레어 완성 되자마자 스파이어 건설하며 수비 이어갑니다. 막기만 하면 유리하죠!',
            ),
            ScriptEvent(
              text: '{home} 선수 뮤탈을 기다리며 수비적으로 본진에 성큰까지 올리며 저글링에 대한 수비력을 더더욱 높입니다!',
              owner: LogOwner.home,
              homeArmy: 2,
              awayArmy: 1,
              awayResource: -50,
              homeResource: -125,
              altText: '{home} 선수 저글링 올인만 막으면 된다는 생각으로 본진 성큰까지 건설하며 뮤탈을 기다립니다!',
            ),
            ScriptEvent(
              text: '{away} 선수 마지막 저글링 짜내기로 본진까지 밀어내려 하지만 이미 성큰이 건설되어 있어요!',
              owner: LogOwner.away,
              homeArmy: -1,
              awayArmy: -6,
              homeResource: -50,
              awayResource: -250,
              altText: '{away} 선수 이미 뮤탈은 늦었다는 판단, 저글링 올인을 선택하지만 본진에서 수비하고 있는 {home} 선수에게 쉽게 막힙니다!',
            ),
            ScriptEvent(
              text: '수비 성공한 순간부터 {home} 선수는 너무 여유롭죠, 뮤탈 뽑아서 상대방 진영으로 이동합니다!',
              owner: LogOwner.home,
              homeArmy: 0,
              awayArmy: 0,
              homeResource: 0,
              awayResource: 0,
              decisive: true,
              altText: '{home} 선수 뮤탈 생산 되자마자 상대방 쪽으로 이동하며 경기 마무리를 하러갑니다!',
            ),
          ],
        ),
      ],
    ),
  ],
);
